"""matcha_work_document — coerce helpers (L6 split).

Extracted from the monolithic service; re-exported by the package __init__.
"""
from datetime import datetime, timezone
from typing import Optional
import json
import re

import logging
logger = logging.getLogger(__name__)

EMAIL_REGEX = re.compile(r"\b[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}\b")

VALID_REVIEW_REQUEST_STATUSES = {"pending", "sent", "failed", "submitted"}

def _parse_jsonb(value) -> dict:
    """Parse a JSONB value from asyncpg (may be str or dict)."""
    if isinstance(value, str):
        return json.loads(value)
    if isinstance(value, dict):
        return value
    return {}

def _infer_skill_from_state(current_state: dict) -> str:
    """Infer the active skill from current_state contents."""
    if not current_state:
        return "chat"
    if any(k in current_state for k in ("candidate_name", "position_title", "salary", "salary_range_min")):
        return "offer_letter"
    if any(k in current_state for k in ("overall_rating", "review_title", "review_request_statuses", "review_expected_responses")):
        return "review"
    if any(k.startswith("handbook_") for k in current_state):
        return "handbook"
    if any(k.startswith("policy_") for k in current_state):
        return "policy"
    if "sections" in current_state or "workbook_title" in current_state:
        return "workbook"
    if any(k in current_state for k in ("employees", "batch_status")):
        return "onboarding"
    if any(k in current_state for k in ("presentation_title", "slides")):
        return "presentation"
    return "chat"

def _strip_markdown_text(value: str) -> str:
    """Lightweight markdown stripping for slide bullet extraction."""
    text = value or ""
    text = re.sub(r"`{1,3}([^`]+)`{1,3}", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r"\1", text)
    text = re.sub(r"^\s{0,3}#{1,6}\s*", "", text, flags=re.MULTILINE)
    text = re.sub(r"\*\*([^*]+)\*\*", r"\1", text)
    text = re.sub(r"\*([^*]+)\*", r"\1", text)
    return text.strip()

def _extract_slide_bullets(content: str, max_points: int = 5) -> list[str]:
    cleaned = _strip_markdown_text(content)
    if not cleaned:
        return []

    bullets: list[str] = []
    for raw_line in cleaned.splitlines():
        line = re.sub(r"^\s*(?:[-*•]+|\d+[.)])\s*", "", raw_line).strip()
        if not line:
            continue
        if len(line) > 180:
            line = line[:177].rstrip() + "..."
        bullets.append(line)
        if len(bullets) >= max_points:
            break

    if bullets:
        return bullets

    sentence_chunks = re.split(r"(?<=[.!?])\s+", cleaned)
    for chunk in sentence_chunks:
        line = chunk.strip()
        if not line:
            continue
        if len(line) > 180:
            line = line[:177].rstrip() + "..."
        bullets.append(line)
        if len(bullets) >= max_points:
            break
    return bullets

def _build_workbook_presentation_state(state: dict) -> dict:
    workbook_title = str(state.get("workbook_title") or "").strip() or "HR Workbook"
    company_name = str(state.get("company_name") or "").strip()
    objective = str(state.get("objective") or "").strip()
    sections = state.get("sections")
    if not isinstance(sections, list):
        sections = []

    slides: list[dict] = []
    title_bullets = []
    if company_name:
        title_bullets.append(company_name)
    if objective:
        title_bullets.append(objective)
    if not title_bullets:
        title_bullets.append("Generated by Matcha Work")

    slides.append(
        {
            "title": workbook_title,
            "bullets": title_bullets,
            "speaker_notes": "Opening context and presentation goals.",
        }
    )

    agenda_titles = []
    for section in sections:
        if not isinstance(section, dict):
            continue
        section_title = str(section.get("title") or "").strip()
        if section_title:
            agenda_titles.append(section_title)

    if agenda_titles:
        slides.append(
            {
                "title": "Agenda",
                "bullets": agenda_titles[:8],
                "speaker_notes": "Walk through section flow.",
            }
        )

    for section in sections:
        if not isinstance(section, dict):
            continue
        section_title = str(section.get("title") or "").strip() or "Section"
        content = str(section.get("content") or "").strip()
        bullets = _extract_slide_bullets(content)
        if not bullets:
            continue
        slides.append(
            {
                "title": section_title,
                "bullets": bullets,
                "speaker_notes": f"Discuss key points for {section_title.lower()}.",
            }
        )

    if len(slides) == 1:
        slides.append(
            {
                "title": "Key Points",
                "bullets": [
                    "Add workbook sections to generate richer slides.",
                    "Use clear section headings and concise guidance.",
                    "Regenerate after updating workbook content.",
                ],
                "speaker_notes": "Placeholder slide until workbook sections are available.",
            }
        )

    slides.append(
        {
            "title": "Next Steps",
            "bullets": [
                "Confirm owners for each policy/process area.",
                "Set rollout timeline and communication plan.",
                "Track follow-up actions in Matcha Work.",
            ],
            "speaker_notes": "Close with implementation steps.",
        }
    )

    generated_at = datetime.now(timezone.utc).isoformat()
    presentation_title = f"{workbook_title} - Presentation"
    presentation_subtitle = company_name or objective or None

    return {
        "title": presentation_title,
        "subtitle": presentation_subtitle,
        "generated_at": generated_at,
        "slides": slides,
        "slide_count": len(slides),
    }

def _parse_date_str(date_str: str) -> Optional[datetime]:
    """Try common date formats."""
    formats = [
        "%Y-%m-%d",
        "%B %d, %Y",
        "%b %d, %Y",
        "%m/%d/%Y",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S.%f",
    ]
    for fmt in formats:
        try:
            return datetime.strptime(date_str, fmt)
        except ValueError:
            continue
    return None

def _coerce_bool(value, default: bool = False) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return bool(value)
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"true", "1", "yes", "y"}:
            return True
        if normalized in {"false", "0", "no", "n", ""}:
            return False
    return default

def _coerce_int(value) -> Optional[int]:
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None

def _coerce_float(value) -> Optional[float]:
    if value is None:
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None

def _coerce_datetime(value) -> Optional[datetime]:
    if isinstance(value, datetime):
        return value
    if isinstance(value, str):
        return _parse_date_str(value)
    return None

def _normalize_email(email: str) -> Optional[str]:
    normalized = (email or "").strip().lower()
    if not normalized:
        return None
    if not EMAIL_REGEX.fullmatch(normalized):
        return None
    return normalized

def normalize_recipient_emails(values: list[str]) -> list[str]:
    deduped: list[str] = []
    seen: set[str] = set()
    for raw in values:
        email = _normalize_email(raw)
        if not email or email in seen:
            continue
        seen.add(email)
        deduped.append(email)
    return deduped

def _coerce_state_recipient_emails(state: dict) -> list[str]:
    raw = state.get("recipient_emails")
    if not isinstance(raw, list):
        return []
    return normalize_recipient_emails([str(item) for item in raw])

def _coerce_offer_draft_recipient_emails(state: dict) -> list[str]:
    values: list[str] = []
    raw_recipients = state.get("recipient_emails")
    if isinstance(raw_recipients, list):
        values.extend(str(item) for item in raw_recipients if str(item).strip())
    candidate_email = state.get("candidate_email")
    if isinstance(candidate_email, str) and candidate_email.strip():
        values.append(candidate_email)
    return normalize_recipient_emails(values)

def _row_to_review_request_status(row: dict) -> dict:
    status = str(row.get("status") or "pending")
    if status not in VALID_REVIEW_REQUEST_STATUSES:
        status = "pending"
    return {
        "email": str(row.get("recipient_email") or "").strip().lower(),
        "status": status,
        "sent_at": row.get("sent_at"),
        "submitted_at": row.get("submitted_at"),
        "last_error": row.get("last_error"),
    }

def _build_review_request_state_update(status_rows: list[dict]) -> dict:
    recipient_emails = [str(row.get("email") or "").strip().lower() for row in status_rows if row.get("email")]
    expected = len(recipient_emails)
    received = sum(1 for row in status_rows if row.get("status") == "submitted")
    pending = max(expected - received, 0)

    latest_sent_at = None
    for row in status_rows:
        sent_at = row.get("sent_at")
        if isinstance(sent_at, datetime):
            if latest_sent_at is None or sent_at > latest_sent_at:
                latest_sent_at = sent_at

    serialized_status_rows = []
    for row in status_rows:
        serialized_status_rows.append(
            {
                "email": row.get("email"),
                "status": row.get("status"),
                "sent_at": row.get("sent_at").isoformat() if isinstance(row.get("sent_at"), datetime) else None,
                "submitted_at": (
                    row.get("submitted_at").isoformat()
                    if isinstance(row.get("submitted_at"), datetime)
                    else None
                ),
                "last_error": row.get("last_error"),
            }
        )

    return {
        "recipient_emails": recipient_emails,
        "review_request_statuses": serialized_status_rows,
        "review_expected_responses": expected,
        "review_received_responses": received,
        "review_pending_responses": pending,
        "review_last_sent_at": latest_sent_at.isoformat() if latest_sent_at else None,
    }
