#!/usr/bin/env bash
# Regenerate deploy/nginx/01-cloudfront-realip.conf from AWS's published
# ip-ranges.json.
#
# Why: every limit_req / limit_conn zone on the host keys on
# $binary_remote_addr, and behind CloudFront that is the POP's address, not the
# viewer's — one edge location shares a single bucket (docs/ops/MATCHA_EDGE.md,
# "nginx limit_req"). The generated file tells the realip module to trust
# X-Forwarded-For ONLY when the TCP peer is a CloudFront origin-facing address,
# so $remote_addr becomes the viewer and the limits key per viewer.
#
# Safety: a viewer cannot escape the limiter by sending their own
# X-Forwarded-For — CloudFront appends the true viewer address LAST, and realip
# walks from the right past trusted hops. A connection that is not from one of
# these ranges (a direct-to-origin scanner, or a new AWS range this snapshot
# predates) keeps its real peer address, i.e. today's behaviour.
#
# The output is committed; update-ec2.sh syncs deploy/nginx/*.conf to
# /etc/nginx/conf.d/ on every non-hotfix deploy. Re-run this when AWS adds
# ranges (the createDate below says how old the snapshot is).
set -euo pipefail

cd "$(dirname "$0")"
OUT=01-cloudfront-realip.conf
SRC="${1:-https://ip-ranges.amazonaws.com/ip-ranges.json}"

python3 - "$SRC" "$OUT" <<'EOF'
import ipaddress, json, sys, urllib.request

src, out = sys.argv[1], sys.argv[2]
raw = open(src).read() if not src.startswith("http") else urllib.request.urlopen(src, timeout=30).read()
d = json.loads(raw)

# CLOUDFRONT_ORIGIN_FACING is the set CloudFront connects to origins FROM. The
# broader CLOUDFRONT set is viewer-facing edge space that never reaches us.
v4 = sorted({p["ip_prefix"] for p in d["prefixes"] if p["service"] == "CLOUDFRONT_ORIGIN_FACING"},
            key=lambda s: ipaddress.ip_network(s))
if len(v4) < 20:
    sys.exit(f"refusing to write: only {len(v4)} origin-facing ranges (expected dozens)")
for s in v4:
    ipaddress.ip_network(s)  # validate before it reaches nginx -t

lines = [
    "# GENERATED by deploy/nginx/gen-cloudfront-realip.sh — do not hand-edit.",
    f"# Source: ip-ranges.json syncToken={d['syncToken']} createDate={d['createDate']}",
    f"# {len(v4)} CLOUDFRONT_ORIGIN_FACING IPv4 ranges. Our origin is IPv4-only",
    "# (origin.gummfit.com has no AAAA), so CloudFront never connects over v6.",
    "#",
    "# Makes $remote_addr / $binary_remote_addr the VIEWER address when the peer",
    "# is CloudFront, so limit_req/limit_conn key per viewer, not per POP.",
    "# Any other peer keeps its real address. See docs/ops/MATCHA_EDGE.md.",
    "",
]
lines += [f"set_real_ip_from {s};" for s in v4]
lines += ["", "real_ip_header X-Forwarded-For;", "real_ip_recursive on;", ""]
open(out, "w").write("\n".join(lines))
print(f"wrote {out}: {len(v4)} ranges, snapshot {d['createDate']}")
EOF
