from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401


# ---------------------------------------------------------------------------
# CATEGORY_ALIASES — map common misspellings / variants to canonical keys
# ---------------------------------------------------------------------------

CATEGORY_ALIASES: Dict[str, str] = {
    "meal_rest_breaks": "meal_breaks",
    "meal_and_rest_breaks": "meal_breaks",
    "meal_periods": "meal_breaks",
    "rest_breaks": "meal_breaks",
    "payday_frequency": "pay_frequency",
    "pay_day_frequency": "pay_frequency",
    "final_wage": "final_pay",
    "final_wages": "final_pay",
    "final_paycheck": "final_pay",
    "final_paychecks": "final_pay",
    "minor_work_permits": "minor_work_permit",
    "work_permit": "minor_work_permit",
    "work_permits": "minor_work_permit",
    "youth_employment": "minor_work_permit",
    "youth_work_permit": "minor_work_permit",
    "scheduling_and_reporting_time": "scheduling_reporting",
    "reporting_time": "scheduling_reporting",
    "predictive_scheduling": "scheduling_reporting",
    "fair_workweek": "scheduling_reporting",
    "leave_of_absence": "leave",
    "family_leave": "leave",
    "medical_leave": "leave",
    "pfml": "leave",
    "paid_family_leave": "leave",
    "family_medical_leave": "leave",
    "osha": "workplace_safety",
    "occupational_safety": "workplace_safety",
    "safety": "workplace_safety",
    "workplace_health": "workplace_safety",
    "workers_compensation": "workers_comp",
    "worker_comp": "workers_comp",
    "workman_comp": "workers_comp",
    "workmen_comp": "workers_comp",
    "discrimination": "anti_discrimination",
    "harassment": "anti_discrimination",
    "equal_pay": "anti_discrimination",
    "pay_equity": "anti_discrimination",
    "ada": "anti_discrimination",
    "ada_accommodations": "anti_discrimination",
    # Healthcare categories
    "hipaa": "hipaa_privacy",
    "hipaa_security": "hipaa_privacy",
    "hitech": "hipaa_privacy",
    "phi": "hipaa_privacy",
    "42_cfr_part_2": "hipaa_privacy",
    "part_2": "hipaa_privacy",
    "substance_use_records": "hipaa_privacy",
    "false_claims": "billing_integrity",
    "anti_kickback": "billing_integrity",
    "stark_law": "billing_integrity",
    "medicare_billing": "billing_integrity",
    "mhpaea": "billing_integrity",
    "mental_health_parity": "billing_integrity",
    "joint_commission": "clinical_safety",
    "cms_conditions": "clinical_safety",
    "infection_control": "clinical_safety",
    "bloodborne_pathogens": "clinical_safety",
    "medical_waste": "clinical_safety",
    "epa_medical_waste": "clinical_safety",
    "credentialing": "healthcare_workforce",
    "oig_exclusion": "healthcare_workforce",
    "mandatory_reporter": "healthcare_workforce",
    "oig_compliance": "corporate_integrity",
    "qui_tam": "corporate_integrity",
    "irb": "research_consent",
    "gcp": "research_consent",
    "facility_licensure": "state_licensing",
    "abortion": "state_licensing",
    "dobbs": "state_licensing",
    "ada_accessibility": "state_licensing",
    "emtala": "emergency_preparedness",
    "nfpa": "emergency_preparedness",
    "life_safety_code": "emergency_preparedness",
    # Life Sciences
    "gmp": "gmp_manufacturing",
    "cgmp": "gmp_manufacturing",
    "current_good_manufacturing": "gmp_manufacturing",
    "manufacturing_compliance": "gmp_manufacturing",
    "21_cfr_211": "gmp_manufacturing",
    "qsr": "gmp_manufacturing",
    "quality_system_regulation": "gmp_manufacturing",
    "glp": "glp_nonclinical",
    "good_laboratory_practice": "glp_nonclinical",
    "nonclinical_studies": "glp_nonclinical",
    "21_cfr_58": "glp_nonclinical",
    "good_clinical_practice": "clinical_trials_gcp",
    "clinical_trial": "clinical_trials_gcp",
    "clinical_trials": "clinical_trials_gcp",
    "ind": "clinical_trials_gcp",
    "ind_application": "clinical_trials_gcp",
    "ich_e6": "clinical_trials_gcp",
    "dscsa": "drug_supply_chain",
    "track_and_trace": "drug_supply_chain",
    "drug_pedigree": "drug_supply_chain",
    "serialization": "drug_supply_chain",
    "wholesale_distribution": "drug_supply_chain",
    "sunshine_act": "sunshine_open_payments",
    "open_payments": "sunshine_open_payments",
    "physician_payments": "sunshine_open_payments",
    "aggregate_spend": "sunshine_open_payments",
    "biosafety": "biosafety_lab",
    "bsl": "biosafety_lab",
    "ibc": "biosafety_lab",
    "select_agents": "biosafety_lab",
    "lab_safety": "biosafety_lab",
    "chemical_hygiene": "biosafety_lab",
}


