from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_ONCOLOGY: List[RegulationDef] = [

    # ── Oncology: radiation_safety ────────────────────────────────────────────
    RegulationDef(
        key="radiation_safety_officer", category="radiation_safety",
        name="Radiation Safety Officer Requirements",
        description="RSO qualifications, training, and responsibilities for radiation safety programs",
        enforcing_agency="NRC/State",
        state_variance="Moderate",
        update_frequency="NRC training and experience requirements updated periodically; 10 CFR 35 revisions",
        authority_sources=({"domain": "nrc.gov", "name": "NRC"},),
    ),
    RegulationDef(
        key="linear_accelerator_qa", category="radiation_safety",
        name="Linear Accelerator QA Requirements",
        description="Radiation therapy linear accelerator quality assurance and commissioning requirements",
        enforcing_agency="NRC/State",
        state_variance="Moderate",
        update_frequency="AAPM TG reports updated periodically; state regulations vary",
        authority_sources=({"domain": "nrc.gov", "name": "NRC"},),
    ),
    RegulationDef(
        key="brachytherapy_safety", category="radiation_safety",
        name="Brachytherapy Safety Standards",
        description="Internal radiation therapy safety, source management, and dose verification standards",
        enforcing_agency="NRC/State",
        state_variance="Moderate",
        update_frequency="NRC 10 CFR 35 updated periodically; AAPM/ABS guidelines evolve with technology",
        authority_sources=({"domain": "nrc.gov", "name": "NRC"},),
    ),
    RegulationDef(
        key="radiation_oncology_safety_team", category="radiation_safety",
        name="Radiation Oncology Safety Team",
        description="Multidisciplinary radiation safety oversight team requirements and incident review",
        enforcing_agency="ACR/ASTRO",
        state_variance="Moderate",
        update_frequency="ACR/ASTRO practice parameters updated every 5 years; TJC requirements evolve",
        authority_sources=({"domain": "astro.org", "name": "ASTRO"},),
    ),
    RegulationDef(
        key="radioactive_materials_license", category="radiation_safety",
        name="Radioactive Materials License",
        description="NRC or agreement state license for possession, use, and disposal of radioactive materials",
        enforcing_agency="NRC/Agreement States",
        state_variance="High",
        update_frequency="License renewals every 10 years; NRC/state inspection cycles vary",
        authority_sources=({"domain": "nrc.gov", "name": "NRC"},),
    ),
    RegulationDef(
        key="national_radiation_control", category="radiation_safety",
        name="National Radiation Control (International)",
        description="National radiation safety authority requirements (e.g., Mexico CNSNS) for radiation source licensing",
        enforcing_agency="National nuclear authority",
        state_variance="Moderate",
        update_frequency="National radiation safety frameworks evolving; IAEA guidance updated periodically",
        authority_sources=({"domain": "iaea.org", "name": "IAEA"},),
    ),

    # ── Oncology: chemotherapy_handling ────────────────────────────────────────
    RegulationDef(
        key="closed_system_transfer", category="chemotherapy_handling",
        name="Closed System Transfer Devices",
        description="CSTD requirements for hazardous drug handling to prevent occupational exposure",
        enforcing_agency="NIOSH/USP",
        state_variance="Moderate",
        update_frequency="USP <800> requirements evolving; NIOSH CSTD performance criteria updated periodically",
        authority_sources=({"domain": "cdc.gov/niosh", "name": "NIOSH"},),
    ),
    RegulationDef(
        key="hazardous_drug_assessment", category="chemotherapy_handling",
        name="Hazardous Drug Assessment",
        description="Risk assessment requirements for identifying and classifying hazardous drug handling risks",
        enforcing_agency="NIOSH",
        state_variance="Low/None",
        update_frequency="NIOSH hazardous drug list updated biennially; assessment methodologies evolve",
        authority_sources=({"domain": "cdc.gov/niosh", "name": "NIOSH"},),
    ),
    RegulationDef(
        key="spill_management", category="chemotherapy_handling",
        name="Hazardous Drug Spill Management",
        description="Spill kit requirements, cleanup procedures, and decontamination protocols for hazardous drugs",
        enforcing_agency="OSHA/USP",
        state_variance="Low/None",
        update_frequency="USP <800> spill management requirements; OSHA guidance stable",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="hazardous_waste_disposal", category="chemotherapy_handling",
        name="Hazardous Drug Waste Disposal",
        description="Classification and disposal requirements for chemotherapy and hazardous pharmaceutical waste",
        enforcing_agency="EPA/State",
        state_variance="Moderate",
        update_frequency="EPA hazardous waste pharmaceuticals rule 2019; state adoption ongoing",
        authority_sources=({"domain": "epa.gov", "name": "EPA"},),
    ),
    RegulationDef(
        key="national_hazardous_drug_handling", category="chemotherapy_handling",
        name="National Hazardous Drug Handling (International)",
        description="National hazardous drug handling standards and official norms (e.g., Mexico NOM standards)",
        enforcing_agency="National health authority",
        state_variance="Moderate",
        update_frequency="National standards updated periodically; alignment with international best practices ongoing",
        authority_sources=({"domain": "ilo.org", "name": "ILO"},),
    ),

    # ── Oncology: tumor_registry ──────────────────────────────────────────────
    RegulationDef(
        key="cancer_registry_reporting", category="tumor_registry",
        name="Cancer Registry Reporting",
        description="Mandatory cancer case reporting to state registries and the National Program of Cancer Registries",
        enforcing_agency="State cancer registries/CDC",
        state_variance="High",
        update_frequency="Reporting requirements updated annually; data standards revised by NAACCR",
        authority_sources=({"domain": "cdc.gov/cancer/npcr", "name": "CDC NPCR"},),
    ),
    RegulationDef(
        key="reporting_timelines", category="tumor_registry",
        name="Registry Reporting Timelines",
        description="Deadlines and timeliness requirements for cancer case reporting submission to state registries",
        enforcing_agency="State cancer registries",
        state_variance="High",
        update_frequency="State reporting deadlines vary; typically 6 months from diagnosis",
        authority_sources=({"domain": "cdc.gov/cancer/npcr", "name": "CDC NPCR"},),
    ),
    RegulationDef(
        key="electronic_reporting_format", category="tumor_registry",
        name="Electronic Reporting Format",
        description="NAACCR data standards and electronic format requirements for cancer case reporting",
        enforcing_agency="NAACCR",
        state_variance="Moderate",
        update_frequency="NAACCR data standards updated annually; format versions released periodically",
        authority_sources=({"domain": "naaccr.org", "name": "NAACCR"},),
    ),
    RegulationDef(
        key="registry_data_quality", category="tumor_registry",
        name="Registry Data Quality",
        description="Completeness, timeliness, and accuracy standards for cancer registry data",
        enforcing_agency="NAACCR/State",
        state_variance="Moderate",
        update_frequency="NAACCR certification standards updated annually; quality benchmarks evolve",
        authority_sources=({"domain": "naaccr.org", "name": "NAACCR"},),
    ),
    RegulationDef(
        key="national_cancer_registry", category="tumor_registry",
        name="National Cancer Registry (International)",
        description="National cancer registration systems and population-based registry requirements",
        enforcing_agency="National health authority",
        state_variance="Moderate",
        update_frequency="National registry frameworks evolving; IARC provides international guidance",
        authority_sources=({"domain": "ilo.org", "name": "ILO"},),
    ),

    # ── Oncology: oncology_clinical_trials ────────────────────────────────────
    RegulationDef(
        key="clinical_trial_coverage_mandates", category="oncology_clinical_trials",
        name="Clinical Trial Coverage Mandates",
        description="State laws requiring insurance coverage of routine patient costs in clinical trials",
        enforcing_agency="State legislatures",
        state_variance="High",
        update_frequency="State mandates enacted independently; federal parity efforts ongoing",
        authority_sources=({"domain": "cancer.gov", "name": "NCI"},),
    ),
    RegulationDef(
        key="right_to_try", category="oncology_clinical_trials",
        name="Right to Try Act",
        description="Federal and state laws allowing access to investigational drugs outside of clinical trials",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Federal Right to Try Act 2018; state laws predate federal; framework stable",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="protocol_deviation_reporting", category="oncology_clinical_trials",
        name="Protocol Deviation Reporting",
        description="Reporting and managing clinical trial protocol deviations and violations",
        enforcing_agency="FDA/IRB",
        state_variance="Low/None",
        update_frequency="FDA and ICH-GCP guidance updated periodically; IRB policies vary",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="adverse_event_reporting", category="oncology_clinical_trials",
        name="Adverse Event Reporting",
        description="Safety reporting requirements for serious and unexpected adverse events in oncology clinical trials",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="IND safety reporting requirements (21 CFR 312.32) stable; FDA guidance updated periodically",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="investigational_drug_access", category="oncology_clinical_trials",
        name="Investigational Drug Access",
        description="Expanded access and compassionate use programs for investigational drugs outside trials",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="FDA expanded access regulations (21 CFR 312.310) stable; guidance updated periodically",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),

    # ── Oncology: oncology_patient_rights ─────────────────────────────────────
    RegulationDef(
        key="patient_rights_declarations", category="oncology_patient_rights",
        name="Patient Rights Declarations",
        description="Oncology patient bill of rights including informed consent, second opinion, and treatment choice",
        enforcing_agency="State/TJC",
        state_variance="Moderate",
        update_frequency="Joint Commission patient rights standards updated annually; state laws vary",
        authority_sources=({"domain": "jointcommission.org", "name": "Joint Commission"},),
    ),
    RegulationDef(
        key="hospice_palliative_care", category="oncology_patient_rights",
        name="Hospice & Palliative Care",
        description="Hospice eligibility criteria, palliative care integration, and end-of-life care requirements",
        enforcing_agency="CMS/State",
        state_variance="Moderate",
        update_frequency="CMS hospice CoPs updated periodically; state palliative care laws expanding",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="fertility_preservation_counseling", category="oncology_patient_rights",
        name="Fertility Preservation Counseling",
        description="Requirements for pre-treatment fertility preservation discussion with cancer patients",
        enforcing_agency="ASCO/State",
        state_variance="Moderate",
        update_frequency="ASCO guidelines updated periodically; state mandates expanding",
        authority_sources=({"domain": "asco.org", "name": "ASCO"},),
    ),
    RegulationDef(
        key="cancer_treatment_consent", category="oncology_patient_rights",
        name="Cancer Treatment Consent",
        description="Informed consent requirements specific to oncology treatment including risks, alternatives, and prognosis",
        enforcing_agency="State/TJC",
        state_variance="Moderate",
        update_frequency="Joint Commission consent standards updated annually; state informed consent laws vary",
        authority_sources=({"domain": "jointcommission.org", "name": "Joint Commission"},),
    ),
    RegulationDef(
        key="palliative_care_access", category="oncology_patient_rights",
        name="Palliative Care Access (International)",
        description="National palliative care standards and access requirements for cancer patients",
        enforcing_agency="National health authority",
        state_variance="Moderate",
        update_frequency="National palliative care frameworks evolving; WHO guidance updated periodically",
        authority_sources=({"domain": "ilo.org", "name": "ILO"},),
    ),
]
