from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_MEDICAL_COMPLIANCE: List[RegulationDef] = [
    RegulationDef(
        key="oig_compliance_program_guidance",
        category="corporate_integrity",
        name="OIG Compliance Program Guidance",
        description="Seven elements of effective compliance: written standards, compliance officer, training, monitoring, enforcement, response, open lines",
        enforcing_agency="OIG",
        state_variance="Low/None",
        update_frequency="Original guidance 1998–2005; General Compliance Program Guidance updated 2023",
        authority_sources=({"domain": "oig.hhs.gov/compliance/compliance-guidance", "name": "oig.hhs.gov/compliance/compliance-guidance"},),
    ),
    RegulationDef(
        key="federal_sentencing_guidelines",
        category="corporate_integrity",
        name="Federal Sentencing Guidelines (§8B2.1)",
        description="Organizational sentencing factors; effective compliance program as mitigating factor; board oversight",
        enforcing_agency="U.S. Sentencing Commission",
        state_variance="Low/None",
        update_frequency="Updated annually (November amendments cycle)",
        authority_sources=({"domain": "ussc.gov/guidelines/organizational-guidelines", "name": "ussc.gov/guidelines/organizational-guidelines"},),
    ),
    RegulationDef(
        key="corporate_integrity_agreements",
        category="corporate_integrity",
        name="Corporate Integrity Agreements (CIAs)",
        description="Post-settlement compliance obligations; IRO reviews, board reporting, claims review",
        enforcing_agency="OIG",
        state_variance="Low/None",
        update_frequency="Each CIA is entity-specific; OIG publishes new CIAs as they are entered",
        authority_sources=({"domain": "oig.hhs.gov/fraud/cia", "name": "oig.hhs.gov/fraud/cia"},),
    ),
    RegulationDef(
        key="whistleblower_protections",
        category="corporate_integrity",
        name="Whistleblower Protections (FCA Qui Tam)",
        description="Protection from retaliation for reporting fraud; 15–30% reward; sealed filing",
        enforcing_agency="DOJ",
        state_variance="Moderate",
        update_frequency="Rarely amended; DOJ policy memos update enforcement priorities",
        authority_sources=({"domain": "justice.gov/civil/fraud/whistleblower", "name": "justice.gov/civil/fraud/whistleblower"},),
    ),
    RegulationDef(
        key="state_whistleblower_protection_laws",
        category="corporate_integrity",
        name="State Whistleblower Protection Laws",
        description="Many states have additional protections beyond federal FCA provisions",
        enforcing_agency="State AGs / Courts",
        state_variance="High",
        update_frequency="Updated via state legislation 1–3 yrs",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "taf.org", "name": "Taxpayers Against Fraud"},
        ),
    ),
    RegulationDef(
        key="deficit_reduction_act_of_2005",
        category="corporate_integrity",
        name="Deficit Reduction Act of 2005 (§6032)",
        description="Entities with $5M+ Medicaid must educate employees about FCA, whistleblower protections",
        enforcing_agency="CMS / State",
        state_variance="Moderate",
        update_frequency="Enacted 2005; rarely amended",
        authority_sources=({"domain": "oig.hhs.gov/compliance/101/files/DRA-Fact-Sheet.pdf", "name": "oig.hhs.gov/compliance/101/files/DRA-Fact-Sheet.pdf"},),
    ),
    RegulationDef(
        key="code_of_conduct_conflict_of_interest",
        category="corporate_integrity",
        name="Code of Conduct & Conflict of Interest",
        description="Expected by OIG, accreditors, payer contracts; board/physician financial disclosure",
        enforcing_agency="OIG / Accreditors",
        state_variance="Low/None",
        update_frequency="Internal policies updated annually; OIG expectations stable",
        authority_sources=({"domain": "oig.hhs.gov/compliance/compliance-guidance", "name": "oig.hhs.gov/compliance/compliance-guidance"},),
    ),
    RegulationDef(
        key="compliance_committee_board_oversight",
        category="corporate_integrity",
        name="Compliance Committee & Board Oversight",
        description="OIG expects board-level compliance oversight; quality/compliance committee reporting to board",
        enforcing_agency="OIG / Accreditors",
        state_variance="Low/None",
        update_frequency="OIG General CPG (2023) reinforced board oversight expectations",
        authority_sources=({"domain": "oig.hhs.gov/compliance/compliance-guidance", "name": "oig.hhs.gov/compliance/compliance-guidance"},),
    ),
    RegulationDef(
        key="internal_investigations_disclosure_protocols",
        category="corporate_integrity",
        name="Internal Investigations & Disclosure Protocols",
        description="Self-disclosure protocols (OIG SDP, CMS SRDP); internal investigation procedures; privilege considerations",
        enforcing_agency="OIG / CMS / DOJ",
        state_variance="Low/None",
        update_frequency="OIG SDP guidance updated every 2–3 yrs; CMS SRDP protocol updated periodically",
        authority_sources=(
            {"domain": "oig.hhs.gov/compliance/self-disclosure-info", "name": "oig.hhs.gov/compliance/self-disclosure-info"},
            {"domain": "cms.gov/medicare/coordination-of-benefits-and-recovery/debt-recovery", "name": "cms.gov/medicare/coordination-of-benefits-and-recovery/debt-recovery"},
        ),
    ),
    RegulationDef(
        key="21st_century_cures_act_information_blocking",
        category="health_it",
        name="21st Century Cures Act — Information Blocking (45 CFR Part 171)",
        description="Prohibition on practices interfering with access/exchange of EHI; eight exceptions; applies to providers, HINs, HIT developers",
        enforcing_agency="ONC / OIG",
        state_variance="Low/None",
        update_frequency="Initial rule 2021; OIG penalties finalized 2023; updates every 2–3 yrs",
        authority_sources=(
            {"domain": "healthit.gov/topic/information-blocking", "name": "healthit.gov/topic/information-blocking"},
            {"domain": "federalregister.gov", "name": "federalregister.gov"},
        ),
    ),
    RegulationDef(
        key="onc_health_it_certification",
        category="health_it",
        name="ONC Health IT Certification (45 CFR Part 170)",
        description="Certification requirements for EHR technology; USCDI data standards; API requirements",
        enforcing_agency="ONC",
        state_variance="Low/None",
        update_frequency="HTI-1 final rule 2024; USCDI updated annually",
        authority_sources=(
            {"domain": "healthit.gov/topic/certification-ehrs/certification-health-it", "name": "healthit.gov/topic/certification-ehrs/certification-health-it"},
            {"domain": "healthit.gov/isa/united-states-core-data-interoperability-uscdi", "name": "healthit.gov/isa/united-states-core-data-interoperability-uscdi"},
        ),
    ),
    RegulationDef(
        key="cms_interoperability_patient_access_rules",
        category="health_it",
        name="CMS Interoperability & Patient Access Rules",
        description="Patient access API, provider directory API, payer-to-payer exchange, prior auth API",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="CMS-9115-F (2020); CMS-0057-F (2024); updates every 2–3 yrs",
        authority_sources=({"domain": "cms.gov/priorities/key-initiatives/burden-reduction/interoperability", "name": "cms.gov/priorities/key-initiatives/burden-reduction/interoperability"},),
    ),
    RegulationDef(
        key="meaningful_use_promoting_interoperability",
        category="health_it",
        name="Meaningful Use / Promoting Interoperability",
        description="EHR incentive program; now part of MIPS; e-prescribing, HIE, patient portal access",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via MPFS/IPPS final rules",
        authority_sources=({"domain": "cms.gov/regulations-and-guidance/legislation/ehrincentiveprograms", "name": "cms.gov/regulations-and-guidance/legislation/ehrincentiveprograms"},),
    ),
    RegulationDef(
        key="hl7_fhir_uscdi_standards",
        category="health_it",
        name="HL7 FHIR & USCDI Standards",
        description="Technical standards for health data exchange; USCDI v1–v4 data classes; FHIR R4 API implementation",
        enforcing_agency="ONC / HL7",
        state_variance="Low/None",
        update_frequency="USCDI updated annually; FHIR versions every 2–3 yrs",
        authority_sources=(
            {"domain": "hl7.org/fhir", "name": "hl7.org/fhir"},
            {"domain": "healthit.gov/isa/united-states-core-data-interoperability-uscdi", "name": "healthit.gov/isa/united-states-core-data-interoperability-uscdi"},
        ),
    ),
    RegulationDef(
        key="eprescribing_for_controlled_substances",
        category="health_it",
        name="E-Prescribing for Controlled Substances (EPCS)",
        description="DEA requirements for e-prescribing Schedule II–V; identity proofing; two-factor authentication",
        enforcing_agency="DEA",
        state_variance="High",
        update_frequency="DEA interim final rule 2010; state mandates expanding rapidly",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov/ecomm/e_rx", "name": "deadiversion.usdoj.gov/ecomm/e_rx"},
            {"domain": "each state pharmacy board", "name": "each state pharmacy board"},
        ),
    ),
    RegulationDef(
        key="state_hie_requirements",
        category="health_it",
        name="State HIE Requirements",
        description="Some states mandate HIE connection; varying consent models (opt-in/opt-out); data submission requirements",
        enforcing_agency="State HIT offices",
        state_variance="High",
        update_frequency="Varies by state; updated with state legislation/regulation",
        authority_sources=(
            {"domain": "Each state HIT/HIE organization", "name": "Each state HIT/HIE organization"},
            {"domain": "healthit.gov/topic/health-it-health-care-settings/health-information-exchange", "name": "healthit.gov/topic/health-it-health-care-settings/health-information-exchange"},
        ),
    ),
    RegulationDef(
        key="electronic_signatures",
        category="health_it",
        name="Electronic Signatures (ESIGN / UETA)",
        description="Federal and state frameworks for electronic signature validity in healthcare",
        enforcing_agency="Federal / State",
        state_variance="Moderate",
        update_frequency="ESIGN (2000) rarely amended; state UETA adoptions vary",
        authority_sources=(
            {"domain": "ftc.gov/legal-library/browse/statutes/electronic-signatures-global-national-commerce-act", "name": "ftc.gov/legal-library/browse/statutes/electronic-signatures-global-national-commerce-act"},
            {"domain": "uniformlaws.org", "name": "uniformlaws.org"},
        ),
    ),
    RegulationDef(
        key="21_cfr_part_11",
        category="health_it",
        name="21 CFR Part 11 (Electronic Records in FDA-Regulated Activities)",
        description="FDA requirements for e-records and e-signatures in trials, device manufacturing, pharma operations",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Original 1997; FDA guidance documents updated periodically",
        authority_sources=({"domain": "fda.gov/regulatory-information/search-fda-guidance-documents/part-11-electronic-records-electronic-signatures", "name": "fda.gov/regulatory-information/search-fda-guidance-documents/part-11-electronic-records-electronic-signatures"},),
    ),
    RegulationDef(
        key="telehealth_technology_standards",
        category="health_it",
        name="Telehealth Technology Standards",
        description="Platform security, audio/video standards, interstate licensing (IMLC, NLC), prescribing via telehealth",
        enforcing_agency="CMS / State Boards / DEA",
        state_variance="High",
        update_frequency="Rapidly evolving post-COVID; state laws update each legislative session",
        authority_sources=(
            {"domain": "cchpca.org", "name": "Center for Connected Health Policy"},
            {"domain": "each state medical board", "name": "each state medical board"},
        ),
    ),
    RegulationDef(
        key="mips_qpp",
        category="quality_reporting",
        name="MIPS / QPP",
        description="Quality, cost, promoting interoperability, improvement activities; payment adjustments based on composite scores",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via MPFS final rule (November)",
        authority_sources=(
            {"domain": "qpp.cms.gov", "name": "qpp.cms.gov"},
            {"domain": "cms.gov/medicare/quality/physicians", "name": "cms.gov/medicare/quality/physicians"},
        ),
    ),
    RegulationDef(
        key="advanced_apms",
        category="quality_reporting",
        name="Advanced APMs",
        description="Shared savings/risk models (ACOs, bundled payments); QP thresholds",
        enforcing_agency="CMS / CMMI",
        state_variance="Low/None",
        update_frequency="Updated annually; CMMI model-specific updates ongoing",
        authority_sources=(
            {"domain": "qpp.cms.gov", "name": "qpp.cms.gov"},
            {"domain": "innovation.cms.gov", "name": "innovation.cms.gov"},
        ),
    ),
    RegulationDef(
        key="hospital_iqr_program",
        category="quality_reporting",
        name="Hospital IQR Program",
        description="Mandatory quality measure reporting for IPPS hospitals; pay reduction for non-reporting",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual measure updates via IPPS final rule (August)",
        authority_sources=({"domain": "cms.gov/medicare/quality/inpatient-quality-reporting", "name": "cms.gov/medicare/quality/inpatient-quality-reporting"},),
    ),
    RegulationDef(
        key="hospital_oqr_program",
        category="quality_reporting",
        name="Hospital OQR Program",
        description="Quality measures for OPPS hospitals",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via OPPS final rule (November)",
        authority_sources=({"domain": "cms.gov/medicare/quality/outpatient-quality-reporting", "name": "cms.gov/medicare/quality/outpatient-quality-reporting"},),
    ),
    RegulationDef(
        key="hospital_vbp_program",
        category="quality_reporting",
        name="Hospital VBP Program",
        description="Payment incentives based on outcomes, patient experience (HCAHPS), safety, efficiency",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual domain/measure updates via IPPS final rule",
        authority_sources=({"domain": "cms.gov/medicare/quality/value-based-programs/hospital-purchasing", "name": "cms.gov/medicare/quality/value-based-programs/hospital-purchasing"},),
    ),
    RegulationDef(
        key="hac_reduction_program",
        category="quality_reporting",
        name="HAC Reduction Program",
        description="Payment penalties for hospitals in worst quartile for hospital-acquired conditions",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual measure/methodology updates via IPPS final rule",
        authority_sources=({"domain": "cms.gov/medicare/quality/value-based-programs/hac-reduction-program", "name": "cms.gov/medicare/quality/value-based-programs/hac-reduction-program"},),
    ),
    RegulationDef(
        key="hospital_readmissions_reduction_program",
        category="quality_reporting",
        name="Hospital Readmissions Reduction Program",
        description="Payment penalties for excess readmissions for specified conditions",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via IPPS final rule",
        authority_sources=({"domain": "cms.gov/medicare/quality/value-based-programs/hospital-readmissions-reduction-program", "name": "cms.gov/medicare/quality/value-based-programs/hospital-readmissions-reduction-program"},),
    ),
    RegulationDef(
        key="snf_quality_reporting_program",
        category="quality_reporting",
        name="SNF Quality Reporting Program",
        description="Quality measures and staffing data for skilled nursing facilities",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via SNF PPS final rule",
        authority_sources=({"domain": "cms.gov/medicare/quality/nursing-home-improvement/quality-reporting-program", "name": "cms.gov/medicare/quality/nursing-home-improvement/quality-reporting-program"},),
    ),
    RegulationDef(
        key="home_health_quality_reporting",
        category="quality_reporting",
        name="Home Health Quality Reporting",
        description="OASIS data submission; quality measures for home health agencies",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via HH PPS final rule",
        authority_sources=({"domain": "cms.gov/medicare/quality/home-health-quality-reporting-program", "name": "cms.gov/medicare/quality/home-health-quality-reporting-program"},),
    ),
    RegulationDef(
        key="hedis_measures",
        category="quality_reporting",
        name="HEDIS Measures",
        description="Standardized quality measures used by health plans; payer contracts and Star Ratings",
        enforcing_agency="NCQA",
        state_variance="Low/None",
        update_frequency="Updated annually (HEDIS measurement year cycle)",
        authority_sources=({"domain": "ncqa.org/hedis", "name": "ncqa.org/hedis"},),
    ),
    RegulationDef(
        key="cms_star_ratings",
        category="quality_reporting",
        name="CMS Star Ratings",
        description="Public quality ratings for MA plans and hospitals",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Methodology updated annually; ratings published annually",
        authority_sources=({"domain": "cms.gov/medicare/quality/medicare-advantage-part-c-and-d-star-ratings-program", "name": "cms.gov/medicare/quality/medicare-advantage-part-c-and-d-star-ratings-program"},),
    ),
    RegulationDef(
        key="state_quality_reporting_mandates",
        category="quality_reporting",
        name="State Quality Reporting Mandates",
        description="Some states have additional quality reporting, public reporting, and P4P programs",
        enforcing_agency="State Health Depts",
        state_variance="High",
        update_frequency="Varies by state; updated via state legislation/regulation",
        authority_sources=(
            {"domain": "Each state health dept", "name": "Each state health dept"},
            {"domain": "nashp.org", "name": "National Academy for State Health Policy"},
        ),
    ),
    RegulationDef(
        key="hipaa_security_rule_cybersecurity",
        category="cybersecurity",
        name="HIPAA Security Rule (Technical Details)",
        description="Risk analysis, access management, audit controls, integrity, transmission security, encryption, contingency planning",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Major update proposed 2024 (NPRM); finalization expected 2025–2026",
        authority_sources=(
            {"domain": "hhs.gov/hipaa/for-professionals/security", "name": "hhs.gov/hipaa/for-professionals/security"},
            {"domain": "federalregister.gov", "name": "federalregister.gov"},
        ),
    ),
    RegulationDef(
        key="nist_cybersecurity_framework",
        category="cybersecurity",
        name="NIST Cybersecurity Framework (CSF 2.0)",
        description="Identify, Protect, Detect, Respond, Recover, Govern; increasingly expected by HHS",
        enforcing_agency="NIST / HHS",
        state_variance="Low/None",
        update_frequency="CSF 2.0 released Feb 2024; major revisions every 5–7 yrs",
        authority_sources=({"domain": "nist.gov/cyberframework", "name": "nist.gov/cyberframework"},),
    ),
    RegulationDef(
        key="hhs_healthcare_cybersecurity_performance_goals",
        category="cybersecurity",
        name="HHS Healthcare Cybersecurity Performance Goals (HPH CPGs)",
        description="Essential and enhanced goals: asset inventory, email security, MFA, vulnerability management, incident planning",
        enforcing_agency="HHS / CISA",
        state_variance="Low/None",
        update_frequency="Initial publication 2024; expected to update annually",
        authority_sources=({"domain": "hhs.gov/cybersecurity-performance-goals", "name": "hhs.gov/cybersecurity-performance-goals"},),
    ),
    RegulationDef(
        key="cisa_healthcare_guidance",
        category="cybersecurity",
        name="CISA Healthcare Guidance",
        description="Sector-specific guidance; KEV catalog; critical infrastructure designation",
        enforcing_agency="CISA",
        state_variance="Low/None",
        update_frequency="Continuous — advisories and alerts published as needed",
        authority_sources=(
            {"domain": "cisa.gov/healthcare", "name": "cisa.gov/healthcare"},
            {"domain": "cisa.gov/known-exploited-vulnerabilities-catalog", "name": "cisa.gov/known-exploited-vulnerabilities-catalog"},
        ),
    ),
    RegulationDef(
        key="circia",
        category="cybersecurity",
        name="CIRCIA (Cyber Incident Reporting)",
        description="Upcoming mandatory 72-hour reporting for critical infrastructure including healthcare",
        enforcing_agency="CISA",
        state_variance="Low/None",
        update_frequency="Final rule expected 2025–2026; NPRM published 2024",
        authority_sources=({"domain": "cisa.gov/circia", "name": "cisa.gov/circia"},),
    ),
    RegulationDef(
        key="state_data_breach_notification_laws",
        category="cybersecurity",
        name="State Data Breach Notification Laws",
        description="All 50 states have laws; varying definitions, timelines, AG notice requirements",
        enforcing_agency="State AGs",
        state_variance="High",
        update_frequency="Active legislative area — updates every 1–2 yrs per state",
        authority_sources=(
            {"domain": "ncsl.org/technology-and-telecommunication/security-breach-notification-laws", "name": "ncsl.org/technology-and-telecommunication/security-breach-notification-laws"},
            {"domain": "each state AG", "name": "each state AG"},
        ),
    ),
    RegulationDef(
        key="state_cybersecurity_requirements",
        category="cybersecurity",
        name="State Cybersecurity Requirements",
        description="NY SHIELD Act, CA CCPA technical safeguards, MA 201 CMR 17.00, etc.",
        enforcing_agency="State regulators",
        state_variance="High",
        update_frequency="Evolving rapidly; new state laws enacted annually",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ncsl.org/technology-and-telecommunication/cybersecurity-legislation", "name": "ncsl.org/technology-and-telecommunication/cybersecurity-legislation"},
        ),
    ),
    RegulationDef(
        key="medical_device_cybersecurity",
        category="cybersecurity",
        name="Medical Device Cybersecurity (Section 524B FD&C Act)",
        description="Pre-market cybersecurity for connected devices; SBOM requirements; post-market patching",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Enacted 2023; FDA guidance updated periodically",
        authority_sources=({"domain": "fda.gov/medical-devices/digital-health-center-excellence/cybersecurity", "name": "fda.gov/medical-devices/digital-health-center-excellence/cybersecurity"},),
    ),
    RegulationDef(
        key="ransomware_cyber_extortion_response",
        category="cybersecurity",
        name="Ransomware & Cyber Extortion Response",
        description="HIPAA obligations during ransomware; OCR enforcement for failure to prevent/respond",
        enforcing_agency="HHS OCR / FBI / CISA",
        state_variance="Low/None",
        update_frequency="HHS/CISA guidance updated as threat landscape evolves",
        authority_sources=(
            {"domain": "hhs.gov/hipaa/for-professionals/security/guidance/cybersecurity", "name": "hhs.gov/hipaa/for-professionals/security/guidance/cybersecurity"},
            {"domain": "ic3.gov", "name": "ic3.gov"},
        ),
    ),
    RegulationDef(
        key="nist_csf_implementation",
        category="cybersecurity",
        name="NIST Cybersecurity Framework Implementation",
        description="Voluntary framework for managing cybersecurity risk; widely adopted in healthcare",
        enforcing_agency="NIST (voluntary)",
        state_variance="Low/None",
        update_frequency="CSF 2.0 released Feb 2024",
        authority_sources=({"domain": "nist.gov/cyberframework", "name": "NIST CSF"},),
    ),
    RegulationDef(
        key="soc2_type2_compliance",
        category="cybersecurity",
        name="SOC 2 Type II Compliance",
        description="Trust service criteria for security, availability, processing integrity, confidentiality, privacy",
        enforcing_agency="AICPA / Auditors",
        state_variance="Low/None",
        update_frequency="Annually audited",
        authority_sources=({"domain": "aicpa.org", "name": "AICPA"},),
    ),
    RegulationDef(
        key="gdpr_health_data",
        category="cybersecurity",
        name="GDPR — Health Data Processing",
        description="EU General Data Protection Regulation requirements for processing health data (special category)",
        enforcing_agency="EU Data Protection Authorities",
        state_variance="Low/None",
        update_frequency="Active enforcement; guidance evolving",
        authority_sources=({"domain": "gdpr.eu", "name": "GDPR.eu"},),
    ),
    RegulationDef(
        key="fda_device_cybersecurity_guidance",
        category="cybersecurity",
        name="FDA Pre/Post-Market Cybersecurity Guidance (Devices)",
        description="FDA guidance on cybersecurity in pre-market submissions and post-market management for medical devices",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Guidance updated 2023",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="patch_act_medical_devices",
        category="cybersecurity",
        name="PATCH Act — Medical Device Cybersecurity",
        description="Consolidated Appropriations Act provisions requiring cybersecurity plans for new device submissions",
        enforcing_agency="FDA / Congress",
        state_variance="Low/None",
        update_frequency="Enacted 2022; FDA implementing",
        authority_sources=({"domain": "congress.gov", "name": "Congress.gov"},),
    ),
    RegulationDef(
        key="state_consumer_privacy_acts",
        category="cybersecurity",
        name="State Consumer Privacy Acts (CCPA, CPA, CTDPA, etc.)",
        description="State-level comprehensive privacy laws with health data provisions",
        enforcing_agency="State AGs",
        state_variance="High",
        update_frequency="New states enacting annually",
        authority_sources=({"domain": "iapp.org", "name": "IAPP"},),
    ),
    RegulationDef(
        key="incident_response_plan",
        category="cybersecurity",
        name="Cybersecurity Incident Response Plan Requirements",
        description="Requirements for documented incident response plans across federal and state frameworks",
        enforcing_agency="Multiple",
        state_variance="Moderate",
        update_frequency="Best practices evolving",
        authority_sources=({"domain": "cisa.gov", "name": "CISA"},),
    ),
    RegulationDef(
        key="third_party_risk_management",
        category="cybersecurity",
        name="Third-Party / Vendor Risk Management",
        description="Requirements for managing cybersecurity risk from vendors and business associates",
        enforcing_agency="Multiple",
        state_variance="Moderate",
        update_frequency="Growing regulatory emphasis",
        authority_sources=({"domain": "healthit.gov", "name": "ONC"},),
    ),
    RegulationDef(
        key="cms_life_safety_code",
        category="environmental_safety",
        name="CMS Life Safety Code (NFPA 101)",
        description="Fire safety for healthcare occupancies; egress, alarms, sprinklers, smoke compartments",
        enforcing_agency="CMS / State Fire Marshal",
        state_variance="Moderate",
        update_frequency="CMS adopts NFPA editions every 5–10 yrs; NFPA updates every 3 yrs",
        authority_sources=(
            {"domain": "nfpa.org/101", "name": "nfpa.org/101"},
            {"domain": "cms.gov/medicare/provider-enrollment-and-certification/fire-safety", "name": "cms.gov/medicare/provider-enrollment-and-certification/fire-safety"},
        ),
    ),
    RegulationDef(
        key="nfpa_99",
        category="environmental_safety",
        name="NFPA 99 (Health Care Facilities Code)",
        description="Medical gas systems, electrical systems, HVAC, emergency power",
        enforcing_agency="CMS / Joint Commission",
        state_variance="Low/None",
        update_frequency="NFPA 99 updated every 3 yrs",
        authority_sources=({"domain": "nfpa.org/99", "name": "nfpa.org/99"},),
    ),
    RegulationDef(
        key="ada_accessibility_standards",
        category="environmental_safety",
        name="ADA Accessibility Standards",
        description="Physical accessibility: parking, entrances, exam rooms, equipment",
        enforcing_agency="DOJ",
        state_variance="Moderate",
        update_frequency="2010 ADA Standards; DOJ guidance updated periodically",
        authority_sources=(
            {"domain": "ada.gov", "name": "ada.gov"},
            {"domain": "access-board.gov", "name": "access-board.gov"},
        ),
    ),
    RegulationDef(
        key="epa_medical_waste",
        category="environmental_safety",
        name="EPA Medical Waste (RCRA)",
        description="Hazardous waste ID, storage, transport, disposal; pharmaceutical waste rules",
        enforcing_agency="EPA / State environmental agencies",
        state_variance="High",
        update_frequency="Federal RCRA updates every 3–5 yrs; state regs vary widely",
        authority_sources=(
            {"domain": "epa.gov/rcra", "name": "epa.gov/rcra"},
            {"domain": "epa.gov/hwgenerators/management-pharmaceutical-hazardous-waste", "name": "epa.gov/hwgenerators/management-pharmaceutical-hazardous-waste"},
        ),
    ),
    RegulationDef(
        key="osha_hazardous_chemical_standards",
        category="environmental_safety",
        name="OSHA Hazardous Chemical Standards",
        description="Hazard Communication (GHS); formaldehyde; ethylene oxide; chemotherapy drugs",
        enforcing_agency="OSHA",
        state_variance="Moderate",
        update_frequency="Standards updated every 5–10 yrs; guidance documents more frequently",
        authority_sources=({"domain": "osha.gov/hazardous-chemicals", "name": "osha.gov/hazardous-chemicals"},),
    ),
    RegulationDef(
        key="osha_ionizing_radiation",
        category="environmental_safety",
        name="OSHA Ionizing Radiation (29 CFR 1910.1096)",
        description="Occupational exposure limits, monitoring, signage, restricted areas",
        enforcing_agency="OSHA / NRC / State",
        state_variance="Moderate",
        update_frequency="Federal standards rarely updated; state radiation programs update more frequently",
        authority_sources=(
            {"domain": "osha.gov/ionizing-radiation", "name": "osha.gov/ionizing-radiation"},
            {"domain": "nrc.gov", "name": "nrc.gov"},
        ),
    ),
    RegulationDef(
        key="state_radiation_control_programs",
        category="environmental_safety",
        name="State Radiation Control Programs",
        description="Licensing/inspection of radiation equipment; personnel monitoring; shielding",
        enforcing_agency="State Radiation Control",
        state_variance="High",
        update_frequency="Updated via state regulation every 1–3 yrs",
        authority_sources=(
            {"domain": "crcpd.org", "name": "Conference of Radiation Control Program Directors"},
            {"domain": "each state radiation control program", "name": "each state radiation control program"},
        ),
    ),
    RegulationDef(
        key="legionella_water_management",
        category="environmental_safety",
        name="Legionella / Water Management",
        description="CMS memo requiring water management programs; ASHRAE 188",
        enforcing_agency="CMS / State Health Depts",
        state_variance="Moderate",
        update_frequency="CMS memo 2017; ASHRAE 188 updated every 5 yrs",
        authority_sources=(
            {"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},
            {"domain": "ashrae.org", "name": "ashrae.org"},
        ),
    ),
    RegulationDef(
        key="sharps_needlestick_prevention",
        category="environmental_safety",
        name="Sharps & Needlestick Prevention",
        description="Engineering controls, exposure control plans, sharps injury logs",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="Needlestick Safety Act 2000; OSHA guidance updated periodically",
        authority_sources=({"domain": "osha.gov/bloodborne-pathogens/needlestick", "name": "osha.gov/bloodborne-pathogens/needlestick"},),
    ),
    RegulationDef(
        key="construction_renovation",
        category="environmental_safety",
        name="Construction & Renovation (ICRA/FGI)",
        description="Infection Control Risk Assessment; FGI Guidelines for hospital design/construction",
        enforcing_agency="Joint Commission / State",
        state_variance="Moderate",
        update_frequency="FGI Guidelines updated every 4–5 yrs (2022 edition current)",
        authority_sources=({"domain": "fgiguidelines.org", "name": "fgiguidelines.org"},),
    ),
    RegulationDef(
        key="cms_emergency_preparedness_rule",
        category="emergency_preparedness",
        name="CMS Emergency Preparedness Rule (42 CFR 482, 483, 484, 485, 486, 491)",
        description="Risk assessment, emergency plan, policies/procedures, communication plan, annual training/testing",
        enforcing_agency="CMS",
        state_variance="Moderate",
        update_frequency="Final rule 2016; Interpretive Guidelines updated periodically",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification/emergency-preparedness", "name": "cms.gov/medicare/provider-enrollment-and-certification/emergency-preparedness"},),
    ),
    RegulationDef(
        key="emtala_emergency_obligations",
        category="emergency_preparedness",
        name="EMTALA Emergency Obligations",
        description="Screening/stabilization during declared emergencies; surge capacity",
        enforcing_agency="CMS / OIG",
        state_variance="Low/None",
        update_frequency="Guidance updated after major events (e.g., COVID, hurricanes)",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},),
    ),
    RegulationDef(
        key="hospital_preparedness_program",
        category="emergency_preparedness",
        name="Hospital Preparedness Program (HPP)",
        description="ASPR cooperative agreement; healthcare coalition participation; surge benchmarks",
        enforcing_agency="ASPR / HHS",
        state_variance="Moderate",
        update_frequency="Funding guidance updated annually; capabilities updated every 2–3 yrs",
        authority_sources=({"domain": "phe.gov/preparedness/planning/hpp", "name": "phe.gov/preparedness/planning/hpp"},),
    ),
    RegulationDef(
        key="nims_hics",
        category="emergency_preparedness",
        name="NIMS / HICS",
        description="Standardized incident management; required for federal preparedness funding",
        enforcing_agency="FEMA / ASPR",
        state_variance="Low/None",
        update_frequency="NIMS updated every 5–10 yrs; HICS updated periodically",
        authority_sources=(
            {"domain": "fema.gov/nims", "name": "fema.gov/nims"},
            {"domain": "emsa.ca.gov/hospital-incident-command-system", "name": "emsa.ca.gov/hospital-incident-command-system"},
        ),
    ),
    RegulationDef(
        key="state_emergency_preparedness_requirements",
        category="emergency_preparedness",
        name="State Emergency Preparedness Requirements",
        description="State-specific hospital emergency plans, evacuation plans, mutual aid",
        enforcing_agency="State Health Depts / EM",
        state_variance="High",
        update_frequency="Updated via state regulation and post-event lessons learned",
        authority_sources=({"domain": "Each state health dept and emergency management agency", "name": "Each state health dept and emergency management agency"},),
    ),
    RegulationDef(
        key="pandemic_preparedness",
        category="emergency_preparedness",
        name="Pandemic Preparedness",
        description="Crisis Standards of Care; PPE stockpiling; ventilator allocation; vaccination distribution",
        enforcing_agency="HHS / CDC / State",
        state_variance="High",
        update_frequency="Active post-COVID rulemaking and guidance development",
        authority_sources=(
            {"domain": "cdc.gov/prepare-your-health", "name": "cdc.gov/prepare-your-health"},
            {"domain": "phe.gov/preparedness", "name": "phe.gov/preparedness"},
        ),
    ),
    RegulationDef(
        key="mass_casualty_active_shooter",
        category="emergency_preparedness",
        name="Mass Casualty / Active Shooter",
        description="Joint Commission requirements; active shooter training; behavioral threat assessment",
        enforcing_agency="Joint Commission / State",
        state_variance="Moderate",
        update_frequency="Joint Commission standards updated annually; DHS guidance periodic",
        authority_sources=(
            {"domain": "jointcommission.org", "name": "jointcommission.org"},
            {"domain": "cisa.gov/active-shooter-preparedness", "name": "cisa.gov/active-shooter-preparedness"},
        ),
    ),
    RegulationDef(
        key="common_rule",
        category="research_consent",
        name="Common Rule (45 CFR Part 46)",
        description="Federal policy for human subjects; IRB requirements; informed consent; vulnerable populations",
        enforcing_agency="OHRP / HHS",
        state_variance="Low/None",
        update_frequency="Revised 2018 (effective 2019); next update uncertain",
        authority_sources=({"domain": "hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46", "name": "hhs.gov/ohrp/regulations-and-policy/regulations/45-cfr-46"},),
    ),
    RegulationDef(
        key="fda_human_subject_regs",
        category="research_consent",
        name="FDA Human Subject Regs (21 CFR Parts 50, 56)",
        description="Additional protections for FDA-regulated research; IND/IDE requirements",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Updated every 3–5 yrs; FDA guidance documents more frequent",
        authority_sources=({"domain": "fda.gov/regulatory-information/search-fda-guidance-documents", "name": "fda.gov/regulatory-information/search-fda-guidance-documents"},),
    ),
    RegulationDef(
        key="good_clinical_practice",
        category="research_consent",
        name="Good Clinical Practice (ICH E6 R2/R3)",
        description="International standard for clinical trial design, conduct, recording, reporting",
        enforcing_agency="FDA / ICH",
        state_variance="Low/None",
        update_frequency="ICH E6 R3 in development (draft 2023); major revisions every 10 yrs",
        authority_sources=(
            {"domain": "ich.org/page/efficacy-guidelines", "name": "ich.org/page/efficacy-guidelines"},
            {"domain": "fda.gov/science-research/clinical-trials-and-human-subject-protection", "name": "fda.gov/science-research/clinical-trials-and-human-subject-protection"},
        ),
    ),
    RegulationDef(
        key="21_cfr_part_11_research_consent",
        category="research_consent",
        name="21 CFR Part 11 (E-Records & E-Signatures)",
        description="Electronic data capture, audit trails, e-signatures in FDA-regulated research",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Original 1997; FDA guidance documents updated periodically",
        authority_sources=({"domain": "fda.gov/regulatory-information/search-fda-guidance-documents/part-11-electronic-records-electronic-signatures", "name": "fda.gov/regulatory-information/search-fda-guidance-documents/part-11-electronic-records-electronic-signatures"},),
    ),
    RegulationDef(
        key="clinicaltrialsgov_registration",
        category="research_consent",
        name="ClinicalTrials.gov Registration (42 CFR Part 11)",
        description="Mandatory registration of applicable trials; results reporting within 12 months",
        enforcing_agency="NIH / FDA",
        state_variance="Low/None",
        update_frequency="Final rule 2016; ClinicalTrials.gov modernization ongoing",
        authority_sources=(
            {"domain": "clinicaltrials.gov", "name": "clinicaltrials.gov"},
            {"domain": "prsinfo.clinicaltrials.gov", "name": "prsinfo.clinicaltrials.gov"},
        ),
    ),
    RegulationDef(
        key="nih_grants_policy_compliance",
        category="research_consent",
        name="NIH Grants Policy & Compliance",
        description="FCOI (42 CFR Part 50 Subpart F); data sharing; RCR training; Public Access Policy",
        enforcing_agency="NIH",
        state_variance="Low/None",
        update_frequency="NIH Grants Policy Statement updated annually; data management plans required 2023+",
        authority_sources=(
            {"domain": "grants.nih.gov/policy", "name": "grants.nih.gov/policy"},
            {"domain": "sharing.nih.gov", "name": "sharing.nih.gov"},
        ),
    ),
    RegulationDef(
        key="hipaa_research_provisions",
        category="research_consent",
        name="HIPAA Research Provisions",
        description="Research use of PHI; authorization waivers; limited data sets; de-identification",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Updated with HIPAA Privacy Rule amendments",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/special-topics/research", "name": "hhs.gov/hipaa/for-professionals/special-topics/research"},),
    ),
    RegulationDef(
        key="state_research_consent_laws",
        category="research_consent",
        name="State Research & Consent Laws",
        description="Additional requirements for genetic research, minors, embryonic/fetal research",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Varies by state; updated via legislation",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ohrp.hhs.gov", "name": "ohrp.hhs.gov"},
        ),
    ),
    RegulationDef(
        key="institutional_biosafety_committee",
        category="research_consent",
        name="Institutional Biosafety Committee (IBC)",
        description="NIH Guidelines for recombinant DNA, synthetic nucleic acids, select agents; BSL classifications",
        enforcing_agency="NIH / CDC / USDA",
        state_variance="Low/None",
        update_frequency="NIH Guidelines updated every 2–3 yrs",
        authority_sources=(
            {"domain": "osp.od.nih.gov/biotechnology/nih-guidelines", "name": "osp.od.nih.gov/biotechnology/nih-guidelines"},
            {"domain": "selectagents.gov", "name": "selectagents.gov"},
        ),
    ),
    RegulationDef(
        key="dea_registration_controlled_substances",
        category="pharmacy_drugs",
        name="DEA Registration & Controlled Substances (21 CFR 1301–1321)",
        description="Registration; Schedule I–V; prescribing, dispensing, administering, disposing",
        enforcing_agency="DEA",
        state_variance="Moderate",
        update_frequency="Scheduling actions ongoing; registration renewed every 3 yrs",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
            {"domain": "ecfr.gov/current/title-21/chapter-II", "name": "ecfr.gov/current/title-21/chapter-II"},
        ),
    ),
    RegulationDef(
        key="prescription_drug_monitoring_programs",
        category="pharmacy_drugs",
        name="Prescription Drug Monitoring Programs (PDMPs)",
        description="State databases tracking controlled substance prescriptions; mandatory checking requirements vary",
        enforcing_agency="State Pharmacy Boards / BJA",
        state_variance="High",
        update_frequency="State PDMP laws updated every 1–2 yrs; all states operational",
        authority_sources=(
            {"domain": "pdmpassist.org", "name": "pdmpassist.org"},
            {"domain": "namsdl.org", "name": "namsdl.org"},
            {"domain": "each state PDMP", "name": "each state PDMP"},
        ),
    ),
    RegulationDef(
        key="drug_supply_chain_security_act",
        category="pharmacy_drugs",
        name="Drug Supply Chain Security Act (DSCSA)",
        description="Product tracing; transaction info; verification; serialization; interoperable electronic system",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Phased implementation 2013–2023+; enforcement discretion extensions ongoing",
        authority_sources=({"domain": "fda.gov/drugs/drug-supply-chain-integrity/drug-supply-chain-security-act-dscsa", "name": "fda.gov/drugs/drug-supply-chain-integrity/drug-supply-chain-security-act-dscsa"},),
    ),
    RegulationDef(
        key="340b_drug_pricing_program",
        category="pharmacy_drugs",
        name="340B Drug Pricing Program (42 U.S.C. § 256b)",
        description="Discounted outpatient drug pricing for covered entities; contract pharmacy; HRSA audits",
        enforcing_agency="HRSA",
        state_variance="Moderate",
        update_frequency="HRSA guidance updated 1–2 yrs; active litigation reshaping program",
        authority_sources=(
            {"domain": "hrsa.gov/opa", "name": "hrsa.gov/opa"},
            {"domain": "340bopais.hrsa.gov", "name": "340bopais.hrsa.gov"},
        ),
    ),
    RegulationDef(
        key="usp_compounding_standards",
        category="pharmacy_drugs",
        name="USP Compounding Standards (<795>, <797>, <800>)",
        description="Non-sterile compounding, sterile compounding, hazardous drug handling",
        enforcing_agency="State Pharmacy Boards / CMS",
        state_variance="Moderate",
        update_frequency="USP <797> revised 2023 (enforcement delayed); chapters updated every 5–10 yrs",
        authority_sources=(
            {"domain": "usp.org/compounding", "name": "usp.org/compounding"},
            {"domain": "each state pharmacy board", "name": "each state pharmacy board"},
        ),
    ),
    RegulationDef(
        key="state_pharmacy_practice_acts",
        category="pharmacy_drugs",
        name="State Pharmacy Practice Acts",
        description="Scope of practice; technician ratios; collaborative practice; dispensing requirements",
        enforcing_agency="State Pharmacy Boards",
        state_variance="High",
        update_frequency="Updated every legislative session",
        authority_sources=(
            {"domain": "Each state pharmacy board", "name": "Each state pharmacy board"},
            {"domain": "nabp.pharmacy", "name": "nabp.pharmacy"},
        ),
    ),
    RegulationDef(
        key="fda_rems_programs",
        category="pharmacy_drugs",
        name="FDA REMS Programs",
        description="Risk Evaluation and Mitigation Strategies for high-risk drugs; iPLEDGE, TIRF, opioid REMS",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Individual REMS modified as needed; new REMS established ongoing",
        authority_sources=(
            {"domain": "fda.gov/drugs/drug-safety-and-availability/rems", "name": "fda.gov/drugs/drug-safety-and-availability/rems"},
            {"domain": "accessdata.fda.gov/scripts/cder/rems", "name": "accessdata.fda.gov/scripts/cder/rems"},
        ),
    ),
    RegulationDef(
        key="medication_error_reporting",
        category="pharmacy_drugs",
        name="Medication Error Reporting",
        description="FDA MedWatch; ISMP reporting; state-mandated error reporting; RCA requirements",
        enforcing_agency="FDA / State",
        state_variance="Moderate",
        update_frequency="MedWatch continuous; state reporting mandates update every 2–3 yrs",
        authority_sources=(
            {"domain": "fda.gov/safety/medwatch", "name": "fda.gov/safety/medwatch"},
            {"domain": "ismp.org", "name": "ismp.org"},
        ),
    ),
    RegulationDef(
        key="pharmaceutical_waste_disposal",
        category="pharmacy_drugs",
        name="Pharmaceutical Waste Disposal",
        description="RCRA hazardous waste rules for pharmaceuticals; DEA reverse distribution for controlled substances",
        enforcing_agency="EPA / DEA / State",
        state_variance="High",
        update_frequency="EPA Management Standards for Hazardous Waste Pharmaceuticals (2019); state rules vary",
        authority_sources=(
            {"domain": "epa.gov/hwgenerators/management-pharmaceutical-hazardous-waste", "name": "epa.gov/hwgenerators/management-pharmaceutical-hazardous-waste"},
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
        ),
    ),
    RegulationDef(
        key="drug_diversion_prevention",
        category="pharmacy_drugs",
        name="Drug Diversion Prevention",
        description="Monitoring and preventing controlled substance diversion; ADC audits; random testing",
        enforcing_agency="DEA / State / Joint Commission",
        state_variance="Moderate",
        update_frequency="Best practice guidance updated every 2–3 yrs; DEA enforcement continuous",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
            {"domain": "jointcommission.org", "name": "jointcommission.org"},
        ),
    ),
    RegulationDef(
        key="medicare_advantage_compliance",
        category="payer_relations",
        name="Medicare Advantage Compliance (42 CFR Part 422)",
        description="Network adequacy; compliance programs; marketing rules; grievances/appeals; RADV audits",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via MA Rate Announcement and Call Letter (April); final rule (fall)",
        authority_sources=({"domain": "cms.gov/medicare/health-plans/medicareadvtgspecratestats", "name": "cms.gov/medicare/health-plans/medicareadvtgspecratestats"},),
    ),
    RegulationDef(
        key="medicaid_managed_care",
        category="payer_relations",
        name="Medicaid Managed Care (42 CFR Part 438)",
        description="State plan requirements; MCO obligations; network adequacy; access standards; quality",
        enforcing_agency="CMS / State Medicaid",
        state_variance="High",
        update_frequency="Federal rule updated every 3–5 yrs; state contracts renegotiated every 1–5 yrs",
        authority_sources=(
            {"domain": "medicaid.gov/medicaid/managed-care", "name": "medicaid.gov/medicaid/managed-care"},
            {"domain": "each state Medicaid agency", "name": "each state Medicaid agency"},
        ),
    ),
    RegulationDef(
        key="aca_insurance_market_reforms",
        category="payer_relations",
        name="ACA Insurance Market Reforms",
        description="EHBs; preventive services; pre-existing conditions; premium rating rules",
        enforcing_agency="CMS / State DOIs",
        state_variance="Moderate",
        update_frequency="Annual Notice of Benefit and Payment Parameters; state benchmark plans updated periodically",
        authority_sources=(
            {"domain": "cms.gov/cciio", "name": "cms.gov/cciio"},
            {"domain": "healthcare.gov", "name": "healthcare.gov"},
        ),
    ),
    RegulationDef(
        key="erisa",
        category="payer_relations",
        name="ERISA",
        description="Governs employer-sponsored health plans; preemption; fiduciary duties; claims procedures",
        enforcing_agency="DOL",
        state_variance="Moderate",
        update_frequency="DOL guidance updated every 2–3 yrs; ERISA statute rarely amended",
        authority_sources=({"domain": "dol.gov/agencies/ebsa/laws-and-regulations/laws/erisa", "name": "dol.gov/agencies/ebsa/laws-and-regulations/laws/erisa"},),
    ),
    RegulationDef(
        key="network_adequacy_standards",
        category="payer_relations",
        name="Network Adequacy Standards",
        description="State and federal requirements for adequate networks; time/distance; wait times",
        enforcing_agency="CMS / State DOIs",
        state_variance="High",
        update_frequency="CMS updates via MA/Medicaid managed care rules; states update annually",
        authority_sources=(
            {"domain": "cms.gov", "name": "cms.gov"},
            {"domain": "each state DOI", "name": "each state DOI"},
            {"domain": "naic.org", "name": "naic.org"},
        ),
    ),
    RegulationDef(
        key="prior_authorization_requirements",
        category="payer_relations",
        name="Prior Authorization Requirements",
        description="CMS interop rule requirements; state reform laws; turnaround times; gold carding",
        enforcing_agency="CMS / State DOIs",
        state_variance="High",
        update_frequency="CMS-0057-F (2024); state prior auth reform laws expanding rapidly",
        authority_sources=(
            {"domain": "cms.gov/priorities/key-initiatives/burden-reduction", "name": "cms.gov/priorities/key-initiatives/burden-reduction"},
            {"domain": "each state legislature", "name": "each state legislature"},
            {"domain": "ama-assn.org/prior-authorization", "name": "ama-assn.org/prior-authorization"},
        ),
    ),
    RegulationDef(
        key="cvo_standards",
        category="payer_relations",
        name="CVO Standards",
        description="NCQA CVO certification; delegated credentialing; payer-specific timelines",
        enforcing_agency="NCQA / Payers",
        state_variance="Low/None",
        update_frequency="NCQA standards updated annually",
        authority_sources=({"domain": "ncqa.org/programs/health-plans/credentials-verification-organization", "name": "ncqa.org/programs/health-plans/credentials-verification-organization"},),
    ),
    RegulationDef(
        key="state_insurance_regulation",
        category="payer_relations",
        name="State Insurance Regulation",
        description="State mandates beyond ACA; prompt pay; claims processing; provider contract requirements",
        enforcing_agency="State DOIs",
        state_variance="High",
        update_frequency="Updated every legislative session",
        authority_sources=(
            {"domain": "Each state DOI", "name": "Each state DOI"},
            {"domain": "naic.org", "name": "naic.org"},
        ),
    ),
    RegulationDef(
        key="mental_health_parity",
        category="payer_relations",
        name="Mental Health Parity (MHPAEA)",
        description="Parity between MH/SUD and medical/surgical benefits; NQTL analysis requirements",
        enforcing_agency="DOL / HHS / Treasury",
        state_variance="Moderate",
        update_frequency="2024 final rule on NQTL comparative analysis; enforcement intensifying",
        authority_sources=(
            {"domain": "dol.gov/agencies/ebsa/laws-and-regulations/laws/mental-health-and-substance-use-disorder-parity", "name": "dol.gov/agencies/ebsa/laws-and-regulations/laws/mental-health-and-substance-use-disorder-parity"},
            {"domain": "cms.gov/cciio/programs-and-initiatives/other-insurance-protections/mhpaea", "name": "cms.gov/cciio/programs-and-initiatives/other-insurance-protections/mhpaea"},
        ),
    ),
    RegulationDef(
        key="postdobbs_state_abortion_laws",
        category="reproductive_behavioral",
        name="Post-Dobbs State Abortion Laws",
        description="Wide variation: total bans to codified protections; gestational limits; exceptions; provider liability; travel restrictions",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Extremely active — multiple states pass/amend laws each session; ballot initiatives ongoing",
        authority_sources=(
            {"domain": "guttmacher.org/state-policy", "name": "guttmacher.org/state-policy"},
            {"domain": "each state legislature", "name": "each state legislature"},
            {"domain": "reproductiverights.org", "name": "reproductiverights.org"},
        ),
    ),
    RegulationDef(
        key="title_x_family_planning",
        category="reproductive_behavioral",
        name="Title X Family Planning",
        description="Federal funding for family planning; grantee compliance; patient confidentiality",
        enforcing_agency="HHS / OASH",
        state_variance="Moderate",
        update_frequency="Title X regulations updated every 2–4 yrs (administration-dependent)",
        authority_sources=({"domain": "hhs.gov/opa/title-x-family-planning", "name": "hhs.gov/opa/title-x-family-planning"},),
    ),
    RegulationDef(
        key="state_reproductive_health_privacy_laws",
        category="reproductive_behavioral",
        name="State Reproductive Health Privacy Laws",
        description="Privacy protections for reproductive health data; law enforcement access restrictions",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Rapidly expanding post-Dobbs (2022–present)",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ncsl.org/health/reproductive-health", "name": "ncsl.org/health/reproductive-health"},
        ),
    ),
    RegulationDef(
        key="42_cfr_part_2_reproductive_behavioral",
        category="reproductive_behavioral",
        name="42 CFR Part 2 (SUD Records — Detailed)",
        description="Consent, court orders, research disclosures, audit/evaluation; 2024 alignment with HIPAA for TPO",
        enforcing_agency="SAMHSA",
        state_variance="Moderate",
        update_frequency="Major 2024 final rule; next update TBD",
        authority_sources=({"domain": "samhsa.gov/about-us/who-we-are/laws-regulations/confidentiality-regulations-faqs", "name": "samhsa.gov/about-us/who-we-are/laws-regulations/confidentiality-regulations-faqs"},),
    ),
    RegulationDef(
        key="state_mental_health_commitment_laws",
        category="reproductive_behavioral",
        name="State Mental Health Commitment Laws",
        description="Involuntary holds (5150 in CA, Baker Act in FL); criteria, duration, patient rights, judicial review",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Updated via state legislation every 1–3 yrs",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "treatmentadvocacycenter.org/state-laws", "name": "treatmentadvocacycenter.org/state-laws"},
        ),
    ),
    RegulationDef(
        key="state_sud_treatment_regulations",
        category="reproductive_behavioral",
        name="State SUD Treatment Regulations",
        description="Licensure of SUD facilities; MAT requirements; counselor credentialing",
        enforcing_agency="State agencies",
        state_variance="High",
        update_frequency="Updated via state regulation",
        authority_sources=(
            {"domain": "Each state substance abuse agency", "name": "Each state substance abuse agency"},
            {"domain": "samhsa.gov", "name": "samhsa.gov"},
        ),
    ),
    RegulationDef(
        key="confidentiality_of_minor_health_records",
        category="reproductive_behavioral",
        name="Confidentiality of Minor Health Records",
        description="Minor consent for STI treatment, contraception, mental health, substance use; parental notification",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Updated via state legislation annually",
        authority_sources=(
            {"domain": "guttmacher.org/state-policy/explore/overview-minors-consent-law", "name": "guttmacher.org/state-policy/explore/overview-minors-consent-law"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="hivaids_testing_disclosure_laws",
        category="reproductive_behavioral",
        name="HIV/AIDS Testing & Disclosure Laws",
        description="Consent for testing; disclosure restrictions; partner notification; criminalization provisions",
        enforcing_agency="State law / CDC",
        state_variance="High",
        update_frequency="State laws updated every 1–3 yrs; CDC guidelines updated periodically",
        authority_sources=(
            {"domain": "cdc.gov/hiv", "name": "cdc.gov/hiv"},
            {"domain": "each state legislature", "name": "each state legislature"},
            {"domain": "hivlawandpolicy.org", "name": "hivlawandpolicy.org"},
        ),
    ),
    RegulationDef(
        key="transgender_healthcare_regulations",
        category="reproductive_behavioral",
        name="Transgender Healthcare Regulations",
        description="Gender-affirming care restrictions/protections; minor restrictions; insurance mandates/exclusions; conscience protections",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Extremely active legislative area (2023–2026); federal rules shifting",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "hrc.org/resources", "name": "hrc.org/resources"},
            {"domain": "lgbtmap.org/equality-maps", "name": "lgbtmap.org/equality-maps"},
        ),
    ),
    RegulationDef(
        key="conscience_religious_exemption_laws",
        category="reproductive_behavioral",
        name="Conscience & Religious Exemption Laws",
        description="Church/Coats-Snowe/Weldon Amendments (federal); state conscience protections",
        enforcing_agency="HHS OCR / State",
        state_variance="High",
        update_frequency="Federal rules shift with administrations; state laws update periodically",
        authority_sources=(
            {"domain": "hhs.gov/conscience", "name": "hhs.gov/conscience"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="child_abuse_neglect_reporting",
        category="pediatric_vulnerable",
        name="Child Abuse & Neglect Reporting (CAPTA)",
        description="Federal framework; all states mandate reporting; covered reporters; procedures vary",
        enforcing_agency="HHS ACF / State CPS",
        state_variance="High",
        update_frequency="Federal CAPTA reauthorized every 5–7 yrs; state laws update annually",
        authority_sources=(
            {"domain": "childwelfare.gov", "name": "childwelfare.gov"},
            {"domain": "acf.hhs.gov/cb", "name": "acf.hhs.gov/cb"},
            {"domain": "each state CPS", "name": "each state CPS"},
        ),
    ),
    RegulationDef(
        key="elder_abuse_prevention",
        category="pediatric_vulnerable",
        name="Elder Abuse Prevention (Elder Justice Act)",
        description="Mandatory reporting in LTC facilities; 2-hour reporting for serious bodily injury",
        enforcing_agency="HHS ACL / State APS",
        state_variance="High",
        update_frequency="Elder Justice Act 2010; state laws update every 1–3 yrs",
        authority_sources=(
            {"domain": "acl.gov/programs/elder-justice", "name": "acl.gov/programs/elder-justice"},
            {"domain": "ncea.acl.gov", "name": "ncea.acl.gov"},
            {"domain": "each state APS", "name": "each state APS"},
        ),
    ),
    RegulationDef(
        key="adult_protective_services_reporting",
        category="pediatric_vulnerable",
        name="Adult Protective Services Reporting",
        description="Mandatory reporting of abuse/neglect/exploitation of vulnerable adults; varies by state",
        enforcing_agency="State APS",
        state_variance="High",
        update_frequency="State laws update every 1–3 yrs",
        authority_sources=(
            {"domain": "napsa-now.org", "name": "napsa-now.org"},
            {"domain": "each state APS", "name": "each state APS"},
        ),
    ),
    RegulationDef(
        key="nursing_home_reform_act",
        category="pediatric_vulnerable",
        name="Nursing Home Reform Act (OBRA 1987)",
        description="Resident rights, care planning, staffing, quality of life for certified nursing facilities",
        enforcing_agency="CMS",
        state_variance="Moderate",
        update_frequency="CMS CoPs updated every 3–5 yrs; Interpretive Guidelines updated more frequently",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification/guidanceforlawsandregulations", "name": "cms.gov/medicare/provider-enrollment-and-certification/guidanceforlawsandregulations"},),
    ),
    RegulationDef(
        key="cms_nursing_home_minimum_staffing_rule",
        category="pediatric_vulnerable",
        name="CMS Nursing Home Minimum Staffing Rule (2024)",
        description="Minimum staffing standards; RN 24/7; HPRD minimums; phased implementation",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Final rule 2024; phased implementation through 2027",
        authority_sources=({"domain": "cms.gov/newsroom/fact-sheets/medicare-and-medicaid-programs-minimum-staffing-standards", "name": "cms.gov/newsroom/fact-sheets/medicare-and-medicaid-programs-minimum-staffing-standards"},),
    ),
    RegulationDef(
        key="guardianship_surrogate_decisionmaking",
        category="pediatric_vulnerable",
        name="Guardianship & Surrogate Decision-Making",
        description="Guardianship, conservatorship, healthcare POA, surrogate hierarchies",
        enforcing_agency="State courts / law",
        state_variance="High",
        update_frequency="State laws update every 2–5 yrs; Uniform Guardianship Act adoption varies",
        authority_sources=(
            {"domain": "uniformlaws.org", "name": "uniformlaws.org"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="disability_rights",
        category="pediatric_vulnerable",
        name="Disability Rights (Section 504 / ADA)",
        description="Non-discrimination in treatment; effective communication; service animals",
        enforcing_agency="HHS OCR / DOJ",
        state_variance="Moderate",
        update_frequency="DOJ/HHS guidance updated every 2–3 yrs",
        authority_sources=(
            {"domain": "hhs.gov/civil-rights/for-individuals/disability", "name": "hhs.gov/civil-rights/for-individuals/disability"},
            {"domain": "ada.gov", "name": "ada.gov"},
        ),
    ),
    RegulationDef(
        key="immigrant_undocumented_patient_protections",
        category="pediatric_vulnerable",
        name="Immigrant & Undocumented Patient Protections",
        description="Emergency Medicaid; EMTALA regardless of status; state coverage programs; language access",
        enforcing_agency="CMS / State",
        state_variance="High",
        update_frequency="State immigrant health programs expanding; federal policy shifts with administrations",
        authority_sources=(
            {"domain": "medicaid.gov", "name": "medicaid.gov"},
            {"domain": "each state Medicaid agency", "name": "each state Medicaid agency"},
            {"domain": "nilc.org", "name": "National Immigration Law Center"},
        ),
    ),
]
