from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_EXPANSION: List[RegulationDef] = [

    # ── Expansion: fda_lifecycle ──────────────────────────────────────────────
    RegulationDef(
        key="nda_bla_submission", category="fda_lifecycle",
        name="NDA/BLA Submission Requirements",
        description="FDA new drug application (NDA) and biologics license application (BLA) process and requirements",
        enforcing_agency="FDA/CDER/CBER",
        state_variance="Low/None",
        update_frequency="Guidance documents updated periodically; statutory framework stable",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="anda_generic_pathway", category="fda_lifecycle",
        name="ANDA Generic Drug Pathway (Hatch-Waxman)",
        description="Abbreviated new drug applications for generic drugs under the Hatch-Waxman Act",
        enforcing_agency="FDA/CDER",
        state_variance="Low/None",
        update_frequency="ANDA guidance updated periodically; Hatch-Waxman framework stable since 1984",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="fda_breakthrough_accelerated", category="fda_lifecycle",
        name="Breakthrough/Fast Track/Accelerated Approval",
        description="Expedited FDA approval pathways for drugs treating serious conditions with unmet need",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Guidance updated as new pathways are created or modified by legislation",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="fda_priority_review", category="fda_lifecycle",
        name="Priority Review & Voucher Programs",
        description="Six-month FDA review timeline for drugs representing significant therapeutic advances",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Voucher programs periodically reauthorized by Congress",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="post_market_surveillance_faers", category="fda_lifecycle",
        name="Post-Market Surveillance (FAERS/MedWatch)",
        description="FDA adverse event reporting system for post-market drug and biologic safety monitoring",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Reporting requirements and system updates issued periodically",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="pharmacovigilance_safety_reporting", category="fda_lifecycle",
        name="Pharmacovigilance & Safety Reporting",
        description="Individual case safety reports (ICSRs), periodic safety update reports (PSURs), and signal detection",
        enforcing_agency="FDA/EMA",
        state_variance="Low/None",
        update_frequency="ICH E2 guidelines updated periodically; FDA/EMA harmonization ongoing",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="rems_lifecycle", category="fda_lifecycle",
        name="REMS (Risk Evaluation & Mitigation Strategies)",
        description="FDA-required risk management programs for drugs with serious safety concerns",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Individual REMS programs updated based on safety data; FDA guidance updated periodically",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="fda_483_observations", category="fda_lifecycle",
        name="FDA 483 Observations & CAPA Management",
        description="FDA inspection findings (Form 483) and corrective/preventive action requirements",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Inspection procedures updated periodically; CAPA expectations evolve with guidance",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="product_labeling_pi_medication_guide", category="fda_lifecycle",
        name="Product Labeling (PI, Medication Guides, Black Box)",
        description="FDA prescribing information, medication guide, and boxed warning requirements for drugs",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Labeling guidance updated periodically; PLR format requirements evolving",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="pediatric_study_requirements", category="fda_lifecycle",
        name="Pediatric Study Requirements (PREA/BPCA)",
        description="Mandatory pediatric drug and biologic study requirements under PREA and BPCA",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Reauthorized periodically; most recently under FDORA 2022",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="orphan_drug_exclusivity", category="fda_lifecycle",
        name="Orphan Drug Designation & Exclusivity",
        description="Seven-year market exclusivity and incentives for drugs treating rare diseases",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Orphan Drug Act framework stable; FDA modernization rules updated periodically",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="patent_exclusivity_orange_book", category="fda_lifecycle",
        name="Patent/Exclusivity Listings (Orange Book/Purple Book)",
        description="FDA drug patent and exclusivity tracking via the Orange Book (drugs) and Purple Book (biologics)",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Orange Book updated monthly; Purple Book updated as biosimilar approvals occur",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),

    # ── Expansion: reimbursement_vbc ──────────────────────────────────────────
    RegulationDef(
        key="macra_mips_reporting", category="reimbursement_vbc",
        name="MACRA/MIPS Quality Reporting",
        description="Merit-based Incentive Payment System quality measures and reporting under MACRA",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="MIPS measures and weights updated annually via CMS final rule",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="apm_participation", category="reimbursement_vbc",
        name="Alternative Payment Model (APM) Participation",
        description="Advanced APM qualifying requirements and participation thresholds under MACRA",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="APM qualifying thresholds updated annually; new models introduced periodically",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="bundled_payment_compliance", category="reimbursement_vbc",
        name="Bundled Payment Program Compliance (BPCI-A)",
        description="Bundled Payments for Care Improvement Advanced model compliance requirements",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Model parameters updated per performance year; CMS Innovation Center oversight",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="cms_star_ratings", category="reimbursement_vbc",
        name="CMS Star Ratings Compliance",
        description="Medicare Advantage and Part D quality star rating measures and compliance requirements",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Star rating methodology and measures updated annually",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="hedis_quality_measures", category="reimbursement_vbc",
        name="HEDIS Quality Measures",
        description="Healthcare Effectiveness Data and Information Set measures for managed care quality",
        enforcing_agency="NCQA",
        state_variance="Low/None",
        update_frequency="HEDIS measures updated annually by NCQA",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="value_based_contract_requirements", category="reimbursement_vbc",
        name="Value-Based Contract Requirements",
        description="Value-based purchasing arrangements and risk-sharing agreement compliance requirements",
        enforcing_agency="CMS/Payers",
        state_variance="Moderate",
        update_frequency="CMS VBP programs updated annually; state Medicaid VBC rules vary",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="drg_coding_compliance", category="reimbursement_vbc",
        name="DRG/CPT Coding Compliance & Auditing",
        description="Diagnosis-related group and CPT coding accuracy requirements and audit standards",
        enforcing_agency="CMS/OIG",
        state_variance="Low/None",
        update_frequency="ICD/CPT code sets updated annually; OIG audit priorities updated yearly",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="price_transparency_rule", category="reimbursement_vbc",
        name="Hospital Price Transparency Rule",
        description="CMS requirement for hospitals to publish machine-readable pricing files and shoppable services",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Final rule effective 2021; enforcement and penalties strengthened 2022-2024",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),
    RegulationDef(
        key="good_faith_estimates", category="reimbursement_vbc",
        name="Good Faith Estimates",
        description="Cost estimate requirements for uninsured and self-pay patients under the No Surprises Act",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Rulemaking ongoing; CMS guidance updated as implementation progresses",
        authority_sources=({"domain": "cms.gov", "name": "CMS"},),
    ),

    # ── Expansion: quality_systems ────────────────────────────────────────────
    RegulationDef(
        key="iso_13485_medical_devices", category="quality_systems",
        name="ISO 13485 Medical Device QMS",
        description="Quality management system standard for medical device design and manufacture",
        enforcing_agency="Notified Bodies/Registrars",
        state_variance="Low/None",
        update_frequency="ISO 13485:2016 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="iso_9001_general_qms", category="quality_systems",
        name="ISO 9001 General Quality Management System",
        description="Process-based quality management system standard applicable to any organization",
        enforcing_agency="Registrars",
        state_variance="Low/None",
        update_frequency="ISO 9001:2015 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="iso_15189_clinical_labs", category="quality_systems",
        name="ISO 15189 Clinical Laboratory QMS",
        description="Quality and competence requirements for medical laboratories",
        enforcing_agency="Accreditation Bodies",
        state_variance="Low/None",
        update_frequency="ISO 15189:2022 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="iso_14001_environmental", category="quality_systems",
        name="ISO 14001 Environmental Management System",
        description="Environmental impact management framework for organizations of any type",
        enforcing_agency="Registrars",
        state_variance="Low/None",
        update_frequency="ISO 14001:2015 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="iso_45001_ohs", category="quality_systems",
        name="ISO 45001 Occupational Health & Safety",
        description="Occupational health and safety management system standard",
        enforcing_agency="Registrars",
        state_variance="Low/None",
        update_frequency="ISO 45001:2018 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="iso_27001_information_security", category="quality_systems",
        name="ISO 27001 Information Security Management",
        description="Information security management system (ISMS) framework for protecting information assets",
        enforcing_agency="Registrars",
        state_variance="Low/None",
        update_frequency="ISO 27001:2022 current; revisions every 5-10 years",
        authority_sources=({"domain": "iso.org", "name": "ISO"},),
    ),
    RegulationDef(
        key="clia_lab_certification", category="quality_systems",
        name="CLIA Laboratory Certification",
        description="Clinical Laboratory Improvement Amendments certification for lab testing quality",
        enforcing_agency="CMS/CDC",
        state_variance="Moderate",
        update_frequency="CLIA regulations updated periodically; CMS survey guidelines revised every few years",
        authority_sources=({"domain": "cms.gov/medicare/quality/clinical-laboratory-improvement-amendments", "name": "CMS CLIA"},),
    ),
    RegulationDef(
        key="cap_accreditation", category="quality_systems",
        name="CAP (College of American Pathologists) Accreditation",
        description="Laboratory accreditation program with proficiency testing and inspection standards",
        enforcing_agency="CAP",
        state_variance="Low/None",
        update_frequency="CAP checklists updated annually; accreditation cycle every 2 years",
        authority_sources=({"domain": "cap.org", "name": "CAP"},),
    ),
    RegulationDef(
        key="joint_commission_accreditation", category="quality_systems",
        name="Joint Commission Accreditation",
        description="Hospital and healthcare organization accreditation with performance standards",
        enforcing_agency="The Joint Commission",
        state_variance="Low/None",
        update_frequency="Standards updated annually; survey cycle every 3 years",
        authority_sources=({"domain": "jointcommission.org", "name": "Joint Commission"},),
    ),

    # ── Expansion: supply_chain ───────────────────────────────────────────────
    RegulationDef(
        key="conflict_minerals_dodd_frank", category="supply_chain",
        name="Conflict Minerals (Dodd-Frank \u00a71502)",
        description="SEC reporting requirements on tin, tantalum, tungsten, and gold sourcing from conflict regions",
        enforcing_agency="SEC",
        state_variance="Low/None",
        update_frequency="SEC rule stable since 2012; enforcement posture shifts with administration",
        authority_sources=({"domain": "sec.gov", "name": "SEC"},),
    ),
    RegulationDef(
        key="reach_regulation", category="supply_chain",
        name="REACH Chemical Registration (EU)",
        description="EU regulation for registration, evaluation, authorization, and restriction of chemicals",
        enforcing_agency="ECHA",
        state_variance="Low/None",
        update_frequency="REACH candidate list updated biannually; authorization list updated periodically",
        authority_sources=({"domain": "echa.europa.eu", "name": "ECHA"},),
    ),
    RegulationDef(
        key="rohs_directive", category="supply_chain",
        name="RoHS Directive",
        description="EU restriction of hazardous substances (lead, mercury, cadmium, etc.) in electrical/electronic equipment",
        enforcing_agency="EU Member States",
        state_variance="Low/None",
        update_frequency="Substance restrictions updated via delegated acts; exemptions reviewed periodically",
        authority_sources=({"domain": "ec.europa.eu", "name": "EU Commission"},),
    ),
    RegulationDef(
        key="uyghur_forced_labor_prevention", category="supply_chain",
        name="Uyghur Forced Labor Prevention Act (UFLPA)",
        description="Rebuttable presumption that goods from Xinjiang are made with forced labor; import restrictions",
        enforcing_agency="CBP/DHS",
        state_variance="Low/None",
        update_frequency="Entity list updated periodically; CBP enforcement guidance evolving",
        authority_sources=({"domain": "cbp.gov", "name": "CBP"},),
    ),
    RegulationDef(
        key="supplier_qualification_audit", category="supply_chain",
        name="Supplier Qualification & Audit Requirements",
        description="Supplier approval, qualification, and ongoing audit program requirements",
        enforcing_agency="FDA/ISO",
        state_variance="Moderate",
        update_frequency="FDA supplier expectations evolve with guidance; ISO standards revised every 5-10 years",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="track_trace_serialization", category="supply_chain",
        name="Track & Trace / Serialization",
        description="Product serialization requirements for supply chain visibility and anti-counterfeiting",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="DSCSA milestones phased through 2023-2025; FDA enforcement discretion ongoing",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="gpp_green_procurement", category="supply_chain",
        name="Green Procurement / Environmentally Preferable Purchasing",
        description="Sustainable purchasing policies and environmentally preferable product standards",
        enforcing_agency="EPA/GSA",
        state_variance="Low/None",
        update_frequency="EPA guidelines and GSA sustainable acquisition rules updated periodically",
        authority_sources=({"domain": "epa.gov", "name": "EPA"},),
    ),
    RegulationDef(
        key="antibribery_fcpa_uk_bribery", category="supply_chain",
        name="Anti-Bribery (FCPA / UK Bribery Act)",
        description="Foreign Corrupt Practices Act and UK Bribery Act anti-bribery and anti-corruption requirements",
        enforcing_agency="DOJ/SFO",
        state_variance="Low/None",
        update_frequency="FCPA framework stable; DOJ enforcement priorities and guidance updated periodically",
        authority_sources=({"domain": "justice.gov", "name": "DOJ"},),
    ),
]
