from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_MEDICAL_SPECIALTY: List[RegulationDef] = [
    RegulationDef(
        key="interstate_medical_licensure_compact",
        category="telehealth",
        name="Interstate Medical Licensure Compact (IMLC)",
        description="Expedited licensure for physicians across state lines; member states and eligibility",
        enforcing_agency="IMLC Commission",
        state_variance="High",
        update_frequency="New states join periodically; rules updated by Commission",
        authority_sources=({"domain": "imlcc.org", "name": "imlcc.org"},),
    ),
    RegulationDef(
        key="nurse_licensure_compact",
        category="telehealth",
        name="Nurse Licensure Compact (NLC)",
        description="Multistate nursing license for compact member states",
        enforcing_agency="NCSBN",
        state_variance="High",
        update_frequency="New states joining actively (2020–2026); rules updated by NCSBN",
        authority_sources=({"domain": "ncsbn.org/nurse-licensure-compact", "name": "ncsbn.org/nurse-licensure-compact"},),
    ),
    RegulationDef(
        key="psypact",
        category="telehealth",
        name="PSYPACT",
        description="Telepsychology and temporary in-person practice across member states",
        enforcing_agency="PSYPACT Commission",
        state_variance="High",
        update_frequency="Expanding membership; rules updated by Commission",
        authority_sources=({"domain": "psypact.org", "name": "psypact.org"},),
    ),
    RegulationDef(
        key="medicare_telehealth_coverage",
        category="telehealth",
        name="Medicare Telehealth Coverage (§1834(m))",
        description="Covered services, originating site, geographic restrictions; post-COVID flexibilities",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Annual updates via MPFS; COVID flexibilities extended/made permanent incrementally",
        authority_sources=({"domain": "cms.gov/medicare/coverage/telehealth", "name": "cms.gov/medicare/coverage/telehealth"},),
    ),
    RegulationDef(
        key="state_telehealth_parity_laws",
        category="telehealth",
        name="State Telehealth Parity Laws",
        description="Coverage and/or payment parity; modality requirements (audio-only, asynchronous)",
        enforcing_agency="State DOIs / Legislatures",
        state_variance="High",
        update_frequency="Active legislative area — updated every session",
        authority_sources=(
            {"domain": "cchpca.org", "name": "cchpca.org"},
            {"domain": "each state legislature", "name": "each state legislature"},
            {"domain": "telehealth.hhs.gov", "name": "telehealth.hhs.gov"},
        ),
    ),
    RegulationDef(
        key="ryan_haight_act",
        category="telehealth",
        name="Ryan Haight Act (Online Controlled Substance Prescribing)",
        description="DEA requirements for prescribing via telemedicine; in-person exam exceptions; special registration",
        enforcing_agency="DEA",
        state_variance="Moderate",
        update_frequency="Post-COVID flexibilities; DEA proposed rules 2023–2025 for telemedicine registration",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
            {"domain": "federalregister.gov", "name": "federalregister.gov"},
        ),
    ),
    RegulationDef(
        key="fda_digital_health_samd",
        category="telehealth",
        name="FDA Digital Health / SaMD",
        description="Clinical decision support, mobile medical apps, AI/ML-based SaMD; pre-market review",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="FDA Digital Health Center of Excellence guidance updated continuously",
        authority_sources=({"domain": "fda.gov/medical-devices/digital-health-center-excellence", "name": "fda.gov/medical-devices/digital-health-center-excellence"},),
    ),
    RegulationDef(
        key="remote_patient_monitoring",
        category="telehealth",
        name="Remote Patient Monitoring",
        description="Medicare RPM billing (CPT 99453–99458); state licensure for cross-state monitoring; device requirements",
        enforcing_agency="CMS / State",
        state_variance="Moderate",
        update_frequency="Annual MPFS updates; state licensure rules evolving",
        authority_sources=(
            {"domain": "cms.gov/medicare/coverage/telehealth", "name": "cms.gov/medicare/coverage/telehealth"},
            {"domain": "each state medical board", "name": "each state medical board"},
        ),
    ),
    RegulationDef(
        key="state_telehealth_practice_standards",
        category="telehealth",
        name="State Telehealth Practice Standards",
        description="Patient-provider relationship; consent; documentation; follow-up; prescribing limitations",
        enforcing_agency="State Medical Boards",
        state_variance="High",
        update_frequency="Updated every legislative session and via medical board rulemaking",
        authority_sources=(
            {"domain": "fsmb.org/advocacy/telemedicine", "name": "fsmb.org/advocacy/telemedicine"},
            {"domain": "each state medical board", "name": "each state medical board"},
        ),
    ),
    RegulationDef(
        key="aiml_in_clinical_decision_support",
        category="telehealth",
        name="AI/ML in Clinical Decision Support",
        description="FDA SaMD framework; transparency; bias monitoring; state-emerging AI regulations",
        enforcing_agency="FDA / State",
        state_variance="Moderate",
        update_frequency="FDA guidance updated annually; state AI laws emerging rapidly (2024–2026)",
        authority_sources=(
            {"domain": "fda.gov/medical-devices/software-medical-device-samd", "name": "fda.gov/medical-devices/software-medical-device-samd"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="fda_medical_device_reporting",
        category="medical_devices",
        name="FDA Medical Device Reporting (21 CFR Part 803)",
        description="Mandatory reporting of device-related deaths, serious injuries, malfunctions",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Reporting requirements stable; FDA guidance updated periodically",
        authority_sources=({"domain": "fda.gov/medical-devices/postmarket-requirements-devices/mandatory-reporting-requirements-manufacturers-importers-and-device-user-facilities", "name": "fda.gov/medical-devices/postmarket-requirements-devices/mandatory-reporting-requirements-manufacturers-importers-and-device-user-facilities"},),
    ),
    RegulationDef(
        key="medical_device_tracking",
        category="medical_devices",
        name="Medical Device Tracking (21 CFR Part 821)",
        description="Tracking for life-sustaining/life-supporting devices; patient notification",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Rarely amended",
        authority_sources=({"domain": "fda.gov/medical-devices/postmarket-requirements-devices/medical-device-tracking", "name": "fda.gov/medical-devices/postmarket-requirements-devices/medical-device-tracking"},),
    ),
    RegulationDef(
        key="equipment_maintenance_testing",
        category="medical_devices",
        name="Equipment Maintenance & Testing",
        description="CMS CoP; Joint Commission EC standards; preventive maintenance; clinical engineering",
        enforcing_agency="CMS / Joint Commission",
        state_variance="Moderate",
        update_frequency="Joint Commission EC standards updated annually; CMS CoPs less frequently",
        authority_sources=(
            {"domain": "jointcommission.org/standards", "name": "jointcommission.org/standards"},
            {"domain": "cms.gov", "name": "cms.gov"},
        ),
    ),
    RegulationDef(
        key="unique_device_identification",
        category="medical_devices",
        name="Unique Device Identification (UDI)",
        description="Device labeling and tracking; UDI in medical records",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Phased implementation complete; database (GUDID) maintained continuously",
        authority_sources=(
            {"domain": "fda.gov/medical-devices/unique-device-identification-system-udi-system", "name": "fda.gov/medical-devices/unique-device-identification-system-udi-system"},
            {"domain": "accessgudid.nlm.nih.gov", "name": "accessgudid.nlm.nih.gov"},
        ),
    ),
    RegulationDef(
        key="fda_recalls_safety_communications",
        category="medical_devices",
        name="FDA Recalls & Safety Communications",
        description="Facility obligations to respond to recalls; tracking affected patients; corrective actions",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Recalls issued as needed; facility response obligations ongoing",
        authority_sources=({"domain": "fda.gov/safety/recalls-market-withdrawals-safety-alerts", "name": "fda.gov/safety/recalls-market-withdrawals-safety-alerts"},),
    ),
    RegulationDef(
        key="radiationemitting_device_standards",
        category="medical_devices",
        name="Radiation-Emitting Device Standards (21 CFR Subchapter J)",
        description="Performance standards for X-ray, laser, ultrasound devices; reporting",
        enforcing_agency="FDA / State",
        state_variance="Moderate",
        update_frequency="Federal standards updated rarely; state programs inspect annually",
        authority_sources=(
            {"domain": "fda.gov/radiation-emitting-products", "name": "fda.gov/radiation-emitting-products"},
            {"domain": "each state radiation control", "name": "each state radiation control"},
        ),
    ),
    RegulationDef(
        key="safe_medical_devices_act",
        category="medical_devices",
        name="Safe Medical Devices Act (SMDA)",
        description="User facility reporting for device-related incidents; semi-annual summary reports",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Rarely amended (enacted 1990)",
        authority_sources=({"domain": "fda.gov/medical-devices/postmarket-requirements-devices", "name": "fda.gov/medical-devices/postmarket-requirements-devices"},),
    ),
    RegulationDef(
        key="510k_pma_de_novo",
        category="medical_devices",
        name="510(k) / PMA / De Novo Classification Pathways",
        description="Pre-market submission pathways for medical devices",
        enforcing_agency="FDA / CDRH",
        state_variance="Low/None",
        update_frequency="Guidance updated periodically",
        authority_sources=({"domain": "fda.gov/medical-devices", "name": "FDA CDRH"},),
    ),
    RegulationDef(
        key="design_controls_21cfr820",
        category="medical_devices",
        name="Design Controls (21 CFR 820 Subpart C)",
        description="Design input/output, verification, validation, transfer, changes",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="21 CFR 820 modernization ongoing",
        authority_sources=({"domain": "ecfr.gov", "name": "eCFR 21 CFR 820"},),
    ),
    RegulationDef(
        key="device_master_record",
        category="medical_devices",
        name="Device Master Record (DMR) & Device History Record (DHR)",
        description="Documentation requirements for device specifications and manufacturing history",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Stable",
        authority_sources=({"domain": "ecfr.gov", "name": "eCFR 21 CFR 820"},),
    ),
    RegulationDef(
        key="unique_device_identification_udi",
        category="medical_devices",
        name="Unique Device Identification (UDI) System",
        description="Device identification and labeling through supply chain",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Phase-in complete; GUDID maintained",
        authority_sources=({"domain": "fda.gov/medical-devices/unique-device-identification-system-udi-system", "name": "FDA UDI"},),
    ),
    RegulationDef(
        key="device_establishment_registration",
        category="medical_devices",
        name="Device Establishment Registration & Listing",
        description="Annual registration of manufacturing establishments and device listings",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="Annual renewal",
        authority_sources=({"domain": "fda.gov", "name": "FDA"},),
    ),
    RegulationDef(
        key="software_as_medical_device",
        category="medical_devices",
        name="Software as a Medical Device (SaMD) — IEC 62304",
        description="Software lifecycle for medical device software per IEC 62304 and FDA guidance",
        enforcing_agency="FDA / IEC",
        state_variance="Low/None",
        update_frequency="FDA guidance evolving; IEC 62304:2015",
        authority_sources=({"domain": "fda.gov", "name": "FDA Digital Health"},),
    ),
    RegulationDef(
        key="cybersecurity_medical_devices",
        category="medical_devices",
        name="Cybersecurity for Medical Devices (FDA Guidance + PATCH Act)",
        description="Pre/post-market cybersecurity for connected medical devices",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="FDA guidance 2023; PATCH Act provisions",
        authority_sources=({"domain": "fda.gov/medical-devices/digital-health-center-excellence", "name": "FDA Digital Health"},),
    ),
    RegulationDef(
        key="human_factors_usability",
        category="medical_devices",
        name="Human Factors / Usability Engineering (IEC 62366)",
        description="Usability engineering process for medical devices",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="IEC 62366-1:2015+AMD1:2020",
        authority_sources=({"domain": "fda.gov", "name": "FDA Human Factors"},),
    ),
    RegulationDef(
        key="national_organ_transplant_act",
        category="transplant_organ",
        name="National Organ Transplant Act (NOTA)",
        description="Federal framework for procurement, allocation, transplantation; prohibition on organ sales",
        enforcing_agency="HRSA / OPTN",
        state_variance="Low/None",
        update_frequency="Rarely amended; OPTN contract restructuring underway (2024–2026)",
        authority_sources=(
            {"domain": "hrsa.gov/opa", "name": "hrsa.gov/opa"},
            {"domain": "organdonor.gov", "name": "organdonor.gov"},
        ),
    ),
    RegulationDef(
        key="cms_cops_for_transplant_centers",
        category="transplant_organ",
        name="CMS CoPs for Transplant Centers (42 CFR 482.68–104)",
        description="Outcomes, patient selection, organ procurement, living donor protections, SRTR data",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Updated every 3–5 yrs; CMS relaxed outcome requirements 2020",
        authority_sources=({"domain": "cms.gov/regulations-and-guidance/legislation/cfr", "name": "cms.gov/regulations-and-guidance/legislation/cfr"},),
    ),
    RegulationDef(
        key="optnunos_policies_bylaws",
        category="transplant_organ",
        name="OPTN/UNOS Policies & Bylaws",
        description="Allocation policies, listing criteria, waitlist, member obligations, data reporting",
        enforcing_agency="OPTN / UNOS",
        state_variance="Low/None",
        update_frequency="OPTN policies updated continuously (board votes on changes multiple times/yr)",
        authority_sources=({"domain": "optn.transplant.hrsa.gov/policies-bylaws", "name": "optn.transplant.hrsa.gov/policies-bylaws"},),
    ),
    RegulationDef(
        key="tissue_banking",
        category="transplant_organ",
        name="Tissue Banking (FDA 21 CFR Parts 1270, 1271)",
        description="Donor screening, testing, processing, storage, labeling for HCT/Ps",
        enforcing_agency="FDA",
        state_variance="Moderate",
        update_frequency="FDA guidance updated every 2–3 yrs",
        authority_sources=({"domain": "fda.gov/vaccines-blood-biologics/tissue-tissue-products", "name": "fda.gov/vaccines-blood-biologics/tissue-tissue-products"},),
    ),
    RegulationDef(
        key="opo_conditions_for_coverage",
        category="transplant_organ",
        name="OPO Conditions for Coverage",
        description="Performance metrics, governance, hospital agreements, brain death protocols",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Major update 2020 (outcome measures); CMS final rule on OPO performance 2020",
        authority_sources=({"domain": "cms.gov/regulations-and-guidance/legislation/cfr", "name": "cms.gov/regulations-and-guidance/legislation/cfr"},),
    ),
    RegulationDef(
        key="sherman_act_clayton_act",
        category="antitrust",
        name="Sherman Act / Clayton Act",
        description="Price-fixing, market allocation, group boycotts; merger review for hospital consolidation",
        enforcing_agency="DOJ / FTC",
        state_variance="Moderate",
        update_frequency="Statutes rarely amended; enforcement priorities shift with administrations",
        authority_sources=(
            {"domain": "justice.gov/atr", "name": "justice.gov/atr"},
            {"domain": "ftc.gov/enforcement/competition-matters/healthcare", "name": "ftc.gov/enforcement/competition-matters/healthcare"},
        ),
    ),
    RegulationDef(
        key="ftc_act_5",
        category="antitrust",
        name="FTC Act §5",
        description="FTC authority over anticompetitive practices in healthcare",
        enforcing_agency="FTC",
        state_variance="Low/None",
        update_frequency="FTC enforcement priorities updated annually",
        authority_sources=({"domain": "ftc.gov/enforcement", "name": "ftc.gov/enforcement"},),
    ),
    RegulationDef(
        key="hartscottrodino_act",
        category="antitrust",
        name="Hart-Scott-Rodino Act (HSR)",
        description="Pre-merger notification for healthcare transactions above thresholds",
        enforcing_agency="FTC / DOJ",
        state_variance="Low/None",
        update_frequency="Thresholds adjusted annually for GDP; reporting form updated 2024",
        authority_sources=({"domain": "ftc.gov/enforcement/premerger-notification-program", "name": "ftc.gov/enforcement/premerger-notification-program"},),
    ),
    RegulationDef(
        key="certificate_of_need",
        category="antitrust",
        name="Certificate of Need (CON)",
        description="Some states require CON for new facilities, equipment, service expansions",
        enforcing_agency="State Health Planning",
        state_variance="High",
        update_frequency="Active reform area — some states expanding, others repealing CON",
        authority_sources=(
            {"domain": "ncsl.org/health/certificate-of-need-state-health-laws", "name": "ncsl.org/health/certificate-of-need-state-health-laws"},
            {"domain": "each state health planning agency", "name": "each state health planning agency"},
        ),
    ),
    RegulationDef(
        key="state_ag_healthcare_transaction_review",
        category="antitrust",
        name="State AG Healthcare Transaction Review",
        description="Many states require AG review of healthcare mergers/acquisitions, especially nonprofits",
        enforcing_agency="State AGs",
        state_variance="High",
        update_frequency="Growing state AG activity; new review laws enacted annually",
        authority_sources=(
            {"domain": "Each state AG office", "name": "Each state AG office"},
            {"domain": "nashp.org", "name": "nashp.org"},
        ),
    ),
    RegulationDef(
        key="irc_501_for_charitable_hospitals",
        category="tax_exempt",
        name="IRC §501(r) for Charitable Hospitals",
        description="CHNA every 3 yrs; financial assistance policy; charge limitations; billing/collection practices",
        enforcing_agency="IRS",
        state_variance="Moderate",
        update_frequency="IRS final regulations 2014; CHNA cycles every 3 yrs; IRS guidance periodic",
        authority_sources=({"domain": "irs.gov/charities-non-profits/charitable-organizations/requirements-for-501c3-hospitals", "name": "irs.gov/charities-non-profits/charitable-organizations/requirements-for-501c3-hospitals"},),
    ),
    RegulationDef(
        key="irs_form_990_schedule_h",
        category="tax_exempt",
        name="IRS Form 990 Schedule H",
        description="Community benefit reporting; financial assistance; bad debt; Medicare shortfall; community building",
        enforcing_agency="IRS",
        state_variance="Low/None",
        update_frequency="Schedule H updated periodically; filed annually",
        authority_sources=({"domain": "irs.gov/forms-pubs/about-schedule-h-form-990", "name": "irs.gov/forms-pubs/about-schedule-h-form-990"},),
    ),
    RegulationDef(
        key="state_community_benefit_requirements",
        category="tax_exempt",
        name="State Community Benefit Requirements",
        description="Additional reporting, spending minimums, CHNA requirements beyond 501(r)",
        enforcing_agency="State AGs / Health Depts",
        state_variance="High",
        update_frequency="State laws update every 1–3 yrs; growing scrutiny of hospital tax exemptions",
        authority_sources=(
            {"domain": "Each state AG", "name": "Each state AG"},
            {"domain": "hilltopinstitute.org/community-benefit", "name": "hilltopinstitute.org/community-benefit"},
        ),
    ),
    RegulationDef(
        key="state_property_tax_exemptions",
        category="tax_exempt",
        name="State Property Tax Exemptions",
        description="State-specific requirements; community benefit standards; charity care thresholds",
        enforcing_agency="State/Local Tax Authorities",
        state_variance="High",
        update_frequency="Active litigation and legislative reform area",
        authority_sources=({"domain": "Each state revenue/tax authority", "name": "Each state revenue/tax authority"},),
    ),
    RegulationDef(
        key="ubit",
        category="tax_exempt",
        name="UBIT (Unrelated Business Income Tax)",
        description="Tax on income from non-exempt activities; parking, laundry, pharmacy sales to nonpatients",
        enforcing_agency="IRS",
        state_variance="Low/None",
        update_frequency="TCJA 2017 changes; IRS guidance updated periodically",
        authority_sources=({"domain": "irs.gov/charities-non-profits/unrelated-business-income-tax", "name": "irs.gov/charities-non-profits/unrelated-business-income-tax"},),
    ),
    RegulationDef(
        key="title_vi",
        category="language_access",
        name="Title VI (Language Access)",
        description="Meaningful access for LEP individuals; qualified interpreters; translated vital documents; signage",
        enforcing_agency="HHS OCR",
        state_variance="Moderate",
        update_frequency="HHS LEP guidance updated every 5–10 yrs; OCR enforcement ongoing",
        authority_sources=(
            {"domain": "hhs.gov/civil-rights/for-individuals/special-topics/limited-english-proficiency", "name": "hhs.gov/civil-rights/for-individuals/special-topics/limited-english-proficiency"},
            {"domain": "lep.gov", "name": "lep.gov"},
        ),
    ),
    RegulationDef(
        key="section_1557_aca",
        category="language_access",
        name="Section 1557 ACA (Detailed)",
        description="Comprehensive nondiscrimination; sex (including gender identity); disability; age",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Major rulemaking cycles: 2016, 2020, 2024",
        authority_sources=({"domain": "hhs.gov/civil-rights/for-individuals/section-1557", "name": "hhs.gov/civil-rights/for-individuals/section-1557"},),
    ),
    RegulationDef(
        key="ada_effective_communication",
        category="language_access",
        name="ADA Effective Communication",
        description="Auxiliary aids for disabilities; interpreters; accessible formats; relay services",
        enforcing_agency="DOJ / HHS OCR",
        state_variance="Low/None",
        update_frequency="ADA Title II/III guidance updated periodically",
        authority_sources=(
            {"domain": "ada.gov", "name": "ada.gov"},
            {"domain": "hhs.gov/civil-rights", "name": "hhs.gov/civil-rights"},
        ),
    ),
    RegulationDef(
        key="state_language_access_laws",
        category="language_access",
        name="State Language Access Laws",
        description="Specific interpreter qualifications; translated document requirements; enhanced access",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Updated via state legislation every 1–3 yrs",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ncsl.org", "name": "ncsl.org"},
        ),
    ),
    RegulationDef(
        key="clas_standards",
        category="language_access",
        name="CLAS Standards",
        description="National standards for culturally competent care; governance, communication, engagement",
        enforcing_agency="HHS OMH",
        state_variance="Low/None",
        update_frequency="CLAS Standards released 2013; OMH resources updated periodically",
        authority_sources=({"domain": "thinkculturalhealth.hhs.gov/clas", "name": "thinkculturalhealth.hhs.gov/clas"},),
    ),
    RegulationDef(
        key="religious_accommodation_in_healthcare",
        category="language_access",
        name="Religious Accommodation in Healthcare",
        description="Title VII employee accommodation; patient dietary, dress, blood product, end-of-life preferences",
        enforcing_agency="EEOC / HHS OCR",
        state_variance="Moderate",
        update_frequency="EEOC guidance updated periodically; Groff v. DeJoy (2023) raised accommodation standard",
        authority_sources=(
            {"domain": "eeoc.gov/religious-discrimination", "name": "eeoc.gov/religious-discrimination"},
            {"domain": "hhs.gov/conscience", "name": "hhs.gov/conscience"},
        ),
    ),
    RegulationDef(
        key="medical_records_retention",
        category="records_retention",
        name="Medical Records Retention",
        description="No single federal standard; CMS requires policies; HIPAA 6 yrs for compliance docs; state laws 5–30+ yrs; minors longer",
        enforcing_agency="CMS / State law",
        state_variance="High",
        update_frequency="State retention laws update every 3–5 yrs",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ahima.org/topics/retention-and-destruction", "name": "ahima.org/topics/retention-and-destruction"},
        ),
    ),
    RegulationDef(
        key="hipaa_documentation_requirements",
        category="records_retention",
        name="HIPAA Documentation Requirements",
        description="6-year retention for policies, procedures, training, BAAs, risk assessments",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Stable requirement since HIPAA implementation",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/privacy/guidance/documentation", "name": "hhs.gov/hipaa/for-professionals/privacy/guidance/documentation"},),
    ),
    RegulationDef(
        key="medical_records_content_standards",
        category="records_retention",
        name="Medical Records Content Standards",
        description="CMS CoP requirements; authentication; verbal orders; documentation per accreditor",
        enforcing_agency="CMS / Accreditors",
        state_variance="Moderate",
        update_frequency="Updated with CMS CoP and accreditor standard revisions",
        authority_sources=(
            {"domain": "cms.gov", "name": "cms.gov"},
            {"domain": "jointcommission.org/standards", "name": "jointcommission.org/standards"},
        ),
    ),
    RegulationDef(
        key="patient_access_to_records",
        category="records_retention",
        name="Patient Access to Records (HIPAA Right of Access)",
        description="30-day response; reasonable fees; electronic copies; OCR Right of Access Initiative",
        enforcing_agency="HHS OCR",
        state_variance="Moderate",
        update_frequency="OCR enforcement initiative launched 2019; active enforcement ongoing",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/privacy/guidance/access", "name": "hhs.gov/hipaa/for-professionals/privacy/guidance/access"},),
    ),
    RegulationDef(
        key="state_medical_records_laws",
        category="records_retention",
        name="State Medical Records Laws",
        description="Content, retention, access, amendment, fees, destruction methods",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Updated via state legislation every 2–5 yrs",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "ahima.org", "name": "ahima.org"},
        ),
    ),
    RegulationDef(
        key="legal_hold_litigation_preservation",
        category="records_retention",
        name="Legal Hold & Litigation Preservation",
        description="Preservation upon litigation notice; spoliation consequences; e-discovery",
        enforcing_agency="Courts / DOJ",
        state_variance="Moderate",
        update_frequency="Case law evolves continuously; FRCP amendments periodic",
        authority_sources=({"domain": "uscourts.gov/rules-policies/current-rules-practice-procedure", "name": "uscourts.gov/rules-policies/current-rules-practice-procedure"},),
    ),
    RegulationDef(
        key="baa_requirements",
        category="records_retention",
        name="BAA Requirements",
        description="HIPAA-mandated contracts with vendors accessing PHI; required provisions; breach obligations",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Requirements stable since 2013 Omnibus Rule; OCR template available",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/covered-entities/sample-business-associate-agreement-provisions", "name": "hhs.gov/hipaa/for-professionals/covered-entities/sample-business-associate-agreement-provisions"},),
    ),
    RegulationDef(
        key="hipaa_marketing_restrictions",
        category="marketing_comms",
        name="HIPAA Marketing Restrictions",
        description="Marketing vs. treatment communications; authorization requirements; refill/face-to-face exceptions",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Stable since Omnibus Rule 2013",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/privacy/guidance/marketing", "name": "hhs.gov/hipaa/for-professionals/privacy/guidance/marketing"},),
    ),
    RegulationDef(
        key="medicare_marketing_guidelines",
        category="marketing_comms",
        name="Medicare Marketing Guidelines (MCMG)",
        description="MA and Part D marketing rules; prohibited activities; disclaimers; CMS pre-review",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Updated annually (published with MA Rate Announcement)",
        authority_sources=({"domain": "cms.gov/medicare/health-plans/managedcaremarketing", "name": "cms.gov/medicare/health-plans/managedcaremarketing"},),
    ),
    RegulationDef(
        key="tcpa",
        category="marketing_comms",
        name="TCPA",
        description="Consent for autodialed calls/texts; healthcare exception is narrow; state mini-TCPAs",
        enforcing_agency="FCC / State",
        state_variance="High",
        update_frequency="FCC orders updated periodically; 1-to-1 consent rule 2025; state laws expanding",
        authority_sources=(
            {"domain": "fcc.gov/general/telemarketing-and-robocalls", "name": "fcc.gov/general/telemarketing-and-robocalls"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="canspam_act",
        category="marketing_comms",
        name="CAN-SPAM Act",
        description="Commercial email requirements; opt-out; sender ID",
        enforcing_agency="FTC",
        state_variance="Low/None",
        update_frequency="Rarely amended (enacted 2003)",
        authority_sources=({"domain": "ftc.gov/legal-library/browse/rules/can-spam-rule", "name": "ftc.gov/legal-library/browse/rules/can-spam-rule"},),
    ),
    RegulationDef(
        key="state_consumer_protection_deceptive_practices",
        category="marketing_comms",
        name="State Consumer Protection / Deceptive Practices",
        description="State laws on deceptive healthcare advertising; testimonials; price transparency",
        enforcing_agency="State AGs / DOIs",
        state_variance="High",
        update_frequency="Updated via state legislation/AG enforcement",
        authority_sources=({"domain": "Each state AG office", "name": "Each state AG office"},),
    ),
    RegulationDef(
        key="ftc_endorsement_guidelines",
        category="marketing_comms",
        name="FTC Endorsement Guidelines",
        description="Physician endorsements; social media disclosure; patient testimonials",
        enforcing_agency="FTC",
        state_variance="Low/None",
        update_frequency="Updated 2023; next update in several years",
        authority_sources=({"domain": "ftc.gov/legal-library/browse/rules/guides-concerning-endorsements-testimonials", "name": "ftc.gov/legal-library/browse/rules/guides-concerning-endorsements-testimonials"},),
    ),
    RegulationDef(
        key="price_transparency",
        category="marketing_comms",
        name="Price Transparency (Hospital & Insurance)",
        description="Hospital machine-readable files, shoppable services; Transparency in Coverage for insurers",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Hospital rule effective 2021; insurer rule phased 2022–2024; CMS enforcement increasing",
        authority_sources=(
            {"domain": "cms.gov/hospital-price-transparency", "name": "cms.gov/hospital-price-transparency"},
            {"domain": "cms.gov/healthplan-price-transparency", "name": "cms.gov/healthplan-price-transparency"},
        ),
    ),
    RegulationDef(
        key="state_facility_licensure",
        category="state_licensing",
        name="State Facility Licensure",
        description="State-specific licensing for hospitals, ASCs, clinics, behavioral health, HHAs, hospice, LTC, urgent care, imaging",
        enforcing_agency="State Health Depts",
        state_variance="High",
        update_frequency="Continuous — updated via state regulation and legislation",
        authority_sources=({"domain": "Each state health department", "name": "Each state health department"},),
    ),
    RegulationDef(
        key="medicaremedicaid_certification",
        category="state_licensing",
        name="Medicare/Medicaid Certification",
        description="Federal certification for program participation; survey process; deficiency correction",
        enforcing_agency="CMS / State Survey Agencies",
        state_variance="Low/None",
        update_frequency="Survey protocols updated every 2–3 yrs; Interpretive Guidelines updated ongoing",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},),
    ),
    RegulationDef(
        key="certificate_of_need_programs",
        category="state_licensing",
        name="Certificate of Need (CON) Programs",
        description="35+ states require CON for new facilities, capital expenditures, beds, new services",
        enforcing_agency="State Health Planning",
        state_variance="High",
        update_frequency="Active reform area; some states repealing, others strengthening",
        authority_sources=({"domain": "ncsl.org/health/certificate-of-need-state-health-laws", "name": "ncsl.org/health/certificate-of-need-state-health-laws"},),
    ),
    RegulationDef(
        key="corporate_practice_of_medicine_doctrine",
        category="state_licensing",
        name="Corporate Practice of Medicine Doctrine",
        description="State prohibitions on corporate employment of physicians or control of clinical decisions; MSO structures",
        enforcing_agency="State Medical Boards / Courts",
        state_variance="High",
        update_frequency="Evolves via case law and AG opinions; varies dramatically by state",
        authority_sources=(
            {"domain": "Each state medical board", "name": "Each state medical board"},
            {"domain": "state AG opinions", "name": "state AG opinions"},
        ),
    ),
    RegulationDef(
        key="feesplitting_prohibitions",
        category="state_licensing",
        name="Fee-Splitting Prohibitions",
        description="Restrictions on dividing fees with non-licensed persons; impact on practice management",
        enforcing_agency="State Medical Boards",
        state_variance="High",
        update_frequency="Updated via state statute and medical board rules",
        authority_sources=({"domain": "Each state medical board", "name": "Each state medical board"},),
    ),
    RegulationDef(
        key="nonprofit_healthcare_governance",
        category="state_licensing",
        name="Nonprofit Healthcare Governance",
        description="State requirements for nonprofit hospital boards; fiduciary duties; conflicts; AG oversight of conversions",
        enforcing_agency="State AGs",
        state_variance="High",
        update_frequency="Growing AG scrutiny of nonprofit hospital transactions and governance",
        authority_sources=({"domain": "Each state AG office", "name": "Each state AG office"},),
    ),
    RegulationDef(
        key="medical_staff_bylaws_selfgovernance",
        category="state_licensing",
        name="Medical Staff Bylaws & Self-Governance",
        description="CMS CoP organized medical staff; bylaws; fair hearing/appeal; peer review protections (HCQIA)",
        enforcing_agency="CMS / State",
        state_variance="Moderate",
        update_frequency="HCQIA (1986) stable; CMS CoPs updated every 3–5 yrs; state peer review protections vary",
        authority_sources=(
            {"domain": "cms.gov", "name": "cms.gov"},
            {"domain": "npdb.hrsa.gov/resources/aboutHcqia.jsp", "name": "npdb.hrsa.gov/resources/aboutHcqia.jsp"},
        ),
    ),
    RegulationDef(
        key="ai_algorithmic_decisionmaking",
        category="emerging_regulatory",
        name="AI & Algorithmic Decision-Making",
        description="FDA SaMD framework; CMS coverage of AI diagnostics; state AI transparency/bias laws; liability",
        enforcing_agency="FDA / CMS / State",
        state_variance="High",
        update_frequency="Extremely active — FDA guidance, state laws, and EU AI Act developments continuously",
        authority_sources=(
            {"domain": "fda.gov/medical-devices/software-medical-device-samd", "name": "fda.gov/medical-devices/software-medical-device-samd"},
            {"domain": "each state legislature", "name": "each state legislature"},
            {"domain": "ai.gov", "name": "ai.gov"},
        ),
    ),
    RegulationDef(
        key="social_determinants_of_health_data",
        category="emerging_regulatory",
        name="Social Determinants of Health (SDOH) Data",
        description="CMS SDOH screening (Z-codes); ONC USCDI SDOH elements; privacy considerations",
        enforcing_agency="CMS / ONC",
        state_variance="Low/None",
        update_frequency="USCDI SDOH elements expanding annually; CMS guidance periodic",
        authority_sources=(
            {"domain": "cms.gov/priorities/health-equity", "name": "cms.gov/priorities/health-equity"},
            {"domain": "healthit.gov/isa/uscdi", "name": "healthit.gov/isa/uscdi"},
        ),
    ),
    RegulationDef(
        key="health_equity_compliance",
        category="emerging_regulatory",
        name="Health Equity Compliance",
        description="CMS health equity initiatives; accreditation standards; disparities reporting; cultural competency",
        enforcing_agency="CMS / Accreditors",
        state_variance="Moderate",
        update_frequency="CMS health equity framework 2022; accreditor requirements expanding",
        authority_sources=(
            {"domain": "cms.gov/priorities/health-equity", "name": "cms.gov/priorities/health-equity"},
            {"domain": "jointcommission.org/resources/health-equity", "name": "jointcommission.org/resources/health-equity"},
        ),
    ),
    RegulationDef(
        key="cannabis_medical_marijuana",
        category="emerging_regulatory",
        name="Cannabis / Medical Marijuana",
        description="Federal Schedule I vs. state programs; employer testing conflicts; patient accommodations; banking",
        enforcing_agency="DEA / State",
        state_variance="High",
        update_frequency="Federal scheduling review underway; state programs update continuously",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
            {"domain": "each state cannabis regulatory agency", "name": "each state cannabis regulatory agency"},
            {"domain": "ncsl.org/health/state-medical-cannabis-laws", "name": "ncsl.org/health/state-medical-cannabis-laws"},
        ),
    ),
    RegulationDef(
        key="genomic_medicine_precision_health",
        category="emerging_regulatory",
        name="Genomic Medicine & Precision Health",
        description="Genetic testing (CLIA, FDA); genetic counseling licensure; GINA; genetic data privacy; DTC testing",
        enforcing_agency="FDA / CLIA / State",
        state_variance="High",
        update_frequency="FDA oversight evolving; state genetic privacy laws expanding; GINA stable",
        authority_sources=(
            {"domain": "fda.gov/medical-devices/in-vitro-diagnostics/direct-consumer-tests", "name": "fda.gov/medical-devices/in-vitro-diagnostics/direct-consumer-tests"},
            {"domain": "genome.gov", "name": "genome.gov"},
        ),
    ),
    RegulationDef(
        key="clinical_decision_support_exemptions",
        category="emerging_regulatory",
        name="Clinical Decision Support (CDS) Exemptions",
        description="21st Century Cures CDS exemptions from device regulation; four-criteria test; locked vs. adaptive CDS",
        enforcing_agency="FDA",
        state_variance="Low/None",
        update_frequency="FDA guidance finalized 2022; updates as technology evolves",
        authority_sources=({"domain": "fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software", "name": "fda.gov/regulatory-information/search-fda-guidance-documents/clinical-decision-support-software"},),
    ),
    RegulationDef(
        key="autonomous_robotic_surgery_systems",
        category="emerging_regulatory",
        name="Autonomous & Robotic Surgery Systems",
        description="FDA clearance; credentialing for robotic procedures; facility requirements; reporting",
        enforcing_agency="FDA / State",
        state_variance="Moderate",
        update_frequency="FDA clearances ongoing; facility standards evolving with technology",
        authority_sources=(
            {"domain": "fda.gov/medical-devices", "name": "fda.gov/medical-devices"},
            {"domain": "each state health dept", "name": "each state health dept"},
        ),
    ),
    RegulationDef(
        key="right_to_try_act",
        category="emerging_regulatory",
        name="Right to Try Act (21 U.S.C. § 360bbb-0a)",
        description="Patient access to investigational drugs outside trials; eligibility; manufacturer reporting; state laws",
        enforcing_agency="FDA / State",
        state_variance="Moderate",
        update_frequency="Federal law enacted 2018; state laws enacted 2014–2018; relatively stable now",
        authority_sources=({"domain": "fda.gov/patients/learn-about-expanded-access-and-other-treatment-options/right-try", "name": "fda.gov/patients/learn-about-expanded-access-and-other-treatment-options/right-try"},),
    ),
    RegulationDef(
        key="interstate_practice_multistate_compliance",
        category="emerging_regulatory",
        name="Interstate Practice & Multi-State Compliance",
        description="Challenges of multi-state operations; varying licensure, scope, mandates, privacy laws; compacts",
        enforcing_agency="Multiple",
        state_variance="High",
        update_frequency="Continuous — each state has independent update cycle",
        authority_sources=(
            {"domain": "imlcc.org", "name": "imlcc.org"},
            {"domain": "ncsbn.org", "name": "ncsbn.org"},
            {"domain": "cchpca.org", "name": "cchpca.org"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="environmental_sustainability_reporting",
        category="emerging_regulatory",
        name="Environmental Sustainability Reporting",
        description="Emerging requirements for healthcare carbon footprint, sustainable procurement, environmental impact",
        enforcing_agency="EPA / State / Voluntary",
        state_variance="Moderate",
        update_frequency="Voluntary frameworks evolving; some state mandates emerging",
        authority_sources=(
            {"domain": "epa.gov", "name": "epa.gov"},
            {"domain": "practicegreenhealth.org", "name": "practicegreenhealth.org"},
            {"domain": "jointcommission.org", "name": "jointcommission.org"},
        ),
    ),
]
