from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_LABOR: List[RegulationDef] = [

    # ── Labor: minimum_wage ───────────────────────────────────────────────
    RegulationDef(
        key="state_minimum_wage",
        category="minimum_wage",
        name="State Minimum Wage",
        description="State-level minimum wage rate; many states set rates above the federal FLSA floor",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Annual or biennial adjustments in most states; some indexed to CPI",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/state", "name": "WHD State Minimum Wage"},
        ),
    ),
    RegulationDef(
        key="tipped_minimum_wage",
        category="minimum_wage",
        name="Tipped Employee Minimum Wage / Tip Credit",
        description="Minimum cash wage for tipped employees and allowable tip credit; varies widely by state",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Updated with minimum wage changes; active legislative area",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/tips", "name": "WHD Tipped Wages"},
        ),
    ),
    RegulationDef(
        key="exempt_salary_threshold",
        category="minimum_wage",
        name="Exempt Employee Salary Threshold (FLSA + State)",
        description="Minimum salary threshold for white-collar overtime exemptions under FLSA and state equivalents",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Federal updates every 3-5 yrs; state thresholds change independently",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/overtime", "name": "WHD Overtime Exemptions"},
        ),
    ),
    RegulationDef(
        # NY (and a few other states) set a HIGHER exempt threshold for a named
        # region than for the rest of the state — NYC + Nassau/Suffolk/Westchester
        # vs "remainder of state". Two different dollar figures, both live, both
        # binding on their own geography: two obligations, so two keys. Without
        # this they both land on `exempt_salary_threshold` and collide, which is
        # exactly the polymorphy the one-code-one-obligation rule forbids.
        key="exempt_salary_threshold_regional",
        category="minimum_wage",
        name="Exempt Employee Salary Threshold — Regional Tier",
        description=(
            "Higher exempt-salary threshold applying to a named sub-state region "
            "(e.g. NY downstate: NYC, Nassau, Suffolk, Westchester)"
        ),
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Changes on the state's own schedule, independently of the statewide tier",
        authority_sources=(
            {"domain": "dol.ny.gov", "name": "NY DOL"},
        ),
    ),
    RegulationDef(
        key="fast_food_minimum_wage",
        category="minimum_wage",
        name="Fast Food Industry Minimum Wage",
        description="Industry-specific minimum wage for fast food workers (CA AB 1228 and similar)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active legislative area — new rates set annually by council (CA)",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/fast-food-minimum-wage.htm", "name": "CA DIR Fast Food Wage"},
        ),
    ),
    RegulationDef(
        key="healthcare_minimum_wage",
        category="minimum_wage",
        name="Healthcare Worker Minimum Wage",
        description="Industry-specific minimum wage for healthcare workers (CA SB 525 and similar)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active legislative area — phased increases through 2028+",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/healthcare-worker-minimum-wage.htm", "name": "CA DIR Healthcare Wage"},
        ),
    ),
    RegulationDef(
        key="large_employer_minimum_wage",
        category="minimum_wage",
        name="Large Employer Minimum Wage Tier",
        description="Higher minimum wage tier for large employers based on employee count or revenue thresholds",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Adjusted annually in jurisdictions with tiered systems",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/state", "name": "WHD State Minimum Wage"},
        ),
    ),
    RegulationDef(
        key="small_employer_minimum_wage",
        category="minimum_wage",
        name="Small Employer Minimum Wage Tier",
        description="Lower minimum wage tier for small employers; phase-up schedules in many jurisdictions",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Adjusted annually; phase-up schedules converge with large employer rates",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/state", "name": "WHD State Minimum Wage"},
        ),
    ),
    RegulationDef(
        key="youth_minimum_wage",
        category="minimum_wage",
        name="Youth / Training Sub-Minimum Wage",
        description="Reduced minimum wage for workers under 20 during first 90 days, or training wage provisions",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="Rarely changed; tied to base minimum wage adjustments",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/youth", "name": "WHD Youth Minimum Wage"},
        ),
    ),
    RegulationDef(
        key="tip_credit_prohibition",
        category="minimum_wage",
        name="Tip Credit Prohibition",
        description="States that prohibit tip credits, requiring full minimum wage before tips (e.g., CA, OR, WA, MN)",
        enforcing_agency="State legislatures",
        state_variance="High",
        update_frequency="Changes with state minimum wage legislation",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/tips", "name": "WHD Tipped Wages"},
        ),
    ),
    RegulationDef(
        key="local_minimum_wage",
        category="minimum_wage",
        name="City / County Minimum Wage Ordinances",
        description="Local minimum wage rates that exceed state rates; common in major metro areas",
        enforcing_agency="Local government",
        state_variance="High",
        update_frequency="Annual adjustments; many indexed to CPI",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/minimum-wage/state", "name": "WHD State Minimum Wage"},
            {"domain": "epi.org/minimum-wage-tracker", "name": "EPI Minimum Wage Tracker"},
        ),
    ),
    RegulationDef(
        key="national_minimum_wage",
        category="minimum_wage",
        name="National Minimum Wage (International)",
        description="Nationally mandated minimum wage rate set by government; applies to all or most workers",
        enforcing_agency="National government / Labor ministry",
        state_variance="Moderate",
        update_frequency="Typically reviewed annually; varies by country",
        authority_sources=(
            {"domain": "ilo.org/global/topics/wages", "name": "ILO Wages"},
        ),
    ),
    RegulationDef(
        key="zlfn_border_zone_minimum_wage",
        category="minimum_wage",
        name="Mexico Free Zone Border Minimum Wage (ZLFN)",
        description="Higher minimum wage for Mexico's northern border free zone (Zona Libre de la Frontera Norte)",
        enforcing_agency="CONASAMI",
        state_variance="High",
        update_frequency="Set annually by CONASAMI; significant increases in recent years",
        authority_sources=(
            {"domain": "gob.mx/conasami", "name": "CONASAMI"},
        ),
    ),

    # ── Labor: overtime ───────────────────────────────────────────────────
    RegulationDef(
        key="daily_weekly_overtime",
        category="overtime",
        name="Daily and Weekly Overtime Thresholds and Rates",
        description="Overtime pay requirements based on daily (8hr) and weekly (40hr) thresholds; 1.5x regular rate",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Federal FLSA thresholds stable; state daily OT laws change periodically",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/overtime", "name": "WHD Overtime"},
        ),
    ),
    RegulationDef(
        key="double_time",
        category="overtime",
        name="Double-Time Pay Requirements",
        description="Double-time pay for hours exceeding daily or weekly thresholds (CA: >12hr/day, 7th consecutive day >8hr)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Changes with state labor code amendments",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/overtime.htm", "name": "CA DIR Overtime"},
        ),
    ),
    RegulationDef(
        key="seventh_day_overtime",
        category="overtime",
        name="Seventh Consecutive Day Overtime",
        description="Premium pay for work on the seventh consecutive day in a workweek (CA, others)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Changes with state labor code amendments",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/overtime.htm", "name": "CA DIR Overtime"},
        ),
    ),
    RegulationDef(
        key="alternative_workweek",
        category="overtime",
        name="Alternative Workweek Schedule Elections",
        description="Employer ability to adopt alternative workweek schedules (e.g., 4x10) with employee vote; affects daily OT",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Rarely changed; election procedures are stable",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/alternative_workweek.htm", "name": "CA DIR Alternative Workweek"},
        ),
    ),
    RegulationDef(
        key="healthcare_overtime",
        category="overtime",
        name="Healthcare Overtime Restrictions",
        description="Restrictions on mandatory overtime for healthcare workers; mandatory OT bans in nursing (e.g., NY, PA, ME)",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Active legislative area — new states enacting restrictions",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/overtime", "name": "WHD Overtime"},
            {"domain": "ncsl.org/labor-and-employment/state-overtime-requirements", "name": "NCSL Overtime"},
        ),
    ),
    RegulationDef(
        key="mandatory_overtime_restrictions",
        category="overtime",
        name="Restrictions on Mandatory Overtime",
        description="State laws restricting or prohibiting employers from requiring mandatory overtime; industry-specific bans",
        enforcing_agency="State legislatures",
        state_variance="High",
        update_frequency="Active legislative area — expanding to more industries and states",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/state-overtime-requirements", "name": "NCSL Overtime"},
        ),
    ),
    RegulationDef(
        key="comp_time",
        category="overtime",
        name="Compensatory Time Off in Lieu of Overtime Pay",
        description="Rules for offering comp time instead of overtime pay; generally limited to public sector under FLSA",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="Federal rule stable; some states allow private-sector comp time",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/overtime", "name": "WHD Overtime"},
        ),
    ),

    # ── Labor: leave ──────────────────────────────────────────────────────
    RegulationDef(
        key="state_family_leave",
        category="leave",
        name="State Family / Medical Leave Beyond FMLA",
        description="State-level family and medical leave laws providing broader coverage than FMLA (lower thresholds, more reasons)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active legislative area — states expanding eligibility and duration",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/fmla", "name": "WHD FMLA"},
            {"domain": "ncsl.org/labor-and-employment/state-family-and-medical-leave-laws", "name": "NCSL Family Leave"},
        ),
    ),
    RegulationDef(
        key="state_paid_family_leave",
        category="leave",
        name="State Paid Family Leave Insurance Programs",
        description="State-run paid family leave insurance (e.g., CA PFL, NY PFL, WA PFML); employee/employer contributions fund benefits",
        enforcing_agency="State agencies",
        state_variance="High",
        update_frequency="Rapidly expanding — new states enacting programs every session",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/state-family-and-medical-leave-laws", "name": "NCSL Family Leave"},
        ),
    ),
    RegulationDef(
        key="state_disability_insurance",
        category="leave",
        name="State Temporary Disability Insurance (CA SDI, NJ TDI, etc.)",
        description="State-mandated short-term disability insurance programs; wage replacement for non-work injuries/illness",
        enforcing_agency="State agencies",
        state_variance="High",
        update_frequency="Contribution rates and benefit amounts adjusted annually",
        authority_sources=(
            {"domain": "edd.ca.gov/disability", "name": "CA EDD Disability"},
        ),
    ),
    RegulationDef(
        key="pregnancy_disability_leave",
        category="leave",
        name="Pregnancy Disability Leave",
        description="Leave protections for pregnancy, childbirth, and related conditions; state laws often exceed federal FMLA/PDA",
        enforcing_agency="State / EEOC",
        state_variance="High",
        update_frequency="Active — states strengthening protections (PWFA 2023 federal, state expansions)",
        authority_sources=(
            {"domain": "eeoc.gov/pregnancy-discrimination", "name": "EEOC Pregnancy Discrimination"},
            {"domain": "dol.gov/agencies/whd/fmla", "name": "WHD FMLA"},
        ),
    ),
    RegulationDef(
        key="paid_sick_leave",
        category="leave",
        name="Paid Sick Leave Mandates",
        description="State and local laws requiring employers to provide paid sick leave; accrual rates, usage rules, and covered reasons",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Active — new states and cities enacting mandates annually",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/paid-sick-leave", "name": "NCSL Paid Sick Leave"},
        ),
    ),
    RegulationDef(
        key="bereavement_leave",
        category="leave",
        name="Bereavement / Funeral Leave",
        description="State laws requiring paid or unpaid bereavement leave for death of family members",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Expanding — CA, IL, OR, WA and others have enacted mandates",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="organ_donor_leave",
        category="leave",
        name="Organ / Bone Marrow Donor Leave",
        description="State laws providing leave for organ and bone marrow donation; typically 30-60 days for organ, 5 days for marrow",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Gradually expanding to more states",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="domestic_violence_leave",
        category="leave",
        name="Leave for Domestic Violence / Sexual Assault Victims",
        description="State laws providing leave for DV, sexual assault, or stalking victims; court appearances, safety planning, medical treatment",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Most states have some provision; expanding eligibility",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="jury_duty_leave",
        category="leave",
        name="Jury Duty Leave Protections",
        description="State laws protecting employees from discharge for jury service; some states require paid leave",
        enforcing_agency="State legislatures",
        state_variance="Low/None",
        update_frequency="Well-established in all states; rarely amended",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="military_leave",
        category="leave",
        name="Military / USERRA Leave",
        description="Federal USERRA and state military leave laws; reemployment rights, continuation of benefits",
        enforcing_agency="DOL / State labor agencies",
        state_variance="Low/None",
        update_frequency="Federal USERRA stable; state supplements change occasionally",
        authority_sources=(
            {"domain": "dol.gov/agencies/vets/programs/userra", "name": "DOL USERRA"},
        ),
    ),
    RegulationDef(
        key="voting_leave",
        category="leave",
        name="Time Off to Vote",
        description="State laws requiring employers to provide time off for voting; paid vs unpaid, notice requirements vary",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Most states have provisions; occasionally expanded around election cycles",
        authority_sources=(
            {"domain": "ncsl.org/elections-and-campaigns/voter-leave", "name": "NCSL Voter Leave"},
        ),
    ),
    RegulationDef(
        key="school_activity_leave",
        category="leave",
        name="School Activity / Parent Involvement Leave",
        description="State laws allowing employees to attend school activities for children; typically unpaid, limited hours per year",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Gradually expanding to more states",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="reproductive_loss_leave",
        category="leave",
        name="Reproductive Loss Leave",
        description="Leave for miscarriage, stillbirth, failed adoption/surrogacy, or unsuccessful fertility treatment (CA SB 848, others)",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Emerging area — CA enacted 2024; other states considering",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse", "name": "CA DIR"},
        ),
    ),
    RegulationDef(
        key="bone_marrow_donor_leave",
        category="leave",
        name="Bone Marrow Donation Leave",
        description="State laws providing specific leave for bone marrow donation; typically 5 working days paid",
        enforcing_agency="State legislatures",
        state_variance="Moderate",
        update_frequency="Gradually expanding to more states",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment", "name": "NCSL Labor"},
        ),
    ),
    RegulationDef(
        key="annual_leave_entitlement",
        category="leave",
        name="Statutory Annual Leave (International)",
        description="Nationally mandated minimum annual/vacation leave entitlement; varies widely by country",
        enforcing_agency="National government / Labor ministry",
        state_variance="Moderate",
        update_frequency="Typically stable; adjusted periodically by legislation",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="vacation_premium",
        category="leave",
        name="Vacation Premium Pay (Mexico 25%)",
        description="Mexico LFT requirement to pay 25% vacation premium on vacation days taken",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="Set by LFT; vacation days recently expanded (2023 reform)",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
    RegulationDef(
        key="statutory_maternity_leave",
        category="leave",
        name="Statutory Maternity Leave (International)",
        description="Nationally mandated maternity leave duration and pay; ILO recommends 14+ weeks",
        enforcing_agency="National government / ILO",
        state_variance="Moderate",
        update_frequency="Typically stable; varies widely by country (6 weeks to 1 year)",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="statutory_paternity_leave",
        category="leave",
        name="Statutory Paternity Leave (International)",
        description="Nationally mandated paternity leave for fathers/partners; emerging in many countries",
        enforcing_agency="National government",
        state_variance="Moderate",
        update_frequency="Expanding globally; duration varies from days to months",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="aguinaldo_christmas_bonus",
        category="leave",
        name="Christmas Bonus / 13th Month Pay (Mexico Aguinaldo)",
        description="Mexico LFT requirement to pay aguinaldo (minimum 15 days salary) by December 20 each year",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="Set by LFT; amount is statutory minimum",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
    RegulationDef(
        key="ptu_profit_sharing",
        category="leave",
        name="Worker Profit Sharing (Mexico PTU 10%)",
        description="Mexico LFT requirement for employers to distribute 10% of taxable profits to workers annually",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="2021 reform capped at 3 months salary or average of prior 3 years",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
    RegulationDef(
        key="severance_pay",
        category="leave",
        name="Statutory Severance Pay (International)",
        description="Nationally mandated severance pay upon termination; calculation based on tenure and salary",
        enforcing_agency="National labor courts / Labor ministry",
        state_variance="Moderate",
        update_frequency="Typically stable; varies widely by country and termination reason",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="seniority_premium",
        category="leave",
        name="Seniority Premium on Separation (Mexico)",
        description="Mexico LFT requirement to pay 12 days salary per year of service (capped at 2x minimum wage) upon voluntary separation after 15+ years",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="Set by LFT; rarely amended",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
    RegulationDef(
        key="shared_parental_leave",
        category="leave",
        name="Shared Parental Leave (UK)",
        description="UK system allowing parents to share up to 50 weeks leave and 37 weeks pay between them",
        enforcing_agency="HMRC / ACAS",
        state_variance="Moderate",
        update_frequency="Enacted 2015; rates reviewed annually",
        authority_sources=(
            {"domain": "gov.uk/shared-parental-leave-and-pay", "name": "UK Gov Shared Parental Leave"},
        ),
    ),
    RegulationDef(
        key="statutory_notice_period_employer",
        category="leave",
        name="Statutory Notice Period (International)",
        description="Minimum notice period an employer must give before termination; varies by tenure and country",
        enforcing_agency="National labor law / Labor courts",
        state_variance="Moderate",
        update_frequency="Typically stable; set by labor code",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="adoption_leave",
        category="leave",
        name="Statutory Adoption Leave (International)",
        description="Nationally mandated leave for adoptive parents; duration and pay vary by country",
        enforcing_agency="National government",
        state_variance="Moderate",
        update_frequency="Expanding globally; often aligned with maternity/paternity leave",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),

    # ── Labor: sick_leave ─────────────────────────────────────────────────
    RegulationDef(
        key="state_paid_sick_leave",
        category="sick_leave",
        name="State-Mandated Paid Sick Leave",
        description="State laws requiring employers to provide paid sick leave; accrual methods, frontloading options, eligible uses",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active — new states enacting mandates every legislative session",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/paid-sick-leave", "name": "NCSL Paid Sick Leave"},
        ),
    ),
    RegulationDef(
        key="accrual_and_usage_caps",
        category="sick_leave",
        name="Sick Leave Accrual Rates and Usage Caps",
        description="State/local rules on sick leave accrual rates (e.g., 1hr per 30hrs worked), annual usage caps, and carryover",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Updated with new sick leave mandates and amendments",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/paid-sick-leave", "name": "NCSL Paid Sick Leave"},
        ),
    ),
    RegulationDef(
        key="local_sick_leave",
        category="sick_leave",
        name="City / County Sick Leave Ordinances",
        description="Local sick leave ordinances that may exceed state requirements (e.g., San Francisco, NYC, Minneapolis)",
        enforcing_agency="Local government",
        state_variance="High",
        update_frequency="Active — new localities enacting ordinances regularly",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/paid-sick-leave", "name": "NCSL Paid Sick Leave"},
        ),
    ),
    RegulationDef(
        key="statutory_sick_leave",
        category="sick_leave",
        name="National Statutory Sick Pay (International)",
        description="Nationally mandated sick pay or sickness insurance; employer-paid or government-funded, varies by country",
        enforcing_agency="National government",
        state_variance="Moderate",
        update_frequency="Typically stable; rates adjusted periodically",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="imss_sick_leave",
        category="sick_leave",
        name="IMSS Social Security Sick Leave (Mexico)",
        description="Mexico IMSS-covered sick leave; employer pays first 3 days, IMSS pays 60% from day 4 for up to 52 weeks",
        enforcing_agency="IMSS",
        state_variance="Moderate",
        update_frequency="IMSS contribution rates reviewed annually",
        authority_sources=(
            {"domain": "gob.mx/imss", "name": "IMSS Mexico"},
        ),
    ),

    # ── Labor: meal_breaks ────────────────────────────────────────────────
    RegulationDef(
        key="meal_break",
        category="meal_breaks",
        name="Meal / Lunch Break Requirements",
        description="State-mandated meal periods; timing, duration, duty-free requirements (e.g., CA 30-min by 5th hour)",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Changes with state labor code amendments; active litigation area",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/breaks", "name": "WHD Break Time"},
            {"domain": "dir.ca.gov/dlse/meal_breaks.htm", "name": "CA DIR Meal Breaks"},
        ),
    ),
    RegulationDef(
        key="rest_break",
        category="meal_breaks",
        name="Rest / Coffee Break Requirements",
        description="State-mandated paid rest breaks; typically 10 minutes per 4 hours worked (CA, CO, WA, others)",
        enforcing_agency="WHD / State labor agencies",
        state_variance="High",
        update_frequency="Changes with state labor code amendments",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/breaks", "name": "WHD Break Time"},
        ),
    ),
    RegulationDef(
        key="lactation_break",
        category="meal_breaks",
        name="Lactation / Nursing Break Requirements",
        description="Federal PUMP Act and state laws requiring break time and private space for nursing mothers to express milk",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="Federal PUMP Act enacted 2022; states continue expanding protections",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/pump-at-work", "name": "WHD PUMP Act"},
        ),
    ),
    RegulationDef(
        key="on_duty_meal_agreement",
        category="meal_breaks",
        name="On-Duty Meal Period Agreements",
        description="Rules for valid on-duty meal period agreements when nature of work prevents off-duty breaks (CA, others)",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Shaped by case law and IWC wage orders",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/meal_breaks.htm", "name": "CA DIR Meal Breaks"},
        ),
    ),
    RegulationDef(
        key="healthcare_meal_waiver",
        category="meal_breaks",
        name="Healthcare Industry Meal Break Waivers",
        description="Special meal break waiver provisions for healthcare workers (e.g., CA healthcare meal period waiver)",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Active litigation area; shaped by case law",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/meal_breaks.htm", "name": "CA DIR Meal Breaks"},
        ),
    ),
    RegulationDef(
        key="missed_break_penalty",
        category="meal_breaks",
        name="Penalty Pay for Missed Breaks (CA Premium Pay)",
        description="One hour of pay at regular rate for each missed meal or rest break (CA Labor Code 226.7, similar in other states)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active enforcement and litigation area",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/meal_breaks.htm", "name": "CA DIR Meal Breaks"},
        ),
    ),

    # ── Labor: pay_frequency ──────────────────────────────────────────────
    RegulationDef(
        key="standard_pay_frequency",
        category="pay_frequency",
        name="Required Pay Frequency (Weekly, Biweekly, etc.)",
        description="State laws mandating minimum frequency of wage payments; varies from weekly to monthly by state",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Rarely changed; well-established state rules",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="exempt_monthly_pay",
        category="pay_frequency",
        name="Exempt Employee Monthly Pay Option",
        description="State rules allowing or restricting monthly pay for exempt employees",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Rarely changed; well-established state rules",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="payday_posting",
        category="pay_frequency",
        name="Payday Posting / Notification Requirements",
        description="State requirements to post or notify employees of regular payday schedule",
        enforcing_agency="State labor agencies",
        state_variance="Low/None",
        update_frequency="Well-established; rarely amended",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="wage_notice",
        category="pay_frequency",
        name="Wage Theft Prevention Notice Requirements",
        description="State laws requiring written notice of pay rate, pay date, employer info at hire and upon changes (e.g., CA, NY)",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Expanding — more states enacting wage theft prevention acts",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/wage_theft_prevention.htm", "name": "CA DIR Wage Theft Prevention"},
        ),
    ),

    # ── Labor: final_pay ──────────────────────────────────────────────────
    RegulationDef(
        key="final_pay_termination",
        category="final_pay",
        name="Final Pay Timing — Involuntary Termination",
        description="State-mandated timeline for paying final wages after involuntary termination (immediate in CA, 72hrs in others)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rarely changed; well-established state rules with active enforcement",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="final_pay_resignation",
        category="final_pay",
        name="Final Pay Timing — Voluntary Resignation",
        description="State-mandated timeline for paying final wages after voluntary resignation (72hrs in CA, next payday in many states)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rarely changed; well-established state rules",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="final_pay_layoff",
        category="final_pay",
        name="Final Pay Timing — Layoff / Reduction in Force",
        description="State rules for final pay timing in layoff/RIF situations; may differ from standard termination timelines",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rarely changed; well-established state rules",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/state/payday", "name": "WHD Payday Requirements"},
        ),
    ),
    RegulationDef(
        key="waiting_time_penalty",
        category="final_pay",
        name="Penalty for Late Final Pay (CA Waiting Time Penalties)",
        description="Penalty wages for failure to timely pay final wages; CA imposes up to 30 days continued wages",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Active enforcement area; penalty provisions rarely change but litigation is ongoing",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/final_pay.htm", "name": "CA DIR Final Pay"},
        ),
    ),
    RegulationDef(
        key="finiquito",
        category="final_pay",
        name="Voluntary Separation Settlement (Mexico Finiquito)",
        description="Mexico LFT settlement for voluntary resignation; includes proportional aguinaldo, vacation, vacation premium, and seniority premium if applicable",
        enforcing_agency="STPS / Conciliation centers",
        state_variance="Moderate",
        update_frequency="Set by LFT; calculation methodology is stable",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
    RegulationDef(
        key="liquidacion",
        category="final_pay",
        name="Involuntary Termination Settlement (Mexico Liquidacion)",
        description="Mexico LFT settlement for unjustified dismissal; includes 3 months salary, 20 days per year of service, plus finiquito components",
        enforcing_agency="Labor courts",
        state_variance="Moderate",
        update_frequency="Set by LFT; subject to labor court interpretation",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),

    # ── Labor: minor_work_permit ──────────────────────────────────────────
    RegulationDef(
        key="work_permit",
        category="minor_work_permit",
        name="Youth Employment Work Permit / Certificate",
        description="State requirements for minors to obtain work permits or employment certificates before starting work",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Well-established; occasionally updated",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/child-labor", "name": "WHD Child Labor"},
        ),
    ),
    RegulationDef(
        key="hour_limits_14_15",
        category="minor_work_permit",
        name="Working Hour Limits Ages 14-15",
        description="Federal and state limits on hours and times of day for 14-15 year old workers (FLSA: 3hr school days, 8hr non-school)",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="Federal limits stable; states may impose stricter limits",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/child-labor", "name": "WHD Child Labor"},
        ),
    ),
    RegulationDef(
        key="hour_limits_16_17",
        category="minor_work_permit",
        name="Working Hour Limits Ages 16-17",
        description="State-level limits on hours and times for 16-17 year old workers; FLSA has no federal hour limits for this age group",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="States may impose restrictions beyond federal minimums",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/child-labor", "name": "WHD Child Labor"},
        ),
    ),
    RegulationDef(
        key="prohibited_occupations",
        category="minor_work_permit",
        name="Hazardous Occupations for Minors",
        description="Federal HO orders and state laws prohibiting minors from hazardous occupations (e.g., power machinery, mining, roofing)",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Moderate",
        update_frequency="Federal HO orders updated periodically; states may add restrictions",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/child-labor/hazardous", "name": "WHD Hazardous Occupations"},
        ),
    ),
    RegulationDef(
        key="entertainment_permits",
        category="minor_work_permit",
        name="Entertainment Industry Permits for Minors",
        description="Special permits and protections for minors in entertainment (Coogan Act trusts, set tutors, work hours)",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Most active in CA, NY, GA; updated as industry evolves",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse/child_labor.htm", "name": "CA DIR Child Labor"},
        ),
    ),
    RegulationDef(
        key="recordkeeping",
        category="minor_work_permit",
        name="Youth Employment Recordkeeping Requirements",
        description="Employer obligations to maintain records of minor employees including permits, hours worked, and age verification",
        enforcing_agency="WHD / State labor agencies",
        state_variance="Low/None",
        update_frequency="Well-established; rarely amended",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/child-labor", "name": "WHD Child Labor"},
        ),
    ),

    # ── Labor: scheduling_reporting ───────────────────────────────────────
    RegulationDef(
        key="reporting_time_pay",
        category="scheduling_reporting",
        name="Reporting / Show-Up Time Pay",
        description="State laws requiring minimum pay when employees report to work but are sent home early (e.g., CA: half of scheduled shift)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rarely changed; well-established in states that have it",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse", "name": "CA DIR"},
        ),
    ),
    RegulationDef(
        key="predictive_scheduling",
        category="scheduling_reporting",
        name="Fair Workweek / Predictive Scheduling",
        description="Laws requiring advance notice of schedules, predictability pay for changes (e.g., OR, NYC, Chicago, Seattle)",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Active legislative area — new jurisdictions enacting laws",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/state-predictive-scheduling-laws", "name": "NCSL Predictive Scheduling"},
        ),
    ),
    RegulationDef(
        key="split_shift_premium",
        category="scheduling_reporting",
        name="Split Shift Premium Pay",
        description="Premium pay for split shifts where employee has unpaid break exceeding one hour (e.g., CA, NY)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rarely changed; established by IWC wage orders (CA)",
        authority_sources=(
            {"domain": "dir.ca.gov/dlse", "name": "CA DIR"},
        ),
    ),
    RegulationDef(
        key="on_call_pay",
        category="scheduling_reporting",
        name="On-Call Compensation Requirements",
        description="State rules for compensating on-call time; distinction between restricted and unrestricted on-call",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Shaped primarily by case law and administrative interpretation",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/overtime", "name": "WHD Overtime"},
        ),
    ),
    RegulationDef(
        key="spread_of_hours",
        category="scheduling_reporting",
        name="Spread of Hours Premium (NY)",
        description="NY requirement for extra hour of pay when workday spread exceeds 10 hours (NY Minimum Wage Order)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Specific to NY; rarely amended",
        authority_sources=(
            {"domain": "dol.ny.gov/minimum-wage", "name": "NY DOL Minimum Wage"},
        ),
    ),
    RegulationDef(
        key="maximum_working_hours",
        category="scheduling_reporting",
        name="Maximum Daily / Weekly Working Hours (International)",
        description="Nationally mandated maximum working hours per day/week; ILO standard is 48hrs/week",
        enforcing_agency="National government / Labor ministry",
        state_variance="Moderate",
        update_frequency="Typically stable; set by labor code",
        authority_sources=(
            {"domain": "ilo.org/global/topics/working-time", "name": "ILO Working Time"},
        ),
    ),
    RegulationDef(
        key="sunday_premium",
        category="scheduling_reporting",
        name="Sunday Premium Pay (Mexico 25%)",
        description="Mexico LFT requirement to pay 25% premium for work on Sundays (prima dominical)",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="Set by LFT; stable statutory requirement",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),

    # ── Labor: workplace_safety ───────────────────────────────────────────
    RegulationDef(
        key="osha_general_duty",
        category="workplace_safety",
        name="OSHA General Duty Clause (Section 5(a)(1))",
        description="Employer obligation to furnish a workplace free from recognized hazards causing or likely to cause death or serious harm",
        enforcing_agency="OSHA / State plan states",
        state_variance="Moderate",
        update_frequency="Clause itself is stable; OSHA enforcement guidance updates regularly",
        authority_sources=(
            {"domain": "osha.gov/laws-regs/oshact/section5-duties", "name": "OSHA General Duty Clause"},
        ),
    ),
    RegulationDef(
        key="injury_illness_recordkeeping",
        category="workplace_safety",
        name="OSHA 300/300A Injury and Illness Recordkeeping",
        description="Requirements to maintain OSHA 300 Log, 300A Summary, and 301 forms; electronic submission for certain employers",
        enforcing_agency="OSHA",
        state_variance="Moderate",
        update_frequency="Reporting thresholds updated periodically; electronic submission expanded 2024",
        authority_sources=(
            {"domain": "osha.gov/recordkeeping", "name": "OSHA Recordkeeping"},
        ),
    ),
    RegulationDef(
        key="heat_illness_prevention",
        category="workplace_safety",
        name="Heat Illness Prevention Programs",
        description="Requirements for heat illness prevention: water, shade, rest breaks, acclimatization, emergency procedures (CA, OSHA proposed federal rule)",
        enforcing_agency="OSHA / State plan states",
        state_variance="High",
        update_frequency="Active — federal OSHA rulemaking in progress; CA/WA/OR have existing standards",
        authority_sources=(
            {"domain": "osha.gov/heat-exposure", "name": "OSHA Heat Exposure"},
        ),
    ),
    RegulationDef(
        key="workplace_violence_prevention",
        category="workplace_safety",
        name="Workplace Violence Prevention Plans",
        description="Requirements for written workplace violence prevention plans, training, incident logging (CA SB 553, healthcare-specific federal/state rules)",
        enforcing_agency="OSHA / State plan states (CA SB 553)",
        state_variance="Moderate",
        update_frequency="Active — CA SB 553 effective 2024; federal OSHA considering rule",
        authority_sources=(
            {"domain": "osha.gov/workplace-violence", "name": "OSHA Workplace Violence"},
            {"domain": "dir.ca.gov/dosh/workplace-violence", "name": "CA DOSH Workplace Violence"},
        ),
    ),
    RegulationDef(
        key="hazard_communication",
        category="workplace_safety",
        name="HazCom / GHS Right-to-Know",
        description="OSHA Hazard Communication Standard (29 CFR 1910.1200); GHS-aligned labeling, SDSs, training for hazardous chemicals",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="HCS 2012 aligned with GHS; periodic updates to chemical classification",
        authority_sources=(
            {"domain": "osha.gov/hazcom", "name": "OSHA HazCom"},
        ),
    ),
    RegulationDef(
        key="stps_nom_standards",
        category="workplace_safety",
        name="STPS NOM Occupational Safety Standards (Mexico)",
        description="Mexico's official occupational safety and health standards (NOMs) issued by STPS covering ergonomics, fire, electrical, noise, and more",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="NOMs updated periodically; approximately 40+ active safety NOMs",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),

    # ── Labor: workers_comp ───────────────────────────────────────────────
    RegulationDef(
        key="mandatory_coverage",
        category="workers_comp",
        name="Mandatory Workers' Compensation Coverage",
        description="State requirements for employers to carry workers' comp insurance; coverage thresholds, exemptions, monopolistic state funds",
        enforcing_agency="State WC boards",
        state_variance="High",
        update_frequency="Coverage requirements updated periodically; rates adjusted annually",
        authority_sources=(
            {"domain": "dol.gov/general/topic/workcomp", "name": "DOL Workers' Comp"},
        ),
    ),
    RegulationDef(
        key="claim_filing",
        category="workers_comp",
        name="Workers' Comp Claim Filing Procedures / Deadlines",
        description="State-specific claim filing procedures, deadlines, employer reporting obligations, and dispute resolution",
        enforcing_agency="State WC boards",
        state_variance="Moderate",
        update_frequency="Procedures updated periodically; filing deadlines are generally stable",
        authority_sources=(
            {"domain": "dol.gov/general/topic/workcomp", "name": "DOL Workers' Comp"},
        ),
    ),
    RegulationDef(
        key="return_to_work",
        category="workers_comp",
        name="Return-to-Work Programs",
        description="State requirements or incentives for return-to-work programs; light duty, modified work, vocational rehabilitation",
        enforcing_agency="State WC boards",
        state_variance="Moderate",
        update_frequency="Gradually expanding; many states incentivize RTW programs",
        authority_sources=(
            {"domain": "dol.gov/general/topic/workcomp", "name": "DOL Workers' Comp"},
        ),
    ),
    RegulationDef(
        key="anti_retaliation",
        category="workers_comp",
        name="Anti-Retaliation for Workers' Comp Claims",
        description="State laws prohibiting employer retaliation against employees for filing workers' comp claims",
        enforcing_agency="State WC boards",
        state_variance="Moderate",
        update_frequency="Well-established in all states; strengthened periodically",
        authority_sources=(
            {"domain": "dol.gov/general/topic/workcomp", "name": "DOL Workers' Comp"},
        ),
    ),
    RegulationDef(
        key="posting_requirements",
        category="workers_comp",
        name="Workers' Comp Posting Requirements",
        description="State requirements to post workers' comp insurance information in the workplace; carrier details, claim filing instructions",
        enforcing_agency="State WC boards",
        state_variance="Low/None",
        update_frequency="Well-established; rarely amended",
        authority_sources=(
            {"domain": "dol.gov/general/topic/workcomp", "name": "DOL Workers' Comp"},
        ),
    ),
    RegulationDef(
        key="social_insurance_employer",
        category="workers_comp",
        name="Employer Social Insurance Contributions (International)",
        description="Mandatory employer contributions to national social insurance / social security systems covering health, pension, disability",
        enforcing_agency="National social security authority",
        state_variance="Moderate",
        update_frequency="Contribution rates typically reviewed annually",
        authority_sources=(
            {"domain": "ilo.org/global/topics/social-security", "name": "ILO Social Security"},
        ),
    ),
    RegulationDef(
        key="social_insurance_employee",
        category="workers_comp",
        name="Employee Social Insurance Deductions (International)",
        description="Mandatory employee deductions for national social insurance / social security; withheld from wages by employer",
        enforcing_agency="National social security authority",
        state_variance="Moderate",
        update_frequency="Contribution rates typically reviewed annually",
        authority_sources=(
            {"domain": "ilo.org/global/topics/social-security", "name": "ILO Social Security"},
        ),
    ),
    RegulationDef(
        key="imss_employer_contribution",
        category="workers_comp",
        name="IMSS Employer Contribution Rates (Mexico)",
        description="Mexico IMSS employer contribution rates covering disability, maternity, retirement, work risk, daycare; based on employee salary",
        enforcing_agency="IMSS",
        state_variance="High",
        update_frequency="Rates adjusted annually; 2023 reform increasing pension contributions through 2030",
        authority_sources=(
            {"domain": "gob.mx/imss", "name": "IMSS Mexico"},
        ),
    ),
    RegulationDef(
        key="infonavit_contribution",
        category="workers_comp",
        name="INFONAVIT Housing Fund Contribution (Mexico)",
        description="Mexico employer contribution of 5% of employee salary to INFONAVIT workers' housing fund",
        enforcing_agency="INFONAVIT",
        state_variance="Moderate",
        update_frequency="Rate is statutory (5%); rarely changed",
        authority_sources=(
            {"domain": "gob.mx/infonavit", "name": "INFONAVIT Mexico"},
        ),
    ),
    RegulationDef(
        key="sar_retirement_contribution",
        category="workers_comp",
        name="SAR Retirement Savings Contribution (Mexico)",
        description="Mexico employer contributions to SAR (Sistema de Ahorro para el Retiro) retirement savings system managed by AFOREs",
        enforcing_agency="CONSAR",
        state_variance="Moderate",
        update_frequency="Contribution rates increasing under 2023 pension reform through 2030",
        authority_sources=(
            {"domain": "gob.mx/consar", "name": "CONSAR Mexico"},
        ),
    ),
    RegulationDef(
        key="uk_auto_enrolment_pension",
        category="workers_comp",
        name="UK Auto-Enrolment Pension (Workplace Pension)",
        description="UK mandatory workplace pension auto-enrolment; minimum 8% total contribution (3% employer, 5% employee)",
        enforcing_agency="The Pensions Regulator",
        state_variance="High",
        update_frequency="Thresholds reviewed annually; contribution rates last changed 2019",
        authority_sources=(
            {"domain": "thepensionsregulator.gov.uk", "name": "The Pensions Regulator"},
        ),
    ),
    RegulationDef(
        key="cpf_employer_contribution",
        category="workers_comp",
        name="CPF Employer Contribution Rates (Singapore)",
        description="Singapore Central Provident Fund employer contribution rates (up to 17%); covers retirement, healthcare, housing",
        enforcing_agency="CPF Board",
        state_variance="High",
        update_frequency="Rates reviewed in annual budget; age-tiered contribution tables",
        authority_sources=(
            {"domain": "cpf.gov.sg", "name": "CPF Board Singapore"},
        ),
    ),
    RegulationDef(
        key="foreign_worker_levy",
        category="workers_comp",
        name="Foreign Worker Levy (Singapore)",
        description="Singapore levy on employers for hiring foreign workers; rates vary by sector, skill level, and dependency ratio",
        enforcing_agency="MOM Singapore",
        state_variance="High",
        update_frequency="Rates adjusted in annual budget; sector-specific changes frequent",
        authority_sources=(
            {"domain": "mom.gov.sg", "name": "MOM Singapore"},
        ),
    ),

    # ── Labor: anti_discrimination ────────────────────────────────────────
    RegulationDef(
        key="protected_classes",
        category="anti_discrimination",
        name="State Protected Classes Beyond Federal",
        description="State laws adding protected classes beyond Title VII (e.g., sexual orientation, gender identity, political activity, credit history)",
        enforcing_agency="State civil rights agencies",
        state_variance="High",
        update_frequency="Active legislative area — states adding protections annually",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/discrimination-and-harassment", "name": "NCSL Discrimination"},
        ),
    ),
    RegulationDef(
        key="pay_transparency",
        category="anti_discrimination",
        name="Pay Transparency / Range Disclosure",
        description="State/local laws requiring employers to disclose salary ranges in job postings or upon request (CO, CA, NY, WA, others)",
        enforcing_agency="State labor agencies",
        state_variance="High",
        update_frequency="Rapidly expanding — new states enacting every session",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/pay-equity", "name": "NCSL Pay Equity"},
        ),
    ),
    RegulationDef(
        key="salary_history_ban",
        category="anti_discrimination",
        name="Salary History Inquiry Ban",
        description="State/local laws prohibiting employers from asking about prior salary history during hiring",
        enforcing_agency="State / Local government",
        state_variance="High",
        update_frequency="Active — new jurisdictions enacting bans regularly",
        authority_sources=(
            {"domain": "ncsl.org/labor-and-employment/pay-equity", "name": "NCSL Pay Equity"},
        ),
    ),
    RegulationDef(
        key="harassment_prevention_training",
        category="anti_discrimination",
        name="Sexual Harassment Prevention Training Mandates",
        description="State laws requiring employers to provide anti-harassment training (e.g., CA SB 1343: 2hr supervisors, 1hr all; NY 1hr annual)",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Active — new states enacting mandates; training content updated regularly",
        authority_sources=(
            {"domain": "dfeh.ca.gov/shpt", "name": "CA CRD Harassment Training"},
        ),
    ),
    RegulationDef(
        key="reasonable_accommodation",
        category="anti_discrimination",
        name="Reasonable Accommodation Requirements",
        description="Federal ADA and state laws requiring employers to provide reasonable accommodations for disabilities, pregnancy, and religion",
        enforcing_agency="EEOC / State civil rights agencies",
        state_variance="Moderate",
        update_frequency="EEOC guidance updated periodically; PWFA (2023) expanded pregnancy accommodations",
        authority_sources=(
            {"domain": "eeoc.gov/laws/guidance", "name": "EEOC Guidance"},
        ),
    ),
    RegulationDef(
        key="whistleblower_protection",
        category="anti_discrimination",
        name="Whistleblower / Retaliation Protections",
        description="State laws protecting employees from retaliation for reporting violations of law, safety hazards, or engaging in protected activity",
        enforcing_agency="State labor agencies",
        state_variance="Moderate",
        update_frequency="Expanding protections; many states strengthening anti-retaliation provisions",
        authority_sources=(
            {"domain": "osha.gov/whistleblower", "name": "OSHA Whistleblower"},
        ),
    ),
    RegulationDef(
        key="nom_035_psychosocial_risk",
        category="anti_discrimination",
        name="NOM-035 Psychosocial Risk Factors (Mexico)",
        description="Mexico STPS standard requiring employers to identify, analyze, and prevent psychosocial risk factors and workplace violence",
        enforcing_agency="STPS",
        state_variance="Moderate",
        update_frequency="Enacted 2018, mandatory since 2020; enforcement expanding",
        authority_sources=(
            {"domain": "gob.mx/stps", "name": "STPS Mexico"},
        ),
    ),
]
