from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_MANUFACTURING: List[RegulationDef] = [

    # ── Manufacturing: environmental_compliance ──────────────────────────────
    RegulationDef(
        key="air_quality_permit", category="environmental_compliance",
        name="Air Quality Operating Permit",
        description="Clean Air Act Title V operating permits for stationary sources of air pollution",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="State implementation plans updated periodically; EPA NAAQS reviewed every 5 years",
        authority_sources=({"domain": "epa.gov/caa-permitting", "name": "EPA"},),
    ),
    RegulationDef(
        key="neshap_compliance", category="environmental_compliance",
        name="NESHAP Compliance",
        description="National Emission Standards for Hazardous Air Pollutants under Clean Air Act Section 112",
        enforcing_agency="EPA",
        state_variance="Moderate",
        update_frequency="NESHAP standards reviewed and updated by source category on EPA schedule",
        authority_sources=({"domain": "epa.gov", "name": "EPA"},),
    ),
    RegulationDef(
        key="wastewater_discharge", category="environmental_compliance",
        name="Wastewater Discharge Permit",
        description="Clean Water Act NPDES permits for industrial and municipal wastewater discharge",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="Permit terms typically 5 years; effluent guidelines updated by industry sector",
        authority_sources=({"domain": "epa.gov/npdes", "name": "EPA"},),
    ),
    RegulationDef(
        key="hazardous_waste_rcra", category="environmental_compliance",
        name="Hazardous Waste Management (RCRA)",
        description="Resource Conservation and Recovery Act requirements for hazardous waste generation, handling, and disposal",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="RCRA regulations updated periodically; state authorization programs vary",
        authority_sources=({"domain": "epa.gov/rcra", "name": "EPA"},),
    ),
    RegulationDef(
        key="stormwater_permit", category="environmental_compliance",
        name="Stormwater Discharge Permit",
        description="Industrial and construction stormwater discharge permits under the Clean Water Act",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="Multi-sector general permit reissued every 5 years; state permits vary",
        authority_sources=({"domain": "epa.gov/npdes/stormwater", "name": "EPA"},),
    ),
    RegulationDef(
        key="emissions_reporting", category="environmental_compliance",
        name="Emissions Reporting Requirements",
        description="Greenhouse gas and criteria pollutant reporting requirements under EPA programs",
        enforcing_agency="EPA/State",
        state_variance="Moderate",
        update_frequency="EPA GHG reporting rule updated periodically; state programs vary",
        authority_sources=({"domain": "epa.gov/ghgreporting", "name": "EPA"},),
    ),
    RegulationDef(
        key="tsca_toxic_substances", category="environmental_compliance",
        name="TSCA Toxic Substances Control Act",
        description="Chemical substance inventory, risk evaluation, and regulation under TSCA (as amended by Lautenberg Act)",
        enforcing_agency="EPA",
        state_variance="Moderate",
        update_frequency="EPA risk evaluations ongoing; TSCA inventory updated continuously",
        authority_sources=({"domain": "epa.gov/tsca-inventory", "name": "EPA"},),
    ),
    RegulationDef(
        key="cercla_superfund_liability", category="environmental_compliance",
        name="CERCLA/Superfund Liability",
        description="Hazardous waste site cleanup liability and cost recovery under CERCLA/Superfund",
        enforcing_agency="EPA",
        state_variance="Moderate",
        update_frequency="NPL sites updated periodically; CERCLA liability framework stable",
        authority_sources=({"domain": "epa.gov/superfund", "name": "EPA"},),
    ),
    RegulationDef(
        key="clean_air_act_title_v", category="environmental_compliance",
        name="Clean Air Act Title V Permitting",
        description="Major source operating permit program under Clean Air Act Title V",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="Title V permits renewed every 5 years; state SIPs updated periodically",
        authority_sources=({"domain": "epa.gov/caa-permitting", "name": "EPA"},),
    ),
    RegulationDef(
        key="epa_risk_management_program", category="environmental_compliance",
        name="EPA Risk Management Program (RMP)",
        description="Chemical accident prevention requirements under 40 CFR Part 68 for facilities with regulated substances",
        enforcing_agency="EPA",
        state_variance="Moderate",
        update_frequency="RMP rule amended 2024; risk management plans resubmitted every 5 years",
        authority_sources=({"domain": "epa.gov/rmp", "name": "EPA"},),
    ),
    RegulationDef(
        key="epcra_tri_reporting", category="environmental_compliance",
        name="EPCRA/TRI Reporting",
        description="Toxics Release Inventory annual reporting of chemical releases under EPCRA Section 313",
        enforcing_agency="EPA",
        state_variance="Moderate",
        update_frequency="TRI chemical list updated periodically; reporting thresholds reviewed by EPA",
        authority_sources=({"domain": "epa.gov/toxics-release-inventory-tri-program", "name": "EPA"},),
    ),
    RegulationDef(
        key="rcra_hazardous_waste", category="environmental_compliance",
        name="RCRA Hazardous Waste Generator Requirements",
        description="Generator category determination, hazardous waste manifest, and storage time limit rules",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="Generator improvements rule 2016; state adoption ongoing",
        authority_sources=({"domain": "epa.gov/rcra", "name": "EPA"},),
    ),
    RegulationDef(
        key="clean_water_act_npdes", category="environmental_compliance",
        name="Clean Water Act NPDES Permitting",
        description="National Pollutant Discharge Elimination System permits for point source discharges",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="NPDES permits issued for 5-year terms; effluent limitations updated by sector",
        authority_sources=({"domain": "epa.gov/npdes", "name": "EPA"},),
    ),
    RegulationDef(
        key="spcc_oil_spill_prevention", category="environmental_compliance",
        name="SPCC Oil Spill Prevention",
        description="Spill Prevention, Control, and Countermeasure plans for facilities storing oil",
        enforcing_agency="EPA",
        state_variance="Low/None",
        update_frequency="SPCC rule amendments infrequent; plans reviewed and updated every 5 years",
        authority_sources=({"domain": "epa.gov/oil-spills-prevention-and-preparedness-regulations", "name": "EPA"},),
    ),

    # ── Manufacturing: chemical_safety ────────────────────────────────────────
    RegulationDef(
        key="hazcom_ghs", category="chemical_safety",
        name="Hazard Communication / GHS",
        description="Globally Harmonized System for chemical classification, labeling, and safety data sheets",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA HazCom standard updated to align with GHS revisions; last major update 2012",
        authority_sources=({"domain": "osha.gov/hazcom", "name": "OSHA"},),
    ),
    RegulationDef(
        key="chemical_inventory_reporting", category="chemical_safety",
        name="Chemical Inventory Reporting",
        description="EPCRA Tier II chemical inventory reporting to local emergency planning committees",
        enforcing_agency="EPA/State",
        state_variance="Moderate",
        update_frequency="Annual reporting requirement; thresholds and forms updated periodically",
        authority_sources=({"domain": "epa.gov", "name": "EPA"},),
    ),
    RegulationDef(
        key="right_to_know", category="chemical_safety",
        name="Right-to-Know Laws",
        description="Employee and community right-to-know about chemical hazards and exposure information",
        enforcing_agency="OSHA/State",
        state_variance="High",
        update_frequency="Federal HazCom stable; state right-to-know laws vary and update independently",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="sds_management", category="chemical_safety",
        name="Safety Data Sheet Management",
        description="Safety data sheet creation, distribution, maintenance, and accessibility requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="SDS format aligned with GHS; OSHA requirements stable",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="hazardous_substance_storage", category="chemical_safety",
        name="Hazardous Substance Storage Requirements",
        description="Chemical storage, secondary containment, and segregation requirements for hazardous substances",
        enforcing_agency="EPA/OSHA/State",
        state_variance="High",
        update_frequency="Federal requirements stable; state fire codes and storage rules vary",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="pfas_restrictions", category="chemical_safety",
        name="PFAS Restrictions",
        description="Per- and polyfluoroalkyl substance restrictions, reporting, and cleanup requirements",
        enforcing_agency="EPA/State",
        state_variance="High",
        update_frequency="Active rulemaking at federal and state levels; EPA PFAS action plan evolving rapidly",
        authority_sources=({"domain": "epa.gov/pfas", "name": "EPA"},),
    ),

    # ── Manufacturing: machine_safety ─────────────────────────────────────────
    RegulationDef(
        key="lockout_tagout", category="machine_safety",
        name="Lockout/Tagout (LOTO)",
        description="Control of hazardous energy procedures for servicing and maintenance (29 CFR 1910.147)",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA standard stable since 1989; interpretation letters issued periodically",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="machine_guarding", category="machine_safety",
        name="Machine Guarding",
        description="Point-of-operation guards and power transmission apparatus guarding requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA machine guarding standards stable; ANSI/NFPA consensus standards updated periodically",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="powered_industrial_trucks", category="machine_safety",
        name="Powered Industrial Trucks",
        description="Forklift operator training, certification, and safe operation requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA standard stable; operator evaluation required every 3 years",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="crane_hoist_safety", category="machine_safety",
        name="Crane & Hoist Safety",
        description="Crane operation, inspection, and operator certification requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA crane standards updated 2010 (construction); general industry standards stable",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="electrical_safety", category="machine_safety",
        name="Electrical Safety",
        description="NFPA 70E arc flash protection and electrical work practices for worker safety",
        enforcing_agency="OSHA/NFPA",
        state_variance="Low/None",
        update_frequency="NFPA 70E updated every 3 years; OSHA electrical standards stable",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="confined_space", category="machine_safety",
        name="Confined Space Entry",
        description="Permit-required confined space entry program requirements (29 CFR 1910.146)",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA standard stable; construction confined space rule added 2015",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),

    # ── Manufacturing: industrial_hygiene ─────────────────────────────────────
    RegulationDef(
        key="noise_exposure", category="industrial_hygiene",
        name="Noise Exposure / Hearing Conservation",
        description="Occupational noise exposure limits, monitoring, and hearing conservation program requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA noise standards stable since 1983; audiometric testing requirements unchanged",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="respiratory_protection", category="industrial_hygiene",
        name="Respiratory Protection Program",
        description="Respirator selection, fit testing, medical evaluation, and program administration requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA respiratory protection standard stable; NIOSH approval schedules updated periodically",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="heat_illness_prevention", category="industrial_hygiene",
        name="Industrial Heat Illness Prevention",
        description="Heat stress management, acclimatization, and prevention programs in industrial settings",
        enforcing_agency="OSHA/State",
        state_variance="High",
        update_frequency="Federal OSHA rulemaking in progress; CA, WA, OR, and other states have existing rules",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="permissible_exposure_limits", category="industrial_hygiene",
        name="Permissible Exposure Limits (PELs)",
        description="OSHA chemical and physical agent workplace exposure limits",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="Federal PELs largely unchanged since 1971; state plans (CA) may adopt stricter limits",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="personal_protective_equipment", category="industrial_hygiene",
        name="Personal Protective Equipment (PPE)",
        description="PPE hazard assessment, selection, provision, and training requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA PPE standards stable; ANSI consensus standards updated periodically",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="ergonomics", category="industrial_hygiene",
        name="Ergonomics Programs",
        description="Musculoskeletal disorder prevention through workplace ergonomics programs",
        enforcing_agency="OSHA/State (CA)",
        state_variance="Moderate",
        update_frequency="No federal ergonomics standard; CA has mandatory ergonomics regulation",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),

    # ── Manufacturing: process_safety ─────────────────────────────────────────
    RegulationDef(
        key="osha_psm", category="process_safety",
        name="OSHA Process Safety Management",
        description="Process safety management for highly hazardous chemicals (29 CFR 1910.119)",
        enforcing_agency="OSHA",
        state_variance="Moderate",
        update_frequency="Federal PSM standard stable; CA has stricter CalARP/PSM requirements",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="process_hazard_analysis", category="process_safety",
        name="Process Hazard Analysis",
        description="PHA methodologies (HAZOP, What-If, FMEA) and revalidation requirements for covered processes",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="PHA revalidation required every 5 years under PSM",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="management_of_change", category="process_safety",
        name="Management of Change (MOC)",
        description="Change control procedures for process modifications to prevent incidents",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="MOC requirements stable under PSM; best practices evolve with industry standards",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="pre_startup_review", category="process_safety",
        name="Pre-Startup Safety Review",
        description="Safety review requirements before startup of new or modified process equipment",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="PSSR requirements stable under PSM standard",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="mechanical_integrity", category="process_safety",
        name="Mechanical Integrity",
        description="Equipment inspection, testing, preventive maintenance, and quality assurance for process equipment",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="MI requirements stable under PSM; API/ASME inspection standards updated periodically",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),
    RegulationDef(
        key="emergency_action_plan", category="process_safety",
        name="Emergency Action Plan",
        description="Facility emergency response planning, evacuation procedures, and employee training requirements",
        enforcing_agency="OSHA",
        state_variance="Low/None",
        update_frequency="OSHA EAP standard stable; plans reviewed and updated based on facility changes",
        authority_sources=({"domain": "osha.gov", "name": "OSHA"},),
    ),

    # ── Manufacturing: product_safety ─────────────────────────────────────────
    RegulationDef(
        key="product_certification", category="product_safety",
        name="Product Certification",
        description="Third-party product testing and certification (UL, CE, CSA) for safety compliance",
        enforcing_agency="CPSC/NRTL",
        state_variance="Moderate",
        update_frequency="Certification standards updated by standard-setting bodies; NRTL programs reviewed by OSHA",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),
    RegulationDef(
        key="recall_procedures", category="product_safety",
        name="Product Recall Procedures",
        description="Product recall notification, reporting, and remediation requirements",
        enforcing_agency="CPSC/FDA",
        state_variance="Low/None",
        update_frequency="CPSC recall procedures stable; reporting obligations updated periodically",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),
    RegulationDef(
        key="quality_system_requirements", category="product_safety",
        name="Product Quality System Requirements",
        description="Quality management system requirements for consumer and industrial product manufacturing",
        enforcing_agency="Various",
        state_variance="Moderate",
        update_frequency="Requirements vary by product type; updated with industry standards",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),
    RegulationDef(
        key="consumer_safety_standards", category="product_safety",
        name="Consumer Safety Standards",
        description="Mandatory and voluntary safety standards for consumer products",
        enforcing_agency="CPSC",
        state_variance="Moderate",
        update_frequency="CPSC issues mandatory standards; ASTM/ANSI voluntary standards updated regularly",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),
    RegulationDef(
        key="labeling_requirements", category="product_safety",
        name="Product Labeling Requirements",
        description="Product labeling, marking, warning, and instruction requirements for consumer safety",
        enforcing_agency="CPSC/FTC",
        state_variance="Moderate",
        update_frequency="Labeling requirements updated with product safety standards and FTC guidance",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),
    RegulationDef(
        key="type_approval", category="product_safety",
        name="Type Approval / Conformity Assessment",
        description="Market access certification and conformity assessment by country or region",
        enforcing_agency="National regulators",
        state_variance="Moderate",
        update_frequency="Country-specific requirements updated with trade agreements and regulatory changes",
        authority_sources=({"domain": "cpsc.gov", "name": "CPSC"},),
    ),

    # ── Manufacturing: trade_compliance ───────────────────────────────────────
    RegulationDef(
        key="customs_tariff", category="trade_compliance",
        name="Customs & Tariff Classification",
        description="Harmonized Tariff Schedule classification and duty rate determination for imports",
        enforcing_agency="CBP",
        state_variance="Moderate",
        update_frequency="HTS updated annually; tariff rates change with trade policy and presidential actions",
        authority_sources=({"domain": "cbp.gov", "name": "CBP"},),
    ),
    RegulationDef(
        key="export_controls", category="trade_compliance",
        name="Export Controls (EAR/ITAR)",
        description="Bureau of Industry and Security export licensing and ITAR defense trade controls",
        enforcing_agency="BIS/DDTC",
        state_variance="Low/None",
        update_frequency="EAR entity list updated frequently; ITAR USML revised periodically",
        authority_sources=({"domain": "bis.doc.gov", "name": "BIS"},),
    ),
    RegulationDef(
        key="anti_dumping_duties", category="trade_compliance",
        name="Anti-Dumping & Countervailing Duties",
        description="Trade remedy duty assessments on unfairly priced or subsidized imports",
        enforcing_agency="ITC/Commerce",
        state_variance="Moderate",
        update_frequency="AD/CVD orders reviewed annually; new investigations initiated as petitions filed",
        authority_sources=({"domain": "usitc.gov", "name": "USITC"},),
    ),
    RegulationDef(
        key="country_of_origin", category="trade_compliance",
        name="Country of Origin Marking",
        description="CBP marking requirements for country of origin on imported goods",
        enforcing_agency="CBP",
        state_variance="Low/None",
        update_frequency="Marking rules stable; interpretation rulings issued as needed",
        authority_sources=({"domain": "cbp.gov", "name": "CBP"},),
    ),
    RegulationDef(
        key="trade_agreements", category="trade_compliance",
        name="Trade Agreement Compliance",
        description="Free trade agreement qualification, rules of origin, and certificate of origin requirements",
        enforcing_agency="USTR/CBP",
        state_variance="Moderate",
        update_frequency="Updated as new trade agreements negotiated; USMCA rules of origin evolving",
        authority_sources=({"domain": "ustr.gov", "name": "USTR"},),
    ),
    RegulationDef(
        key="sanctions_screening", category="trade_compliance",
        name="Sanctions Screening",
        description="OFAC Specially Designated Nationals list and restricted party screening requirements",
        enforcing_agency="OFAC/Treasury",
        state_variance="Low/None",
        update_frequency="SDN list updated frequently; new sanctions programs issued by executive order",
        authority_sources=({"domain": "ofac.treasury.gov", "name": "OFAC"},),
    ),

    # ── Manufacturing: labor_relations ────────────────────────────────────────
    RegulationDef(
        key="collective_bargaining", category="labor_relations",
        name="Collective Bargaining Agreements",
        description="Union contract negotiation, administration, and unfair labor practice requirements",
        enforcing_agency="NLRB",
        state_variance="Low/None",
        update_frequency="NLRA framework stable; NLRB interpretations shift with board composition",
        authority_sources=({"domain": "nlrb.gov", "name": "NLRB"},),
    ),
    RegulationDef(
        key="right_to_work", category="labor_relations",
        name="Right-to-Work Laws",
        description="State laws prohibiting mandatory union membership or dues as a condition of employment",
        enforcing_agency="State legislatures",
        state_variance="High",
        update_frequency="State laws change with legislative action; currently 27 states have right-to-work laws",
        authority_sources=({"domain": "nlrb.gov", "name": "NLRB"},),
    ),
    RegulationDef(
        key="union_notification", category="labor_relations",
        name="Union Notification Requirements",
        description="WARN Act plant closing/mass layoff notices and union notification obligations",
        enforcing_agency="DOL/NLRB",
        state_variance="Low/None",
        update_frequency="Federal WARN Act stable; some states have mini-WARN laws with different thresholds",
        authority_sources=({"domain": "dol.gov", "name": "DOL"},),
    ),
    RegulationDef(
        key="strike_lockout_rules", category="labor_relations",
        name="Strike & Lockout Rules",
        description="Legal framework governing work stoppages, picketing, and lockout procedures",
        enforcing_agency="NLRB",
        state_variance="Low/None",
        update_frequency="NLRA framework stable; NLRB case law evolves with board decisions",
        authority_sources=({"domain": "nlrb.gov", "name": "NLRB"},),
    ),
    RegulationDef(
        key="works_council", category="labor_relations",
        name="Works Council / Employee Representation",
        description="European-style works council and employee representation requirements for international operations",
        enforcing_agency="National labor ministry",
        state_variance="Moderate",
        update_frequency="EU Works Council Directive stable; national transposition varies by country",
        authority_sources=({"domain": "ilo.org", "name": "ILO"},),
    ),
    RegulationDef(
        key="employee_representation", category="labor_relations",
        name="Employee Representation Rights",
        description="Right to organize, bargain collectively, and engage in protected concerted activity",
        enforcing_agency="NLRB/National",
        state_variance="Low/None",
        update_frequency="NLRA Section 7 rights stable; NLRB interpretations shift with board composition",
        authority_sources=({"domain": "nlrb.gov", "name": "NLRB"},),
    ),
]
