from __future__ import annotations

from typing import Any, Dict, FrozenSet, List, Optional, Set, Tuple  # noqa: F401

from app.core.compliance_registry._types import RegulationDef


REGULATIONS_HEALTHCARE: List[RegulationDef] = [
    RegulationDef(
        key="hipaa_privacy_rule",
        category="hipaa_privacy",
        name="HIPAA Privacy Rule (45 CFR Part 160, 164 Subparts A & E)",
        description="Use and disclosure of PHI, minimum necessary standard, patient rights (access, amendment, accounting of disclosures), Notice of Privacy Practices",
        enforcing_agency="HHS OCR",
        state_variance="Moderate",
        update_frequency="Every 2–5 yrs; guidance letters ongoing",
        authority_sources=(
            {"domain": "hhs.gov/hipaa", "name": "hhs.gov/hipaa"},
            {"domain": "federalregister.gov", "name": "search 45 CFR 164"},
        ),
    ),
    RegulationDef(
        key="hipaa_security_rule",
        category="hipaa_privacy",
        name="HIPAA Security Rule (45 CFR Part 164 Subpart C)",
        description="Administrative, physical, and technical safeguards for ePHI; risk analysis requirement; access controls; encryption standards",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Every 3–5 yrs; major update proposed 2024",
        authority_sources=(
            {"domain": "hhs.gov/hipaa/for-professionals/security", "name": "hhs.gov/hipaa/for-professionals/security"},
            {"domain": "healthit.gov", "name": "healthit.gov"},
        ),
    ),
    RegulationDef(
        key="hipaa_breach_notification_rule",
        category="hipaa_privacy",
        name="HIPAA Breach Notification Rule (45 CFR Part 164 Subpart D)",
        description="Notification to individuals, HHS, and media for unsecured PHI breaches; 60-day timeline; risk assessment methodology",
        enforcing_agency="HHS OCR",
        state_variance="Moderate",
        update_frequency="Rarely amended; OCR guidance periodic",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/breach-notification", "name": "hhs.gov/hipaa/for-professionals/breach-notification"},),
    ),
    RegulationDef(
        key="hitech_act",
        category="hipaa_privacy",
        name="HITECH Act (Title XIII of ARRA)",
        description="Strengthened HIPAA enforcement, extended to business associates, meaningful use incentives, increased penalties",
        enforcing_agency="HHS OCR / CMS",
        state_variance="Low/None",
        update_frequency="Rare (enacted 2009; provisions folded into HIPAA updates)",
        authority_sources=({"domain": "hhs.gov/hipaa/for-professionals/special-topics/hitech-act-enforcement-interim-final-rule", "name": "hhs.gov/hipaa/for-professionals/special-topics/hitech-act-enforcement-interim-final-rule"},),
    ),
    RegulationDef(
        key="42_cfr_part_2",
        category="hipaa_privacy",
        name="42 CFR Part 2 (Substance Use Disorder Records)",
        description="Stricter-than-HIPAA protections for SUD treatment records; requires specific written consent for most disclosures",
        enforcing_agency="SAMHSA / HHS OCR",
        state_variance="Moderate",
        update_frequency="Major update 2024 (final rule aligning with HIPAA for TPO); next update uncertain",
        authority_sources=(
            {"domain": "samhsa.gov/about-us/who-we-are/laws-regulations/confidentiality-regulations-faqs", "name": "samhsa.gov/about-us/who-we-are/laws-regulations/confidentiality-regulations-faqs"},
            {"domain": "federalregister.gov", "name": "federalregister.gov"},
        ),
    ),
    RegulationDef(
        key="state_health_privacy_laws",
        category="hipaa_privacy",
        name="State Health Privacy Laws",
        description="Many states impose stricter privacy requirements (e.g., CA CMIA, TX Medical Records Privacy Act, NY SHIELD Act); separate consent for HIV, mental health, genetic info",
        enforcing_agency="State AGs / Health Depts",
        state_variance="High",
        update_frequency="Continuous — state legislatures amend annually",
        authority_sources=(
            {"domain": "Each state legislature website", "name": "Each state legislature website"},
            {"domain": "ncsl.org/health", "name": "National Conference of State Legislatures"},
        ),
    ),
    RegulationDef(
        key="genetic_information_nondiscrimination_act",
        category="hipaa_privacy",
        name="Genetic Information Nondiscrimination Act (GINA)",
        description="Prohibits use of genetic information in health insurance and employment decisions; restricts collection of genetic data",
        enforcing_agency="HHS / EEOC",
        state_variance="Moderate",
        update_frequency="Rarely amended (enacted 2008); state genetic privacy laws update more often",
        authority_sources=(
            {"domain": "eeoc.gov/genetic-information-discrimination", "name": "eeoc.gov/genetic-information-discrimination"},
            {"domain": "genome.gov/about-genomics/policy-issues/Genetic-Discrimination", "name": "genome.gov/about-genomics/policy-issues/Genetic-Discrimination"},
        ),
    ),
    RegulationDef(
        key="ftc_health_breach_notification_rule",
        category="hipaa_privacy",
        name="FTC Health Breach Notification Rule (16 CFR Part 318)",
        description="Applies to non-HIPAA-covered entities handling health data (health apps, consumer devices); breach notification requirements",
        enforcing_agency="FTC",
        state_variance="Low/None",
        update_frequency="Updated 2023; periodic FTC rulemaking",
        authority_sources=({"domain": "ftc.gov/legal-library/browse/rules/health-breach-notification-rule", "name": "ftc.gov/legal-library/browse/rules/health-breach-notification-rule"},),
    ),
    RegulationDef(
        key="coppa",
        category="hipaa_privacy",
        name="COPPA (Children’s Online Privacy Protection Act)",
        description="Applies if collecting online data from children under 13; parental consent; relevant for patient portals and telehealth with minors",
        enforcing_agency="FTC",
        state_variance="Low/None",
        update_frequency="Updated every 3–5 yrs; major update finalized 2024",
        authority_sources=({"domain": "ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa", "name": "ftc.gov/legal-library/browse/rules/childrens-online-privacy-protection-rule-coppa"},),
    ),
    RegulationDef(
        key="state_biometric_privacy_laws",
        category="hipaa_privacy",
        name="State Biometric Privacy Laws (e.g., IL BIPA, TX CUBI)",
        description="Regulate collection/storage of biometric identifiers (fingerprints, retinal scans for facility access or patient ID)",
        enforcing_agency="State AGs / Private action in IL",
        state_variance="High",
        update_frequency="Active — new states passing laws annually (2023–2026)",
        authority_sources=(
            {"domain": "ilga.gov", "name": "IL BIPA 740 ILCS 14"},
            {"domain": "each state legislature site", "name": "each state legislature site"},
            {"domain": "ncsl.org/technology-and-telecommunication/biometric-data", "name": "ncsl.org/technology-and-telecommunication/biometric-data"},
        ),
    ),
    RegulationDef(
        key="false_claims_act",
        category="billing_integrity",
        name="False Claims Act (31 U.S.C. §§ 3729–3733)",
        description="Civil liability for knowingly submitting false claims to federal programs; qui tam (whistleblower) provisions; treble damages",
        enforcing_agency="DOJ / OIG",
        state_variance="Moderate",
        update_frequency="Rarely amended; DOJ guidance/memos update interpretation annually",
        authority_sources=(
            {"domain": "justice.gov/civil/fraud", "name": "justice.gov/civil/fraud"},
            {"domain": "oig.hhs.gov", "name": "oig.hhs.gov"},
        ),
    ),
    RegulationDef(
        key="antikickback_statute",
        category="billing_integrity",
        name="Anti-Kickback Statute (42 U.S.C. § 1320a-7b(b))",
        description="Criminal prohibition on offering/receiving remuneration for referrals of federal healthcare program business; safe harbors",
        enforcing_agency="OIG / DOJ",
        state_variance="High",
        update_frequency="Safe harbors updated every 3–5 yrs; OIG Advisory Opinions ongoing",
        authority_sources=(
            {"domain": "oig.hhs.gov/compliance/safe-harbor-regulations", "name": "oig.hhs.gov/compliance/safe-harbor-regulations"},
            {"domain": "oig.hhs.gov/compliance/advisory-opinions", "name": "oig.hhs.gov/compliance/advisory-opinions"},
        ),
    ),
    RegulationDef(
        key="stark_law",
        category="billing_integrity",
        name="Stark Law (42 U.S.C. § 1395nn)",
        description="Prohibits physician referrals for designated health services to entities with financial relationship, unless exception applies",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Exceptions updated every 3–5 yrs; major 2021 final rule",
        authority_sources=({"domain": "cms.gov/medicare/fraud-and-abuse/physicianselfreferral", "name": "cms.gov/medicare/fraud-and-abuse/physicianselfreferral"},),
    ),
    RegulationDef(
        key="criminal_health_care_fraud",
        category="billing_integrity",
        name="Criminal Health Care Fraud (18 U.S.C. § 1347)",
        description="Federal criminal offense for executing a scheme to defraud any healthcare benefit program",
        enforcing_agency="DOJ / FBI",
        state_variance="Low/None",
        update_frequency="Rarely amended; DOJ enforcement priorities shift annually",
        authority_sources=({"domain": "justice.gov/criminal-fraud/health-care-fraud-unit", "name": "justice.gov/criminal-fraud/health-care-fraud-unit"},),
    ),
    RegulationDef(
        key="exclusion_statute",
        category="billing_integrity",
        name="Exclusion Statute (42 U.S.C. § 1320a-7)",
        description="Mandatory and permissive exclusion from federal programs; OIG LEIE screening requirements",
        enforcing_agency="OIG",
        state_variance="Low/None",
        update_frequency="LEIE list updated monthly; statute rarely amended",
        authority_sources=(
            {"domain": "oig.hhs.gov/exclusions", "name": "oig.hhs.gov/exclusions"},
            {"domain": "sam.gov", "name": "sam.gov"},
        ),
    ),
    RegulationDef(
        key="civil_monetary_penalties_law",
        category="billing_integrity",
        name="Civil Monetary Penalties Law (42 U.S.C. § 1320a-7a)",
        description="Penalties for false claims, kickbacks, patient inducements, EMTALA violations",
        enforcing_agency="OIG",
        state_variance="Low/None",
        update_frequency="Penalty amounts adjusted annually for inflation",
        authority_sources=({"domain": "oig.hhs.gov/fraud/enforcement/cmp", "name": "oig.hhs.gov/fraud/enforcement/cmp"},),
    ),
    RegulationDef(
        key="no_surprises_act",
        category="billing_integrity",
        name="No Surprises Act (Consolidated Appropriations Act 2021)",
        description="Protects patients from surprise out-of-network bills; IDR process; good faith estimates for uninsured",
        enforcing_agency="CMS / State regulators",
        state_variance="High",
        update_frequency="Active rulemaking 2022–2025; IDR process under litigation/revision",
        authority_sources=(
            {"domain": "cms.gov/nosurprises", "name": "cms.gov/nosurprises"},
            {"domain": "cms.gov/cciio/resources", "name": "cms.gov/cciio/resources"},
        ),
    ),
    RegulationDef(
        key="medicare_conditions_of_payment_billing_rules",
        category="billing_integrity",
        name="Medicare Conditions of Payment / Billing Rules",
        description="Proper use of CPT, HCPCS, ICD-10 codes; medical necessity documentation; timely filing; claims submission",
        enforcing_agency="CMS / MACs",
        state_variance="Low/None",
        update_frequency="Annual code updates (Oct ICD-10, Jan CPT); transmittals ongoing",
        authority_sources=(
            {"domain": "cms.gov/medicare/coding", "name": "cms.gov/medicare/coding"},
            {"domain": "cms.gov/regulations-and-guidance/transmittals", "name": "cms.gov/regulations-and-guidance/transmittals"},
        ),
    ),
    RegulationDef(
        key="medicaid_billing_requirements",
        category="billing_integrity",
        name="Medicaid Billing Requirements",
        description="State-specific fee schedules, prior auth rules, eligibility verification, managed care contracts",
        enforcing_agency="CMS / State Medicaid",
        state_variance="High",
        update_frequency="Continuous — state Medicaid agencies update throughout year",
        authority_sources=(
            {"domain": "medicaid.gov", "name": "medicaid.gov"},
            {"domain": "each state Medicaid agency website", "name": "each state Medicaid agency website"},
        ),
    ),
    RegulationDef(
        key="state_antikickback_selfreferral_laws",
        category="billing_integrity",
        name="State Anti-Kickback & Self-Referral Laws",
        description="Many states have own anti-kickback and self-referral statutes, some broader than federal equivalents",
        enforcing_agency="State AGs / Boards",
        state_variance="High",
        update_frequency="Varies by state; legislative sessions annually",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "oig.hhs.gov/compliance/state-false-claims-act", "name": "oig.hhs.gov/compliance/state-false-claims-act"},
        ),
    ),
    RegulationDef(
        key="state_false_claims_acts",
        category="billing_integrity",
        name="State False Claims Acts",
        description="Over 30 states have own false claims acts with broader scope than federal FCA",
        enforcing_agency="State AGs",
        state_variance="High",
        update_frequency="Updated periodically; OIG maintains qualifying list",
        authority_sources=(
            {"domain": "oig.hhs.gov/fraud/state-false-claims-act", "name": "oig.hhs.gov/fraud/state-false-claims-act"},
            {"domain": "each state AG website", "name": "each state AG website"},
        ),
    ),
    RegulationDef(
        key="medicare_secondary_payer_rules",
        category="billing_integrity",
        name="Medicare Secondary Payer (MSP) Rules",
        description="Coordination of benefits when Medicare is secondary; reporting obligations to BCRC",
        enforcing_agency="CMS / BCRC",
        state_variance="Low/None",
        update_frequency="Reporting thresholds updated periodically; guidance letters ongoing",
        authority_sources=({"domain": "cms.gov/medicare/coordination-of-benefits-and-recovery", "name": "cms.gov/medicare/coordination-of-benefits-and-recovery"},),
    ),
    RegulationDef(
        key="provider_enrollment_revalidation",
        category="billing_integrity",
        name="Provider Enrollment & Revalidation (42 CFR Part 424)",
        description="Medicare enrollment requirements, screening levels, revalidation cycles, reporting changes",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Revalidation cycles every 3–5 yrs; rules updated periodically",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},),
    ),
    RegulationDef(
        # The Medicaid-side analog of the key above (42 CFR Part 455 Subpart E,
        # administered per-state: Medi-Cal in CA, eMedNY in NY, …). A separate
        # obligation with its own screening levels, its own revalidation clock and
        # its own state agency — not the Medicare rule wearing a state name, which
        # is how it ended up colliding on `provider_enrollment_revalidation`.
        key="medicaid_provider_enrollment",
        category="billing_integrity",
        name="Medicaid Provider Enrollment & Screening (42 CFR Part 455 Subpart E)",
        description=(
            "State Medicaid enrollment, screening (categorical risk levels), site visits, "
            "fingerprinting and revalidation — administered by the state Medicaid agency"
        ),
        enforcing_agency="State Medicaid agency (e.g. DHCS/Medi-Cal) / CMS",
        state_variance="High",
        update_frequency="Revalidation at least every 5 yrs; state rules change independently",
        authority_sources=({"domain": "medicaid.gov/medicaid/program-integrity", "name": "medicaid.gov Program Integrity"},),
    ),
    RegulationDef(
        key="cms_conditions_of_participation",
        category="clinical_safety",
        name="CMS Conditions of Participation (42 CFR Parts 482–491)",
        description="Minimum health and safety standards for hospitals, SNFs, HHAs, ASCs, and other providers in Medicare/Medicaid",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Updated every 2–5 yrs via rulemaking; Interpretive Guidelines updated more frequently",
        authority_sources=(
            {"domain": "cms.gov/regulations-and-guidance/legislation/cfr", "name": "cms.gov/regulations-and-guidance/legislation/cfr"},
            {"domain": "cms.gov/medicare/provider-enrollment-and-certification/surveycertificationgeninfo", "name": "cms.gov/medicare/provider-enrollment-and-certification/surveycertificationgeninfo"},
        ),
    ),
    RegulationDef(
        key="cms_conditions_for_coverage",
        category="clinical_safety",
        name="CMS Conditions for Coverage (CfCs)",
        description="Standards for ESRD facilities, transplant centers, hospice, CORF, CMHC, OPOs",
        enforcing_agency="CMS",
        state_variance="Low/None",
        update_frequency="Updated every 3–5 yrs",
        authority_sources=({"domain": "cms.gov/regulations-and-guidance/legislation/cfr", "name": "cms.gov/regulations-and-guidance/legislation/cfr"},),
    ),
    RegulationDef(
        key="joint_commission_standards",
        category="clinical_safety",
        name="Joint Commission Standards",
        description="Deemed status for CMS; patient safety goals, medication management, infection prevention, leadership, environment of care",
        enforcing_agency="Joint Commission",
        state_variance="Low/None",
        update_frequency="Annual updates to standards; NPSGs updated annually",
        authority_sources=(
            {"domain": "jointcommission.org/standards", "name": "jointcommission.org/standards"},
            {"domain": "jointcommission.org/resources/patient-safety-topics/national-patient-safety-goals", "name": "jointcommission.org/resources/patient-safety-topics/national-patient-safety-goals"},
        ),
    ),
    RegulationDef(
        key="dnv_gl_healthcare_accreditation",
        category="clinical_safety",
        name="DNV GL Healthcare Accreditation",
        description="Alternative deemed status based on ISO 9001 quality management framework",
        enforcing_agency="DNV GL",
        state_variance="Low/None",
        update_frequency="ISO 9001 updated every 5–7 yrs; DNV standards updated annually",
        authority_sources=({"domain": "dnv.com/assurance/healthcare", "name": "dnv.com/assurance/healthcare"},),
    ),
    RegulationDef(
        key="state_licensure_standards_for_healthcare_facilitie",
        category="clinical_safety",
        name="State Licensure Standards for Healthcare Facilities",
        description="State-specific requirements for hospitals, ASCs, nursing homes, clinics, labs, and other facility types",
        enforcing_agency="State Health Depts",
        state_variance="High",
        update_frequency="Continuous — updated via state regulation and legislation",
        authority_sources=(
            {"domain": "Each state health department website", "name": "Each state health department website"},
            {"domain": "ahd.com", "name": "American Hospital Directory"},
        ),
    ),
    RegulationDef(
        key="emtala",
        category="clinical_safety",
        name="EMTALA (42 U.S.C. § 1395dd)",
        description="Medical screening and stabilization for anyone presenting to ED regardless of ability to pay",
        enforcing_agency="CMS / OIG",
        state_variance="Low/None",
        update_frequency="Rarely amended; CMS Interpretive Guidelines updated periodically",
        authority_sources=({"domain": "cms.gov/medicare/provider-enrollment-and-certification/surveycertificationgeninfo/downloads/sc-letter08-01.pdf", "name": "cms.gov/medicare/provider-enrollment-and-certification/surveycertificationgeninfo/downloads/sc-letter08-01.pdf"},),
    ),
    RegulationDef(
        key="patient_safety_quality_improvement_act",
        category="clinical_safety",
        name="Patient Safety & Quality Improvement Act (PSQIA)",
        description="Privilege and confidentiality protections for patient safety work product reported to PSOs",
        enforcing_agency="AHRQ",
        state_variance="Moderate",
        update_frequency="Rarely amended (enacted 2005); PSO listing updated ongoing",
        authority_sources=({"domain": "pso.ahrq.gov", "name": "pso.ahrq.gov"},),
    ),
    RegulationDef(
        key="npdb_reporting",
        category="clinical_safety",
        name="NPDB Reporting",
        description="Mandatory reporting of malpractice payments, adverse licensure actions, adverse privilege actions",
        enforcing_agency="HRSA",
        state_variance="Low/None",
        update_frequency="Reporting requirements stable; guidebook updated every 2–3 yrs",
        authority_sources=({"domain": "npdb.hrsa.gov", "name": "npdb.hrsa.gov"},),
    ),
    RegulationDef(
        key="sentinel_event_reporting",
        category="clinical_safety",
        name="Sentinel Event Reporting",
        description="Reporting of serious patient safety events per Joint Commission or state requirements",
        enforcing_agency="Joint Commission / State",
        state_variance="High",
        update_frequency="Joint Commission sentinel event policy updated annually; state requirements vary",
        authority_sources=(
            {"domain": "jointcommission.org/resources/patient-safety-topics/sentinel-event", "name": "jointcommission.org/resources/patient-safety-topics/sentinel-event"},
            {"domain": "each state health dept", "name": "each state health dept"},
        ),
    ),
    RegulationDef(
        key="infection_control_prevention_standards",
        category="clinical_safety",
        name="Infection Control & Prevention Standards",
        description="CMS CoP requirements, CDC guidelines (HAI prevention), state-mandated HAI reporting",
        enforcing_agency="CMS / CDC / State",
        state_variance="High",
        update_frequency="CDC guidelines updated continuously; state reporting requirements update annually",
        authority_sources=(
            {"domain": "cdc.gov/hai", "name": "cdc.gov/hai"},
            {"domain": "cms.gov/medicare/infection-control", "name": "cms.gov/medicare/infection-control"},
        ),
    ),
    RegulationDef(
        key="medication_management_controlled_substances",
        category="clinical_safety",
        name="Medication Management & Controlled Substances (21 CFR 1301–1321)",
        description="DEA registration, Schedule II-V prescribing, PDMP requirements, medication storage/dispensing protocols",
        enforcing_agency="DEA / State Pharmacy Boards",
        state_variance="High",
        update_frequency="DEA scheduling actions ongoing; state PDMP laws update annually",
        authority_sources=(
            {"domain": "deadiversion.usdoj.gov", "name": "deadiversion.usdoj.gov"},
            {"domain": "each state pharmacy board", "name": "each state pharmacy board"},
        ),
    ),
    RegulationDef(
        key="clia",
        category="clinical_safety",
        name="CLIA (42 CFR Part 493)",
        description="Certification and quality standards for all clinical laboratories; proficiency testing; personnel requirements",
        enforcing_agency="CMS / CDC / State",
        state_variance="Moderate",
        update_frequency="Updated every 3–5 yrs; proficiency testing updated annually",
        authority_sources=(
            {"domain": "cms.gov/regulations-and-guidance/legislation/clia", "name": "cms.gov/regulations-and-guidance/legislation/clia"},
            {"domain": "cdc.gov/clia", "name": "cdc.gov/clia"},
        ),
    ),
    RegulationDef(
        key="informed_consent_requirements",
        category="clinical_safety",
        name="Informed Consent Requirements",
        description="Federal common rule for research (45 CFR 46); state requirements for surgical/treatment consent, blood, HIV testing",
        enforcing_agency="CMS / State law",
        state_variance="High",
        update_frequency="State laws update frequently; federal common rule updated 2018",
        authority_sources=(
            {"domain": "hhs.gov/ohrp/regulations-and-policy", "name": "hhs.gov/ohrp/regulations-and-policy"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="advance_directives",
        category="clinical_safety",
        name="Advance Directives (Patient Self-Determination Act)",
        description="Requirement to inform patients of advance directive rights; state-specific forms and requirements",
        enforcing_agency="CMS / State law",
        state_variance="High",
        update_frequency="Federal law stable; state forms and laws update every few years",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "caringinfo.org", "name": "NHPCO"},
        ),
    ),
    RegulationDef(
        key="restraint_seclusion_standards",
        category="clinical_safety",
        name="Restraint & Seclusion Standards (42 CFR 482.13(e)–(f))",
        description="CMS rules on physical restraints and seclusion; documentation, monitoring, physician orders, time limits",
        enforcing_agency="CMS / Joint Commission",
        state_variance="Moderate",
        update_frequency="Updated every 3–5 yrs; Joint Commission standards updated annually",
        authority_sources=({"domain": "cms.gov/regulations-and-guidance/legislation/cfr", "name": "cms.gov/regulations-and-guidance/legislation/cfr"},),
    ),
    RegulationDef(
        key="pain_management_opioid_prescribing",
        category="clinical_safety",
        name="Pain Management & Opioid Prescribing",
        description="CDC clinical practice guidelines; state prescribing limits; PDMP check requirements; mandatory prescriber education",
        enforcing_agency="CDC / State Medical Boards",
        state_variance="High",
        update_frequency="CDC guidelines updated 2022; state laws update annually",
        authority_sources=(
            {"domain": "cdc.gov/opioids/healthcare-professionals/prescribing", "name": "cdc.gov/opioids/healthcare-professionals/prescribing"},
            {"domain": "each state medical board", "name": "each state medical board"},
        ),
    ),
    RegulationDef(
        key="antimicrobial_stewardship_programs",
        category="clinical_safety",
        name="Antimicrobial Stewardship Programs",
        description="CMS CoP requirement for hospitals; Joint Commission standards; CDC Core Elements",
        enforcing_agency="CMS / CDC",
        state_variance="Moderate",
        update_frequency="CDC Core Elements updated every 2–3 yrs; CMS CoP updated less frequently",
        authority_sources=({"domain": "cdc.gov/antibiotic-use/core-elements", "name": "cdc.gov/antibiotic-use/core-elements"},),
    ),
    RegulationDef(
        key="medical_staff_credentialing_privileging",
        category="healthcare_workforce",
        name="Medical Staff Credentialing & Privileging",
        description="Verification of education, training, licensure, board cert, malpractice history; initial and reappointment per CMS CoPs",
        enforcing_agency="CMS / Joint Commission / State",
        state_variance="Moderate",
        update_frequency="Accreditation standards updated annually; CMS CoPs every 3–5 yrs",
        authority_sources=(
            {"domain": "jointcommission.org/standards", "name": "jointcommission.org/standards"},
            {"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},
        ),
    ),
    RegulationDef(
        key="provider_licensure_scope_of_practice",
        category="healthcare_workforce",
        name="Provider Licensure & Scope of Practice",
        description="State-specific licensing for physicians, nurses, PAs, NPs, allied health; scope of practice boundaries",
        enforcing_agency="State Licensing Boards",
        state_variance="High",
        update_frequency="Continuous — scope of practice bills introduced every legislative session",
        authority_sources=(
            {"domain": "Each state licensing board", "name": "Each state licensing board"},
            {"domain": "ncsbn.org", "name": "nursing"},
            {"domain": "fsmb.org", "name": "medicine"},
        ),
    ),
    RegulationDef(
        key="oig_exclusion_list_screening",
        category="healthcare_workforce",
        name="OIG Exclusion List (LEIE) Screening",
        description="Monthly screening of employees, contractors, vendors against LEIE; SAM.gov screening; immediate action for matches",
        enforcing_agency="OIG",
        state_variance="Low/None",
        update_frequency="LEIE updated monthly",
        authority_sources=(
            {"domain": "oig.hhs.gov/exclusions", "name": "oig.hhs.gov/exclusions"},
            {"domain": "sam.gov", "name": "sam.gov"},
        ),
    ),
    RegulationDef(
        key="npdb_queries",
        category="healthcare_workforce",
        name="NPDB Queries",
        description="Query NPDB for credentialing of physicians, dentists, other practitioners every 2 years minimum",
        enforcing_agency="HRSA",
        state_variance="Low/None",
        update_frequency="Database updated continuously; query requirements stable",
        authority_sources=({"domain": "npdb.hrsa.gov", "name": "npdb.hrsa.gov"},),
    ),
    RegulationDef(
        key="background_check_requirements",
        category="healthcare_workforce",
        name="Background Check Requirements",
        description="Federal requirements for long-term care; state-specific requirements for various healthcare roles",
        enforcing_agency="CMS / State",
        state_variance="High",
        update_frequency="State laws update every 1–3 yrs",
        authority_sources=(
            {"domain": "cms.gov/medicare/provider-enrollment-and-certification", "name": "cms.gov/medicare/provider-enrollment-and-certification"},
            {"domain": "each state health dept", "name": "each state health dept"},
        ),
    ),
    RegulationDef(
        key="osha_workplace_safety",
        category="healthcare_workforce",
        name="OSHA Workplace Safety (29 CFR Part 1910)",
        description="Bloodborne Pathogen Standard; hazard communication; PPE; recordkeeping; general duty clause",
        enforcing_agency="OSHA",
        state_variance="Moderate",
        update_frequency="Standards updated every 3–10 yrs; guidance documents more frequently",
        authority_sources=(
            {"domain": "osha.gov/healthcare", "name": "osha.gov/healthcare"},
            {"domain": "osha.gov/bloodborne-pathogens", "name": "osha.gov/bloodborne-pathogens"},
        ),
    ),
    RegulationDef(
        key="osha_workplace_violence_prevention",
        category="healthcare_workforce",
        name="OSHA Workplace Violence Prevention",
        description="OSHA guidelines for healthcare workers; some states mandate workplace violence prevention programs",
        enforcing_agency="OSHA / State OSHA plans",
        state_variance="High",
        update_frequency="Federal guidance updated periodically; CA SB 1299 and other state laws update actively",
        authority_sources=(
            {"domain": "osha.gov/workplace-violence", "name": "osha.gov/workplace-violence"},
            {"domain": "each state OSHA plan", "name": "each state OSHA plan"},
        ),
    ),
    RegulationDef(
        key="ada",
        category="healthcare_workforce",
        name="ADA (Americans with Disabilities Act)",
        description="Non-discrimination in employment; reasonable accommodations; applies to 15+ employee employers",
        enforcing_agency="EEOC / DOJ",
        state_variance="Moderate",
        update_frequency="ADA Amendments Act 2008; EEOC guidance updated every 2–3 yrs",
        authority_sources=(
            {"domain": "eeoc.gov/ada", "name": "eeoc.gov/ada"},
            {"domain": "ada.gov", "name": "ada.gov"},
        ),
    ),
    RegulationDef(
        key="fmla",
        category="healthcare_workforce",
        name="FMLA (Family and Medical Leave Act)",
        description="12 weeks unpaid leave for eligible employees; many states provide additional leave protections",
        enforcing_agency="DOL",
        state_variance="High",
        update_frequency="Federal FMLA stable; state paid family leave laws rapidly expanding (2020–2026)",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/fmla", "name": "dol.gov/agencies/whd/fmla"},
            {"domain": "each state labor dept", "name": "each state labor dept"},
        ),
    ),
    RegulationDef(
        key="title_vii_civil_rights_act",
        category="healthcare_workforce",
        name="Title VII / Civil Rights Act",
        description="Prohibition on discrimination based on race, color, religion, sex, national origin; sexual harassment",
        enforcing_agency="EEOC",
        state_variance="Moderate",
        update_frequency="EEOC guidance updated every 2–3 yrs; Bostock (2020) expanded sex discrimination",
        authority_sources=({"domain": "eeoc.gov/laws/statutes/titlevii", "name": "eeoc.gov/laws/statutes/titlevii"},),
    ),
    RegulationDef(
        key="section_1557_of_aca",
        category="healthcare_workforce",
        name="Section 1557 of ACA (Nondiscrimination)",
        description="Prohibits discrimination in health programs receiving federal funding; language access requirements",
        enforcing_agency="HHS OCR",
        state_variance="Low/None",
        update_frequency="Major rulemaking cycles every 3–5 yrs (2016, 2020, 2024 rules)",
        authority_sources=({"domain": "hhs.gov/civil-rights/for-individuals/section-1557", "name": "hhs.gov/civil-rights/for-individuals/section-1557"},),
    ),
    RegulationDef(
        key="flsa",
        category="healthcare_workforce",
        name="FLSA (Fair Labor Standards Act)",
        description="Minimum wage, overtime; nurse and resident physician overtime; state wage laws often more generous",
        enforcing_agency="DOL",
        state_variance="High",
        update_frequency="Federal minimum wage rarely updated; state wage laws change frequently",
        authority_sources=(
            {"domain": "dol.gov/agencies/whd/flsa", "name": "dol.gov/agencies/whd/flsa"},
            {"domain": "each state labor dept", "name": "each state labor dept"},
        ),
    ),
    RegulationDef(
        key="immigration_compliance",
        category="healthcare_workforce",
        name="Immigration Compliance (I-9 / Visa Requirements)",
        description="Employment verification; J-1 waivers for physicians; H-1B for healthcare professionals",
        enforcing_agency="DHS / USCIS / DOL",
        state_variance="Moderate",
        update_frequency="I-9 form updated every 3 yrs; visa policies shift with administrations",
        authority_sources=(
            {"domain": "uscis.gov/i-9", "name": "uscis.gov/i-9"},
            {"domain": "travel.state.gov/j-1", "name": "travel.state.gov/j-1"},
        ),
    ),
    RegulationDef(
        key="mandatory_reporting_obligations",
        category="healthcare_workforce",
        name="Mandatory Reporting Obligations",
        description="Abuse/neglect reporting (child, elder, vulnerable adult); communicable disease; gunshot/stab wound",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Continuous — state reporting requirements update annually",
        authority_sources=(
            {"domain": "childwelfare.gov/topics/systemwide/laws-policies/statutes/manda", "name": "childwelfare.gov/topics/systemwide/laws-policies/statutes/manda"},
            {"domain": "each state legislature", "name": "each state legislature"},
        ),
    ),
    RegulationDef(
        key="continuing_education_requirements",
        category="healthcare_workforce",
        name="Continuing Education Requirements",
        description="State-specific CE/CME requirements for license renewal by profession",
        enforcing_agency="State Licensing Boards",
        state_variance="High",
        update_frequency="Updated with each license renewal cycle (1–3 yrs)",
        authority_sources=(
            {"domain": "Each state licensing board", "name": "Each state licensing board"},
            {"domain": "accme.org", "name": "physician CME"},
        ),
    ),
    RegulationDef(
        key="nurse_staffing_ratios_requirements",
        category="healthcare_workforce",
        name="Nurse Staffing Ratios & Requirements",
        description="CA mandated ratios; other states have staffing committees, disclosure requirements, or guidelines",
        enforcing_agency="State law",
        state_variance="High",
        update_frequency="Active legislative area — bills introduced each session",
        authority_sources=(
            {"domain": "Each state legislature", "name": "Each state legislature"},
            {"domain": "nursingworld.org", "name": "ANA"},
        ),
    ),
    RegulationDef(
        key="physician_residency_gme_requirements",
        category="healthcare_workforce",
        name="Physician Residency & GME Requirements",
        description="ACGME accreditation standards; duty hour restrictions; supervision requirements",
        enforcing_agency="ACGME / CMS",
        state_variance="Low/None",
        update_frequency="ACGME Common Program Requirements updated every 2–3 yrs",
        authority_sources=({"domain": "acgme.org/what-we-do/accreditation/common-program-requirements", "name": "acgme.org/what-we-do/accreditation/common-program-requirements"},),
    ),
]
