name: MatchaTutor
options:
  bundleIdPrefix: com.matcha
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  MatchaTutor:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
      - path: Models
      - path: Services
      - path: ViewModels
      - path: Views
      - path: Resources
    resources:
      - path: Resources/Assets.xcassets
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.matcha.tutor
        INFOPLIST_FILE: Info.plist
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    entitlements:
      path: MatchaTutor.entitlements

schemes:
  MatchaTutor:
    build:
      targets:
        MatchaTutor: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
