"""Public investigation interview invite endpoints (no auth required)."""

from datetime import datetime, timedelta, timezone

from fastapi import APIRouter, HTTPException
from app.database import get_connection
from app.core.services.auth import create_interview_ws_token

router = APIRouter()

# Investigation invite links are long-lived credentials that expose incident
# context + AI-generated questions to anyone holding the URL. Bound their
# lifetime so a forwarded/leaked link can't be used indefinitely. The clock is
# ``invite_sent_at`` (reset when a link is resent/regenerated by an admin).
INVITE_TOKEN_TTL_DAYS = 30


def _invite_expired(invite_sent_at) -> bool:
    """True when a still-open invite has aged past the TTL."""
    if invite_sent_at is None:
        return False  # never sent (defensive) — don't lock out
    now = datetime.now(timezone.utc)
    if invite_sent_at.tzinfo is None:
        invite_sent_at = invite_sent_at.replace(tzinfo=timezone.utc)
    return now - invite_sent_at > timedelta(days=INVITE_TOKEN_TTL_DAYS)


# ============================================================================
# Public endpoints (no auth - invite_token-based access)
# ============================================================================


@router.get("/investigation/{token}")
async def get_investigation_invite_info(token: str):
    """Get public info for an investigation interview invite link."""
    async with get_connection() as conn:
        row = await conn.fetchrow(
            """
            SELECT ii.interviewee_name, ii.interviewee_role, ii.status,
                   ii.invite_sent_at,
                   i.incident_type, co.name as company_name
            FROM ir_investigation_interviews ii
            JOIN ir_incidents i ON ii.incident_id = i.id
            JOIN companies co ON i.company_id = co.id
            WHERE ii.invite_token = $1
            """,
            token,
        )

        if not row:
            raise HTTPException(status_code=404, detail="Invalid or expired link")

        if row["status"] == "cancelled":
            raise HTTPException(status_code=410, detail="This interview has been cancelled")

        if row["status"] not in ("completed", "analyzed") and _invite_expired(row["invite_sent_at"]):
            raise HTTPException(
                status_code=410,
                detail="This interview link has expired. Ask your contact to resend it.",
            )

        return {
            "interviewee_name": row["interviewee_name"],
            "interviewee_role": row["interviewee_role"],
            "company_name": row["company_name"],
            "incident_type": row["incident_type"],
            "status": row["status"],
        }


@router.post("/investigation/{token}/start")
async def start_investigation_interview(token: str):
    """Start an investigation interview via invite token."""
    async with get_connection() as conn:
        row = await conn.fetchrow(
            """
            SELECT ii.id, ii.status, ii.interview_id, ii.invite_sent_at
            FROM ir_investigation_interviews ii
            WHERE ii.invite_token = $1
            """,
            token,
        )

        if not row:
            raise HTTPException(status_code=404, detail="Invalid or expired link")

        if row["status"] == "cancelled":
            raise HTTPException(status_code=410, detail="This interview has been cancelled")

        # Allow re-viewing a completed interview
        if row["status"] in ("completed", "analyzed"):
            return {"status": "completed"}

        if _invite_expired(row["invite_sent_at"]):
            raise HTTPException(
                status_code=410,
                detail="This interview link has expired. Ask your contact to resend it.",
            )

        interview_id = row["interview_id"]
        ws_token = create_interview_ws_token(interview_id)

        # Update junction row to in_progress only if currently pending (idempotent)
        await conn.execute(
            """
            UPDATE ir_investigation_interviews
            SET status = 'in_progress'
            WHERE invite_token = $1 AND status = 'pending'
            """,
            token,
        )

        # Update interview record to in_progress only if currently pending
        await conn.execute(
            """
            UPDATE interviews
            SET status = 'in_progress'
            WHERE id = $1 AND status = 'pending'
            """,
            interview_id,
        )

        return {
            "interview_id": str(interview_id),
            "websocket_url": f"/api/ws/interview/{interview_id}",
            "ws_auth_token": ws_token,
            "status": "started",
        }
