import type { WalkthroughConfig } from '../types';

export const complianceWalkthrough: WalkthroughConfig = {
  id: 'compliance',
  title: 'Compliance Module',
  category: 'admin',
  steps: [
    {
      target: 'compliance-locations',
      title: 'Locations Sidebar',
      content: 'Your business locations are listed here. Each location has its own set of compliance requirements.',
      placement: 'right',
      expect: 'A list of location cards in the sidebar.',
      ifMissing: 'If the sidebar is empty, you need to add your first business location.',
    },
    {
      target: 'compliance-add-btn',
      title: 'Add Location',
      content: 'Register a new business location to start tracking its compliance requirements.',
      placement: 'bottom',
      action: 'Click to open the add location form.',
    },
    {
      target: 'compliance-location-card',
      title: 'Location Card',
      content: 'Click a location card to view its compliance details. The selected location is highlighted.',
      placement: 'right',
      action: 'Click a location to select it and see its requirements.',
      ifMissing: 'Add a location first to see location cards.',
    },
    {
      target: 'compliance-tabs',
      title: 'Content Tabs',
      content: 'Switch between requirements, posters, and deadlines for the selected location.',
      placement: 'bottom',
      action: 'Click a tab to switch views.',
      ifMissing: 'Select a location first to see the tabs.',
    },
    {
      target: 'compliance-content',
      title: 'Compliance Content',
      content: 'The main content area shows requirements, required posters, or upcoming deadlines based on the active tab.',
      placement: 'left',
      expect: 'Compliance requirements or poster information for the selected location.',
      ifMissing: 'Select a location and tab to see content.',
    },
    {
      target: 'compliance-company-select',
      title: 'Company Selector',
      content: 'Admin-only: switch between companies to manage compliance for different organizations.',
      placement: 'bottom',
      ifMissing: 'This control only appears for platform admins managing multiple companies.',
    },
  ],
};

export const policiesWalkthrough: WalkthroughConfig = {
  id: 'policies',
  title: 'Policies',
  category: 'admin',
  steps: [
    {
      target: 'policies-create-btn',
      title: 'Create Policy',
      content: 'Start drafting a new company policy with sections, signature settings, and publication status.',
      placement: 'bottom',
      action: 'Click to open the policy editor.',
    },
    {
      target: 'policies-tabs',
      title: 'Status Filters',
      content: 'Filter policies by lifecycle status: Active, Draft, and Archived.',
      placement: 'bottom',
      action: 'Click a tab to narrow the policy list.',
    },
    {
      target: 'policies-list',
      title: 'Policy List',
      content: 'Browse all policies, open details, and manage versions from this table.',
      placement: 'top',
      action: 'Click any row to open the policy detail page.',
      expect: 'Rows with policy title, version, signed count, and status.',
      ifMissing: 'No policies match the current filter. Create your first policy to populate this list.',
    },
    {
      target: 'policies-activate-btn',
      title: 'Activate Drafts',
      content: 'Publish a draft policy so employees can review and sign it.',
      placement: 'left',
      action: 'Click the check icon on a draft policy to activate it.',
      ifMissing: 'This action appears only on policies currently in draft status.',
    },
  ],
};

export const handbooksWalkthrough: WalkthroughConfig = {
  id: 'handbooks',
  title: 'Handbooks',
  category: 'admin',
  steps: [
    {
      target: 'handbooks-create-btn',
      title: 'Create Handbook',
      content: 'Start the handbook setup wizard to generate a new employee handbook from a template or upload.',
      placement: 'bottom',
      action: 'Click to open the handbook wizard.',
    },
    {
      target: 'handbooks-tabs',
      title: 'Status Filters',
      content: 'Filter handbook records by lifecycle state: Active, Draft, and Archived.',
      placement: 'bottom',
      action: 'Click a tab to narrow the list.',
    },
    {
      target: 'handbooks-list',
      title: 'Handbook List',
      content: 'Open any handbook to edit sections, review legal updates, download PDF, and distribute acknowledgements.',
      placement: 'top',
      action: 'Click a row to open handbook details.',
      expect: 'Rows with title, scope, version, pending changes, and status.',
      ifMissing: 'No handbooks exist yet. Use Create Handbook to start one.',
    },
    {
      target: 'handbooks-publish-btn',
      title: 'Publish',
      content: 'Publishing makes this handbook active and automatically archives any other active handbook.',
      placement: 'left',
      ifMissing: 'Publish appears on draft/archived rows.',
    },
    {
      target: 'handbooks-distribute-btn',
      title: 'Send for E-Sign',
      content: 'Send the active handbook to all current employees for acknowledgement signatures.',
      placement: 'left',
      ifMissing: 'Distribution appears only on active handbooks.',
    },
  ],
};

export const handbookCreateWalkthrough: WalkthroughConfig = {
  id: 'handbook-create',
  title: 'Handbook Setup Wizard',
  category: 'admin',
  steps: [
    {
      target: 'handbook-wizard-progress',
      title: 'Step Progress',
      content: 'This bar tracks progress through setup. You can move between steps before final creation.',
      placement: 'bottom',
    },
    {
      target: 'handbook-step-pill-basics',
      title: 'Basics',
      content: 'Define handbook title, single-state vs multi-state mode, and source type (template or upload).',
      placement: 'top',
    },
    {
      target: 'handbook-step-pill-scope',
      title: 'State Scope',
      content: 'Select the covered states. Multi-state mode requires at least two states.',
      placement: 'top',
    },
    {
      target: 'handbook-step-pill-profile',
      title: 'Company Profile',
      content: 'Provide legal identity fields used to generate handbook language and headers.',
      placement: 'top',
    },
    {
      target: 'handbook-step-pill-workforce',
      title: 'Workforce Setup',
      content: 'Answer workforce questions and add upload/custom sections based on your source type.',
      placement: 'top',
    },
    {
      target: 'handbook-step-pill-review',
      title: 'Review and Create',
      content: 'Confirm all selections, then create the handbook to generate editable sections.',
      placement: 'top',
    },
  ],
};

export const offerLettersWalkthrough: WalkthroughConfig = {
  id: 'offer-letters',
  title: 'Offer Letters',
  category: 'admin',
  steps: [
    {
      target: 'offer-create-btn',
      title: 'Create Offer',
      content: 'Generate a new offer letter for a candidate.',
      placement: 'bottom',
      action: 'Click to choose Quick Form or Wizard Mode.',
    },
    {
      target: 'offer-create-mode',
      title: 'Creation Mode',
      content: 'Choose between Quick Form (single screen) and Wizard Mode (guided steps).',
      placement: 'left',
      action: 'Pick the mode that matches your workflow.',
      ifMissing: 'Click Create Offer first to open this menu.',
    },
    {
      target: 'offer-list',
      title: 'Offer List',
      content: 'Review drafted and sent offers, then open any offer to view details or download PDF.',
      placement: 'top',
      action: 'Click any offer row/card to open its detail view.',
      expect: 'Offer entries with candidate name, role, status, and created date.',
      ifMissing: 'No offers exist yet. Use Create Offer to generate your first one.',
    },
    {
      target: 'offer-first-create-btn',
      title: 'First Offer Shortcut',
      content: 'When the list is empty, this shortcut starts your first offer directly.',
      placement: 'bottom',
      action: 'Click to start in Wizard Mode.',
      ifMissing: 'This shortcut appears only when there are no existing offer letters.',
    },
  ],
};

export const offerLettersRangeWalkthrough: WalkthroughConfig = {
  id: 'offer-letters-range',
  title: 'Blind Range Negotiation',
  category: 'admin',
  steps: [
    {
      target: 'offer-range-toggle',
      title: 'Switch to Salary Range',
      content: 'Instead of a fixed salary, you can negotiate within a range. Click "Salary Range" to reveal the min/max inputs.',
      placement: 'bottom',
      action: 'Select "Salary Range" to enable blind range negotiation on this offer.',
      expect: 'Two inputs appear: Min and Max salary.',
    },
    {
      target: 'offer-range-inputs',
      title: 'Set Your Range',
      content: 'Enter the salary band you\'re willing to offer. The candidate will never see these exact numbers — only whether the ranges overlap.',
      placement: 'bottom',
      action: 'Enter a Min and Max value, e.g. $140,000 – $160,000.',
    },
    {
      target: 'offer-send-range-btn',
      title: 'Send Range Offer',
      content: 'Once the range is saved, use this button to email the candidate a private magic link. They\'ll see your range and submit their own — without seeing the other\'s exact numbers.',
      placement: 'left',
      action: 'Click "Send Range Offer" and enter the candidate\'s email address.',
      ifMissing: 'This button appears after saving an offer with a salary range set.',
    },
    {
      target: 'offer-range-status',
      title: 'Track Negotiation Status',
      content: 'The badge here shows where the negotiation stands: Awaiting Candidate, Matched at $X, or No Match (with direction).',
      placement: 'right',
      expect: '"Awaiting candidate" while the link is open, "Matched at $X" on success, or "No match" with a direction hint.',
      ifMissing: 'Status appears after the range offer has been sent.',
    },
    {
      target: 'offer-renegotiate-btn',
      title: 'Re-negotiate',
      content: 'If the ranges didn\'t overlap, you can revise your range and send a new magic link — up to the configured maximum rounds. The candidate will receive a fresh link automatically.',
      placement: 'left',
      action: 'Click "Re-negotiate" to increment the round and optionally update your range.',
      ifMissing: 'This button only appears after a no-match result with rounds remaining.',
    },
  ],
};

export const erCopilotWalkthrough: WalkthroughConfig = {
  id: 'er-copilot',
  title: 'ER Copilot',
  category: 'admin',
  steps: [
    {
      target: 'er-new-case',
      title: 'Create New Case',
      content: 'Start a new employee relations investigation case.',
      placement: 'bottom',
      action: 'Click to open the case creation dialog.',
    },
    {
      target: 'er-tabs',
      title: 'Status Tabs',
      content: 'Filter cases by status — All, Open, In Review, Pending, or Closed.',
      placement: 'bottom',
      action: 'Click a tab to filter the case list.',
    },
    {
      target: 'er-case-list',
      title: 'Case List',
      content: 'All ER investigation cases. Click any case to open its detail page with full investigation tools.',
      placement: 'top',
      action: 'Click a case row to open the investigation workspace.',
      expect: 'Rows with case numbers, titles, and status indicators.',
      ifMissing: 'No cases found. Create your first case using the button above.',
    },
    {
      target: 'er-case-row',
      title: 'Case Row',
      content: 'Each row shows the case number, title, description, status, and creation date.',
      placement: 'bottom',
      action: 'Click to navigate to the case detail page.',
      ifMissing: 'Create a case first to see case rows.',
    },
    {
      target: 'er-status-col',
      title: 'Status Indicator',
      content: 'The colored dot and label show the current investigation status at a glance.',
      placement: 'left',
      expect: 'A colored dot with a status label (Open, In Review, Pending, or Closed).',
      ifMissing: 'Status appears on each case row.',
    },
  ],
};

export const timeOffWalkthrough: WalkthroughConfig = {
  id: 'time-off',
  title: 'PTO Management',
  category: 'admin',
  steps: [
    {
      target: 'pto-summary',
      title: 'Summary Cards',
      content: 'Quick overview showing pending requests awaiting approval and upcoming time off in the next 30 days.',
      placement: 'bottom',
      expect: 'Two cards with counts for pending approvals and upcoming time off.',
      ifMissing: 'Summary cards appear when PTO data is available.',
    },
    {
      target: 'pto-tabs',
      title: 'Filter Tabs',
      content: 'Filter requests by status — Pending, Approved, Denied, or view All.',
      placement: 'bottom',
      action: 'Click a tab to filter the request list.',
    },
    {
      target: 'pto-request-list',
      title: 'Request List',
      content: 'All PTO requests from your employees. Each row shows the employee, dates, hours, and status.',
      placement: 'top',
      expect: 'Request rows with employee names, date ranges, and action buttons.',
      ifMissing: 'No requests match the current filter.',
    },
    {
      target: 'pto-approve-btn',
      title: 'Approve Request',
      content: 'One-click approval for pending PTO requests.',
      placement: 'left',
      action: 'Click Approve to accept the request.',
      ifMissing: 'Approve buttons appear only on pending requests.',
    },
    {
      target: 'pto-deny-btn',
      title: 'Deny Request',
      content: 'Deny a request with a required reason. The employee will see the denial reason.',
      placement: 'left',
      action: 'Click Deny to open the denial dialog.',
      ifMissing: 'Deny buttons appear only on pending requests.',
    },
  ],
};

export const leaveManagementWalkthrough: WalkthroughConfig = {
  id: 'leave-management',
  title: 'Leave Management',
  category: 'admin',
  steps: [
    {
      target: 'leave-admin-filters',
      title: 'Filters & Refresh',
      content: 'Use status and leave-type filters to narrow requests, then refresh to pull the latest queue.',
      placement: 'bottom',
      action: 'Change filters to focus on a specific workflow stage.',
    },
    {
      target: 'leave-admin-list',
      title: 'Leave Request Queue',
      content: 'This sidebar lists leave cases. Selecting a row opens the full request details and actions.',
      placement: 'right',
      expect: 'Rows with employee, leave type, date, and current status.',
      ifMissing: 'No leave requests match the active filters.',
    },
    {
      target: 'leave-admin-detail',
      title: 'Selected Leave Case',
      content: 'Review the selected case summary, leave dates, and reason before taking status actions.',
      placement: 'left',
      ifMissing: 'Select a leave request from the queue to load case details.',
    },
    {
      target: 'leave-admin-actions',
      title: 'Case Actions',
      content: 'Approve, deny, activate, complete, and assign return-to-work tasks from this action bar.',
      placement: 'bottom',
      ifMissing: 'Actions appear after selecting a leave case.',
    },
    {
      target: 'leave-admin-deadlines',
      title: 'Deadline Tracking',
      content: 'Track required deadline events tied to the leave case and mark them complete or waived.',
      placement: 'left',
      ifMissing: 'Deadline tracking appears when Compliance Plus is enabled and a leave case is selected.',
    },
    {
      target: 'leave-admin-notices',
      title: 'Notice Generation',
      content: 'Generate leave notice documents directly from the case timeline for employee delivery.',
      placement: 'top',
      action: 'Choose a notice type and click Generate Notice.',
      ifMissing: 'Notice generation appears when Compliance Plus is enabled.',
    },
    {
      target: 'leave-admin-rtw-btn',
      title: 'Assign Return-To-Work Tasks',
      content: 'Create return-to-work onboarding tasks for the employee once leave is approved or active.',
      placement: 'left',
      ifMissing: 'This button appears only when the leave case status is Approved or Active.',
    },
  ],
};

export const accommodationsWalkthrough: WalkthroughConfig = {
  id: 'accommodations',
  title: 'Accommodations',
  category: 'admin',
  steps: [
    {
      target: 'accom-admin-toolbar',
      title: 'Filters & New Case',
      content: 'Filter accommodation cases by status, refresh data, and create new ADA interactive process cases.',
      placement: 'bottom',
      action: 'Use New Case to open the accommodation intake form.',
    },
    {
      target: 'accom-admin-case-list',
      title: 'Case List',
      content: 'All accommodation cases are listed here. Select a case to manage details, documents, and analysis.',
      placement: 'right',
      expect: 'Rows with case number, title, and status.',
      ifMissing: 'No accommodation cases exist yet. Start with New Case.',
    },
    {
      target: 'accom-admin-detail',
      title: 'Case Detail Editor',
      content: 'Update case status, disability category, requested accommodation, and final decision details.',
      placement: 'left',
      ifMissing: 'Select a case from the list to load the detail editor.',
    },
    {
      target: 'accom-admin-documents',
      title: 'Documents',
      content: 'Upload supporting files like medical certifications and interactive process notes.',
      placement: 'top',
      action: 'Pick a document type, then upload the file.',
      ifMissing: 'Document tools appear after selecting a case.',
    },
    {
      target: 'accom-admin-analysis',
      title: 'AI Analysis',
      content: 'Run suggestion, hardship, and essential-job-function analyses for faster decision support.',
      placement: 'top',
      action: 'Run each analysis as case information and evidence become available.',
      ifMissing: 'Analysis tools appear after selecting a case.',
    },
    {
      target: 'accom-admin-audit',
      title: 'Audit Log',
      content: 'Review the chronological audit trail of case updates and analysis events.',
      placement: 'top',
      ifMissing: 'Audit entries appear as the case is updated over time.',
    },
    {
      target: 'accom-admin-new-case-btn',
      title: 'Create Case',
      content: 'Start a new accommodation case and optionally link it to an existing leave request.',
      placement: 'left',
      action: 'Click New Case to launch the intake modal.',
    },
  ],
};

export const employeesWalkthrough: WalkthroughConfig = {
  id: 'employees',
  title: 'Employee Directory',
  category: 'admin',
  steps: [
    {
      target: 'emp-add-btn',
      title: 'Add Employee',
      content: 'Create a new employee record with name, email, work state, and employment details.',
      placement: 'bottom',
      action: 'Click to open the add employee form.',
    },
    {
      target: 'emp-bulk-btn',
      title: 'Bulk Upload',
      content: 'Upload a CSV file to add multiple employees at once. Download the template first.',
      placement: 'bottom',
      action: 'Click to open the bulk upload dialog.',
    },
    {
      target: 'emp-help-btn',
      title: 'Help Guide',
      content: 'Toggle the help panel for step-by-step instructions on managing employees.',
      placement: 'bottom',
      action: 'Click to show or hide the help panel.',
    },
    {
      target: 'emp-tabs',
      title: 'Status Filter',
      content: 'Filter employees by status — All, Active, Pending Invite, or Terminated.',
      placement: 'bottom',
      action: 'Click a tab to filter the employee list.',
    },
    {
      target: 'emp-list',
      title: 'Employee List',
      content: 'Your team directory. Click any row to view the full profile and manage onboarding.',
      placement: 'top',
      action: 'Click an employee to open their detail page.',
      expect: 'Employee rows with names, work states, onboarding progress, and status badges.',
      ifMissing: 'No employees found. Add your first employee using the button above.',
    },
    {
      target: 'emp-invite-btn',
      title: 'Send Portal Invite',
      content: 'Email an invitation link so the employee can access their self-service portal.',
      placement: 'left',
      action: 'Click Send Invite on an uninvited employee.',
      ifMissing: 'Invite buttons appear for employees without portal access.',
    },
    {
      target: 'emp-onboarding-col',
      title: 'Onboarding Progress',
      content: 'Track each employee\'s onboarding completion with a visual progress bar.',
      placement: 'left',
      expect: 'A progress bar with completed/total task counts.',
      ifMissing: 'Progress appears after onboarding tasks are assigned.',
    },
  ],
};

export const companySetupWalkthrough: WalkthroughConfig = {
  id: 'company-setup',
  title: 'Company Setup',
  category: 'admin',
  steps: [
    {
      target: 'company-setup-guide',
      title: 'Setup Walkthrough',
      content: 'Use this guided flow to configure your company profile and external integrations from one page.',
      placement: 'left',
      action: 'Click Show Me anytime to replay this guide.',
    },
    {
      target: 'company-info-form',
      title: 'Company Information',
      content: 'Keep your core profile accurate so downstream modules use the right company details.',
      placement: 'right',
      action: 'Update company name, industry, and size, then save changes.',
    },
    {
      target: 'company-logo-card',
      title: 'Company Logo',
      content: 'Upload your logo to keep internal documents and workflows branded consistently.',
      placement: 'left',
      action: 'Upload a PNG, JPG, or SVG under 5MB.',
    },
    {
      target: 'company-setup-card',
      title: 'Integrations Setup',
      content: 'This section centralizes onboarding integrations for your company account.',
      placement: 'top',
      expect: 'Google Workspace status, mode, and domain details.',
    },
    {
      target: 'company-google-configure-btn',
      title: 'Configure Google Workspace',
      content: 'Open full Google Workspace provisioning settings to connect credentials and test the integration.',
      placement: 'left',
      action: 'Click to open Google Workspace configuration.',
      ifMissing: 'This action appears for admin and client users on the company page.',
    },
  ],
};

export const googleWorkspaceWalkthrough: WalkthroughConfig = {
  id: 'google-workspace',
  title: 'Google Workspace Setup',
  category: 'admin',
  steps: [
    {
      target: 'google-workspace-guide',
      title: 'Setup Guide',
      content: 'Use this walkthrough to configure and validate Google Workspace provisioning.',
      placement: 'left',
      action: 'Click Show Me anytime to replay this setup guide.',
    },
    {
      target: 'google-workspace-status',
      title: 'Connection Status',
      content: 'Review your current connection state, domain, mode, and last tested timestamp before changing settings.',
      placement: 'bottom',
      expect: 'Status card showing connected/disconnected/error and environment details.',
    },
    {
      target: 'google-workspace-mode',
      title: 'Connection Mode',
      content: 'Pick the integration mode for your tenant: mock for dry runs, API token, or service account for production.',
      placement: 'bottom',
      action: 'Select the mode that matches your deployment plan.',
    },
    {
      target: 'google-workspace-domain',
      title: 'Primary Domain',
      content: 'Enter your primary Google Workspace domain (e.g., company.com). This is used to construct employee email addresses during provisioning.',
      placement: 'bottom',
    },
    {
      target: 'google-workspace-admin-email',
      title: 'Super Admin Email',
      content: 'The email address of a Super Admin in your Google Workspace. This account is used to authorize API requests.',
      placement: 'bottom',
    },
    {
      target: 'google-workspace-delegated-admin-email',
      title: 'Delegated Admin Email',
      content: 'For Service Account mode, this is the user account that the service account will impersonate. It must have the necessary admin privileges to manage users.',
      placement: 'bottom',
    },
    {
      target: 'google-workspace-org-unit',
      title: 'Default Organizational Unit',
      content: 'The path where new users will be created (e.g., "/Employees" or "/"). If left blank, users are created in the root unit.',
      placement: 'bottom',
    },
    {
      target: 'google-workspace-groups',
      title: 'Default Groups',
      content: 'Groups grant access to team resources. Enter the email addresses (e.g. all-hands@company.com) for mailing lists, shared drives, or calendars new hires should join.',
      placement: 'top',
    },
    {
      target: 'google-workspace-json',
      title: 'Service Account JSON',
      content: 'For Service Account mode, paste the full JSON key file generated from the Google Cloud Console. Ensure Domain-Wide Delegation is enabled for this service account.',
      placement: 'top',
      ifMissing: 'This field only appears when Service Account mode is selected.',
    },
    {
      target: 'google-workspace-token',
      title: 'Access Token',
      content: 'For API Token mode, paste your Google Admin API access token here.',
      placement: 'top',
      ifMissing: 'This field only appears when API Token mode is selected.',
    },
    {
      target: 'google-workspace-options',
      title: 'Provisioning Defaults',
      content: 'Set onboarding defaults like auto-provision and whether to run a connection test before save.',
      placement: 'top',
    },
    {
      target: 'google-workspace-save',
      title: 'Save Configuration',
      content: 'Save to persist settings and optionally run a connection test to verify credentials immediately.',
      placement: 'top',
      action: 'Click Save Connection after entering required fields.',
    },
  ],
};

export const onboardingCenterWalkthrough: WalkthroughConfig = {
  id: 'onboarding-center',
  title: 'Onboarding Center',
  category: 'admin',
  steps: [
    {
      target: 'onboarding-center-guide',
      title: 'Unified Onboarding Guide',
      content: 'Use this guide to move from integration setup to employee onboarding without leaving this page.',
      placement: 'left',
      action: 'Click Show Me anytime to replay this end-to-end flow.',
    },
    {
      target: 'onboarding-tab-workspace',
      title: 'Workspace Tab',
      content: 'Start in Workspace to configure integrations used during employee onboarding.',
      placement: 'bottom',
      action: 'Click Workspace if you are currently on another tab.',
    },
    {
      target: 'onboarding-workspace-google-card',
      title: 'Google Workspace Integration',
      content: 'Check current Google status, defaults, and connection health before provisioning new hires.',
      placement: 'bottom',
      expect: 'Connection badge and configuration details on the card.',
      ifMissing: 'Open the Workspace tab to see integration cards.',
    },
    {
      target: 'onboarding-configure-google',
      title: 'Configure Google',
      content: 'Open full Google provisioning settings for credentials, domain setup, and validation.',
      placement: 'left',
      action: 'Click Configure to open Google setup.',
      ifMissing: 'Google configure action is available on the Workspace tab.',
    },
    {
      target: 'onboarding-workspace-slack-card',
      title: 'Slack Integration',
      content: 'Prepare Slack onboarding defaults so invitation and channel assignment can be automated when Slack is enabled.',
      placement: 'bottom',
      ifMissing: 'Open the Workspace tab to view Slack setup.',
    },
    {
      target: 'onboarding-configure-slack',
      title: 'Configure Slack',
      content: 'Open the Slack setup page to configure workspace URL, channels, and invite defaults.',
      placement: 'left',
      action: 'Click Configure to manage Slack setup.',
      ifMissing: 'Slack configuration is available from the Workspace tab.',
    },
    {
      target: 'onboarding-tab-employees',
      title: 'Employees Tab',
      content: 'Switch here to add employees, send invites, and track onboarding completion progress.',
      placement: 'bottom',
      action: 'Click Employees to continue the flow after integrations are configured.',
    },
    {
      target: 'onboarding-tab-runs',
      title: 'Activity Tab',
      content: 'Use Activity to review provisioning run outcomes and retry failed attempts.',
      placement: 'bottom',
      action: 'Click Activity to open run history.',
    },
    {
      target: 'onboarding-runs-panel',
      title: 'Run Visibility',
      content: 'Provisioning run history and retry controls surface here so failures can be resolved quickly.',
      placement: 'top',
      ifMissing: 'Open the Activity tab to view the run panel.',
    },
  ],
};

export const brokerClientsWalkthrough: WalkthroughConfig = {
  id: 'broker-clients',
  title: 'Broker Client Onboarding',
  category: 'admin',
  steps: [
    {
      target: 'broker-clients-expire-btn',
      title: 'Expire Stale Setups',
      content: 'Expire setup invites that were never activated so your pipeline and reporting stay clean.',
      placement: 'left',
      action: 'Click to expire stale draft/invited records.',
    },
    {
      target: 'broker-clients-terms',
      title: 'Partner Terms Gate',
      content: 'Broker partner terms must be accepted before onboarding actions can proceed.',
      placement: 'bottom',
      ifMissing: 'This panel only appears when terms have not been accepted yet.',
    },
    {
      target: 'broker-clients-summary',
      title: 'Setup Funnel Summary',
      content: 'Track how many client setups are draft, invited, activated, expired, or cancelled.',
      placement: 'bottom',
      expect: 'Status cards showing setup funnel counts.',
    },
    {
      target: 'broker-clients-create-form',
      title: 'Create Client Setup',
      content: 'Pre-configure company details, contact info, and starter features before the client logs in.',
      placement: 'top',
      action: 'Complete this form to create a broker-managed onboarding setup.',
    },
    {
      target: 'broker-clients-feature-toggles',
      title: 'Preconfigured Features',
      content: 'Choose which modules should be enabled by default for this client at launch.',
      placement: 'top',
    },
    {
      target: 'broker-clients-invite-toggle',
      title: 'Invite Immediately',
      content: 'Enable this to send an onboarding invite as soon as the setup is created.',
      placement: 'top',
    },
    {
      target: 'broker-clients-setups-list',
      title: 'Client Setup Queue',
      content: 'Review setup status, copy invite links, and trigger invite/cancel actions per company.',
      placement: 'top',
      ifMissing: 'No setups exist yet. Create your first setup above.',
    },
  ],
};

export const brokerReportingWalkthrough: WalkthroughConfig = {
  id: 'broker-reporting',
  title: 'Broker Portfolio Reporting',
  category: 'admin',
  steps: [
    {
      target: 'broker-reporting-terms',
      title: 'Reporting Access Terms',
      content: 'Reporting remains locked until broker partner terms are accepted.',
      placement: 'bottom',
      ifMissing: 'This panel only appears if terms are still pending.',
    },
    {
      target: 'broker-reporting-summary',
      title: 'Portfolio Summary',
      content: 'Topline KPIs across your book: linked companies, active links, average compliance, and open actions.',
      placement: 'bottom',
      expect: 'Four summary cards with aggregate broker metrics.',
    },
    {
      target: 'broker-reporting-redaction',
      title: 'Redaction Notice',
      content: 'This feed is intentionally aggregate and privacy-safe to avoid employee-level PII exposure.',
      placement: 'bottom',
    },
    {
      target: 'broker-reporting-signals',
      title: 'Company Signals Table',
      content: 'Review each client company\'s compliance rate, open items, employee count, and risk signal.',
      placement: 'top',
      action: 'Use this table for renewal prep and proactive client retention conversations.',
    },
  ],
};

export const internalMobilityWalkthrough: WalkthroughConfig = {
  id: 'internal-mobility',
  title: 'Internal Mobility',
  category: 'admin',
  steps: [
    {
      target: 'internal-mobility-guide',
      title: 'Mobility Command Center',
      content: 'Use this workflow to publish internal opportunities and retain high-potential employees before they look externally.',
      placement: 'left',
      action: 'Click Show Me anytime to replay this walkthrough.',
    },
    {
      target: 'internal-mobility-wizard',
      title: 'Step-by-Step Wizard',
      content: 'This cycle wizard explains exactly what to do next and includes shortcuts to Create and Applications.',
      placement: 'bottom',
      action: 'Use Step and Current Step labels to track progress from setup to alignment.',
    },
    {
      target: 'internal-mobility-create-form',
      title: 'Create Opportunity',
      content: 'Create role or project opportunities with skills, department, and duration so employees can discover growth paths.',
      placement: 'bottom',
      action: 'Publish as Active when the opportunity is ready to be discoverable in the employee portal.',
    },
    {
      target: 'internal-mobility-opportunities-filters',
      title: 'Opportunity Filters',
      content: 'Filter by status and type to quickly review what is live, in draft, or closed.',
      placement: 'bottom',
      action: 'Use Refresh after updates to validate the latest state.',
    },
    {
      target: 'internal-mobility-opportunities-list',
      title: 'Opportunity List',
      content: 'Review each opportunity card, validate required skills, adjust status, and jump straight to matching applicants.',
      placement: 'top',
      ifMissing: 'No opportunities match the active filters. Create your first opportunity above.',
    },
    {
      target: 'internal-mobility-opportunity-view-apps',
      title: 'View Applications',
      content: 'Each opportunity card includes a button to filter the queue to just that opportunity and scroll to applications.',
      placement: 'top',
      ifMissing: 'This appears when at least one opportunity card is visible.',
    },
    {
      target: 'internal-mobility-applications-list',
      title: 'Application Queue',
      content: 'Track employee interest and progression from new applications through aligned or closed outcomes.',
      placement: 'top',
      ifMissing: 'Applications appear after employees apply through the portal experience.',
    },
    {
      target: 'internal-mobility-application-status',
      title: 'Status + Manager Signals',
      content: 'Move applications through stages and record manager notification to keep transitions coordinated and private.',
      placement: 'left',
      ifMissing: 'Status controls appear once at least one application exists.',
    },
    {
      target: 'internal-mobility-application-detail',
      title: 'Application Detail Panel',
      content: 'Open any application card to inspect submission context, notes, review timestamps, and manager-notified timing.',
      placement: 'top',
      ifMissing: 'Click "View Details" on an application to open this panel.',
    },
  ],
};
