import type { GuideKey, WalkthroughConfig } from '../types';
import {
  irListWalkthrough,
  irDashboardWalkthrough,
  irCreateWalkthrough,
  irCategorizationWalkthrough,
  irSeverityWalkthrough,
  irRootCauseWalkthrough,
  irRecommendationsWalkthrough,
  irSimilarWalkthrough,
} from './ir';
import {
  complianceWalkthrough,
  policiesWalkthrough,
  handbooksWalkthrough,
  handbookCreateWalkthrough,
  offerLettersWalkthrough,
  erCopilotWalkthrough,
  timeOffWalkthrough,
  leaveManagementWalkthrough,
  accommodationsWalkthrough,
  onboardingCenterWalkthrough,
  employeesWalkthrough,
  companySetupWalkthrough,
  googleWorkspaceWalkthrough,
  brokerClientsWalkthrough,
  brokerReportingWalkthrough,
} from './admin';
import {
  portalOnboardingWalkthrough,
  portalDocumentsWalkthrough,
  portalPTOWalkthrough,
  portalLeaveWalkthrough,
} from './portal';

export const WALKTHROUGH_CONFIGS: Record<GuideKey, WalkthroughConfig> = {
  'ir-list': irListWalkthrough,
  'ir-dashboard': irDashboardWalkthrough,
  'ir-create': irCreateWalkthrough,
  'ir-categorization': irCategorizationWalkthrough,
  'ir-severity': irSeverityWalkthrough,
  'ir-root-cause': irRootCauseWalkthrough,
  'ir-recommendations': irRecommendationsWalkthrough,
  'ir-similar': irSimilarWalkthrough,
  compliance: complianceWalkthrough,
  policies: policiesWalkthrough,
  handbooks: handbooksWalkthrough,
  'handbook-create': handbookCreateWalkthrough,
  'offer-letters': offerLettersWalkthrough,
  'er-copilot': erCopilotWalkthrough,
  'time-off': timeOffWalkthrough,
  'leave-management': leaveManagementWalkthrough,
  accommodations: accommodationsWalkthrough,
  'onboarding-center': onboardingCenterWalkthrough,
  employees: employeesWalkthrough,
  'company-setup': companySetupWalkthrough,
  'google-workspace': googleWorkspaceWalkthrough,
  'broker-clients': brokerClientsWalkthrough,
  'broker-reporting': brokerReportingWalkthrough,
  'portal-onboarding': portalOnboardingWalkthrough,
  'portal-documents': portalDocumentsWalkthrough,
  'portal-pto': portalPTOWalkthrough,
  'portal-leave': portalLeaveWalkthrough,
};
