import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { SchedulingCommercialSettings } from './SchedulingCommercialSettings'
import { landingMedia } from '../../api/admin/landingMedia'
import { EMPTY_COMMERCIAL, type CommercialUploadProgress } from '../../types/landingMedia'
vi.mock('../../api/admin/landingMedia', () => ({ landingMedia: { getAdmin: vi.fn(), uploadCommercial: vi.fn(), saveCommercial: vi.fn() } }))
beforeEach(() => {
  vi.clearAllMocks()
  vi.mocked(landingMedia.getAdmin).mockResolvedValue({ hero_video_url: null, hero_poster_url: null, sizzle_videos: [], customer_logos: [], testimonials: [], scheduling_commercial: EMPTY_COMMERCIAL })
})

describe('commercial admin', () => {
  it('opens every upload picker with Enter and Space after keyboard navigation', async () => {
    const user = userEvent.setup()
    render(<SchedulingCommercialSettings />)
    const save = screen.getByRole('button', { name: 'Save commercial' })
    await waitFor(() => expect(save).not.toBeDisabled())
    await user.tab()
    expect(screen.getByRole('link', { name: 'home page' })).toHaveFocus()
    await user.tab()
    expect(save).toHaveFocus()
    await user.tab()
    expect(screen.getByRole('checkbox', { name: 'Play the commercial with sound' })).toHaveFocus()

    for (const name of ['desktop commercial', 'mobile commercial', 'desktop poster', 'mobile poster', 'english captions']) {
      const button = screen.getByRole('button', { name: `Upload ${name}` })
      const input = screen.getByLabelText(`Choose ${name} file`)
      const openPicker = vi.spyOn(input, 'click').mockImplementation(() => {})
      await user.tab()
      expect(button).toHaveFocus()
      await user.keyboard('{Enter}')
      expect(openPicker).toHaveBeenCalledTimes(1)
      await user.keyboard(' ')
      expect(openPicker).toHaveBeenCalledTimes(2)
    }
  })
  it('uploads before enabling, then saves separately from the legacy form', async () => {
    const url = 'https://media.example.com/film.mp4'
    vi.mocked(landingMedia.uploadCommercial).mockResolvedValue(url)
    vi.mocked(landingMedia.saveCommercial).mockImplementation(async (data) => ({ ok: true, value: data }))
    render(<SchedulingCommercialSettings />)
    await waitFor(() => expect(screen.getByRole('button', { name: 'Save commercial' }).hasAttribute('disabled')).toBe(false))
    expect(screen.getByRole('checkbox', { name: 'Show the commercial on the home page' }).hasAttribute('disabled')).toBe(true)
    fireEvent.change(screen.getByLabelText('Choose desktop commercial file'), { target: { files: [new File(['video'], 'film.mp4', { type: 'video/mp4' })] } })
    await waitFor(() => expect(screen.getByRole('checkbox', { name: 'Show the commercial on the home page' }).hasAttribute('disabled')).toBe(false))
    expect(landingMedia.uploadCommercial).toHaveBeenCalledWith(expect.any(File), 'desktop_video', expect.any(Function))
    expect(landingMedia.saveCommercial).not.toHaveBeenCalled()
    fireEvent.click(screen.getByRole('checkbox', { name: 'Show the commercial on the home page' }))
    fireEvent.click(screen.getByRole('button', { name: 'Save commercial' }))
    await waitFor(() => expect(landingMedia.saveCommercial).toHaveBeenCalledWith({ ...EMPTY_COMMERCIAL, desktop_video_url: url, enabled: true }))
    expect(await screen.findByRole('status')).toBeTruthy()
  })
  it('saves the sound setting; sound is on by default and a legacy payload without it stays on', async () => {
    vi.mocked(landingMedia.getAdmin).mockResolvedValue({ hero_video_url: null, hero_poster_url: null, sizzle_videos: [], customer_logos: [], testimonials: [], scheduling_commercial: { enabled: false, desktop_video_url: null, mobile_video_url: null, desktop_poster_url: null, mobile_poster_url: null, captions_url: null } as never })
    vi.mocked(landingMedia.saveCommercial).mockImplementation(async (data) => ({ ok: true, value: data }))
    render(<SchedulingCommercialSettings />)
    const sound = screen.getByRole('checkbox', { name: 'Play the commercial with sound' }) as HTMLInputElement
    await waitFor(() => expect(sound.disabled).toBe(false))
    expect(sound.checked).toBe(true)
    fireEvent.click(sound)
    expect(screen.getByText(/plays silently only/)).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Save commercial' }))
    await waitFor(() => expect(landingMedia.saveCommercial).toHaveBeenCalledWith({ ...EMPTY_COMMERCIAL, sound_enabled: false }))
  })
  it('keeps save disabled if settings fail to load', async () => {
    vi.mocked(landingMedia.getAdmin).mockRejectedValue(new Error('offline'))
    render(<SchedulingCommercialSettings />)
    expect(await screen.findByRole('alert')).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Save commercial' }).hasAttribute('disabled')).toBe(true)
  })
  it('retains the prior commercial after a failed replacement', async () => {
    const url = 'https://media.example.com/prior.mp4'
    vi.mocked(landingMedia.getAdmin).mockResolvedValue({ hero_video_url: null, hero_poster_url: null, sizzle_videos: [], customer_logos: [], testimonials: [], scheduling_commercial: { ...EMPTY_COMMERCIAL, enabled: true, desktop_video_url: url } })
    vi.mocked(landingMedia.uploadCommercial).mockRejectedValue(new Error('Upload failed'))
    vi.mocked(landingMedia.saveCommercial).mockImplementation(async (data) => ({ ok: true, value: data }))
    render(<SchedulingCommercialSettings />)
    await waitFor(() => expect(screen.getByRole('button', { name: 'Save commercial' }).hasAttribute('disabled')).toBe(false))
    const user = userEvent.setup()
    const replace = screen.getByRole('button', { name: 'Replace desktop commercial' })
    const input = screen.getByLabelText('Choose desktop commercial file')
    const openPicker = vi.spyOn(input, 'click').mockImplementation(() => {})
    await user.tab()
    await user.tab()
    await user.tab()
    await user.tab()
    await user.tab()
    expect(replace).toHaveFocus()
    await user.keyboard('{Enter}')
    expect(openPicker).toHaveBeenCalledOnce()
    fireEvent.change(input, { target: { files: [new File(['video'], 'replacement.mp4', { type: 'video/mp4' })] } })
    expect(await screen.findByRole('alert')).toBeTruthy()
    fireEvent.click(screen.getByRole('button', { name: 'Save commercial' }))
    await waitFor(() => expect(landingMedia.saveCommercial).toHaveBeenCalledWith(expect.objectContaining({ enabled: true, desktop_video_url: url })))
  })
  it('shows the selected file and every upload phase, keeping save disabled until verification', async () => {
    let update!: (value: CommercialUploadProgress) => void
    let finish!: (url: string) => void
    vi.mocked(landingMedia.uploadCommercial).mockImplementation((_file, _slot, progress) => {
      update = progress
      return new Promise<string>((resolve) => { finish = resolve })
    })
    render(<SchedulingCommercialSettings />)
    const save = screen.getByRole('button', { name: 'Save commercial' })
    await waitFor(() => expect(save).toBeEnabled())
    const file = new File(['video'], 'cafe-1080p.mp4', { type: 'video/mp4' })
    Object.defineProperty(file, 'size', { value: 59_222_054 })
    fireEvent.change(screen.getByLabelText('Choose desktop commercial file'), { target: { files: [file] } })
    expect(screen.getByText('cafe-1080p.mp4')).toBeInTheDocument()
    expect(screen.getByText('56.5 MB')).toBeInTheDocument()
    expect(screen.getByRole('status')).toHaveTextContent('Preparing secure upload')
    expect(save).toBeDisabled()
    act(() => update({ phase: 'uploading', percent: 42 }))
    expect(screen.getByRole('progressbar')).toHaveAttribute('value', '42')
    expect(screen.getByRole('status')).toHaveTextContent('Uploading 42%')
    act(() => update({ phase: 'uploading', percent: 100 }))
    expect(screen.getByRole('status')).toHaveTextContent('Waiting for storage confirmation')
    act(() => update({ phase: 'verifying', percent: 100 }))
    expect(screen.getByRole('progressbar')).not.toHaveAttribute('value')
    expect(screen.getByRole('status')).toHaveTextContent('Verifying the file')
    expect(save).toBeDisabled()
    await act(async () => finish('https://media.example.com/film.mp4'))
    expect(save).toBeEnabled()
    expect(screen.getByRole('status')).toHaveTextContent('uploaded and verified')
    expect(landingMedia.saveCommercial).not.toHaveBeenCalled()
  })
  it.each(['size', 'format', 'empty'] as const)('rejects an invalid %s before any network upload', async (invalid) => {
    render(<SchedulingCommercialSettings />)
    await waitFor(() => expect(screen.getByRole('button', { name: 'Save commercial' })).toBeEnabled())
    const file = new File(invalid === 'empty' ? [] : ['video'], invalid === 'format' ? 'film.mov' : 'film.mp4', { type: 'video/mp4' })
    if (invalid === 'size') Object.defineProperty(file, 'size', { value: 151 * 1024 * 1024 })
    fireEvent.change(screen.getByLabelText('Choose desktop commercial file'), { target: { files: [file] } })
    expect(screen.getByRole('alert')).toHaveTextContent(invalid === 'format' ? 'MP4 or WEBM' : '150 MB')
    expect(landingMedia.uploadCommercial).not.toHaveBeenCalled()
  })
  it('explains a frontend/backend version mismatch instead of allowing a doomed upload', async () => {
    vi.mocked(landingMedia.getAdmin).mockResolvedValue({ hero_video_url: null, hero_poster_url: null, sizzle_videos: [], customer_logos: [], testimonials: [] })
    render(<SchedulingCommercialSettings />)
    expect(await screen.findByRole('alert')).toHaveTextContent('Update the server and reload')
    expect(screen.getByRole('button', { name: 'Upload desktop commercial' })).toBeDisabled()
    expect(screen.getByRole('button', { name: 'Save commercial' })).toBeDisabled()
  })
})
