"""initial schema

Revision ID: 294504605e28
Revises: 
Create Date: 2026-08-07 12:12:52.953130

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '294504605e28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_name', sa.String(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('spotify_id', sa.String(), nullable=True),
    sa.Column('apple_music_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artists')),
    sa.UniqueConstraint('name', name=op.f('uq_artists_name'))
    )
    op.create_table('contributors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('legal_name', sa.String(), nullable=True),
    sa.Column('ipi_number', sa.String(length=11), nullable=True),
    sa.Column('pro_affiliation', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contributors'))
    )
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('audio_master', 'artwork', 'royalty_statement', 'package', 'registration_export', 'rendered_video', name='filekind', native_enum=False), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('audio_master', 'artwork', 'royalty_statement', 'package', 'registration_export', 'rendered_video')", name=op.f('ck_files_kind')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_files_storage_key'))
    )
    op.create_table('isrc_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registrant_prefix', sa.String(length=5), nullable=False),
    sa.Column('year_digits', sa.String(length=2), nullable=False),
    sa.Column('next_designation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("id = 1", name=op.f('ck_isrc_config_singleton')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_isrc_config'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'done', 'failed')", name=op.f('ck_jobs_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_table('works',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('iswc', sa.String(length=11), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_works')),
    sa.UniqueConstraint('iswc', name=op.f('uq_works_iswc'))
    )
    op.create_table('recordings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('isrc', sa.String(length=12), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('recording_year', sa.Integer(), nullable=True),
    sa.Column('audio_file_id', sa.Uuid(), nullable=True),
    sa.Column('duration_seconds', sa.Numeric(precision=9, scale=3), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('audio_format', sa.String(), nullable=True),
    sa.Column('primary_artist_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['files.id'], name=op.f('fk_recordings_audio_file_id_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_artist_id'], ['artists.id'], name=op.f('fk_recordings_primary_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recordings')),
    sa.UniqueConstraint('isrc', name=op.f('uq_recordings_isrc'))
    )
    op.create_table('releases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_type', sa.Enum('album', 'ep', 'single', name='releasetype', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'packaged', 'delivered', 'released', name='releasestatus', native_enum=False), nullable=False),
    sa.Column('upc', sa.String(length=13), nullable=True),
    sa.Column('catalog_number', sa.String(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('original_release_date', sa.Date(), nullable=True),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('c_line', sa.String(), nullable=True),
    sa.Column('p_line', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('subgenre', sa.String(), nullable=True),
    sa.Column('territories', sa.String(), nullable=False),
    sa.Column('artwork_file_id', sa.Uuid(), nullable=True),
    sa.Column('primary_artist_id', sa.Uuid(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("release_type IN ('album', 'ep', 'single')", name=op.f('ck_releases_release_type')),
    sa.CheckConstraint("status IN ('draft', 'ready', 'packaged', 'delivered', 'released')", name=op.f('ck_releases_status')),
    sa.ForeignKeyConstraint(['artwork_file_id'], ['files.id'], name=op.f('fk_releases_artwork_file_id_files'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['primary_artist_id'], ['artists.id'], name=op.f('fk_releases_primary_artist_id_artists')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_releases')),
    sa.UniqueConstraint('catalog_number', name=op.f('uq_releases_catalog_number')),
    sa.UniqueConstraint('upc', name=op.f('uq_releases_upc'))
    )
    op.create_table('royalty_statements',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'parsing', 'parsed', 'failed', name='statement_status', native_enum=False), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('uploaded', 'parsing', 'parsed', 'failed')", name=op.f('ck_royalty_statements_status')),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_royalty_statements_file_id_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_royalty_statements'))
    )
    op.create_table('work_writers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('composer', 'lyricist', 'composer_lyricist', 'arranger', 'translator', name='writerrole', native_enum=False), nullable=False),
    sa.Column('share_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('publisher_name', sa.String(), nullable=True),
    sa.Column('publisher_share_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('composer', 'lyricist', 'composer_lyricist', 'arranger', 'translator')", name=op.f('ck_work_writers_role')),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], name=op.f('fk_work_writers_contributor_id_contributors')),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_work_writers_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_writers')),
    sa.UniqueConstraint('work_id', 'contributor_id', 'role', name='uq_work_writers_work_contributor_role')
    )
    op.create_table('credits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('producer', 'performer', 'mixer', 'mastering_engineer', 'recording_engineer', 'featured', 'remixer', 'other', name='creditrole', native_enum=False), nullable=False),
    sa.Column('credited_as', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('producer', 'performer', 'mixer', 'mastering_engineer', 'recording_engineer', 'featured', 'remixer', 'other')", name=op.f('ck_credits_role')),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], name=op.f('fk_credits_contributor_id_contributors')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_credits_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credits'))
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.Enum('export_package', 'youtube', 'soundcloud', name='deliverytarget', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'complete', 'failed', 'manual', name='deliverystatus', native_enum=False), nullable=False),
    sa.Column('package_file_id', sa.Uuid(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target IN ('export_package', 'youtube', 'soundcloud')", name=op.f('ck_deliveries_target')),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'complete', 'failed', 'manual')", name=op.f('ck_deliveries_status')),
    sa.ForeignKeyConstraint(['package_file_id'], ['files.id'], name=op.f('fk_deliveries_package_file_id_files')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_deliveries_release_id_releases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    op.create_table('master_splits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('contributor_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('producer', 'performer', 'mixer', 'mastering_engineer', 'recording_engineer', 'featured', 'remixer', 'other', name='creditrole', native_enum=False), nullable=True),
    sa.Column('share_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('producer', 'performer', 'mixer', 'mastering_engineer', 'recording_engineer', 'featured', 'remixer', 'other')", name=op.f('ck_master_splits_role')),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], name=op.f('fk_master_splits_contributor_id_contributors')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_master_splits_recording_id_recordings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_splits')),
    sa.UniqueConstraint('recording_id', 'contributor_id', name='uq_master_splits_recording_contributor')
    )
    op.create_table('recording_works',
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_recording_works_recording_id_recordings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_recording_works_work_id_works'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recording_id', 'work_id', name=op.f('pk_recording_works'))
    )
    op.create_table('registration_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.Enum('pro', 'mlc', 'soundexchange', 'distributor', name='regtarget', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'submitted', 'confirmed', 'not_applicable', name='regstatus', native_enum=False), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('export_file_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target IN ('pro', 'mlc', 'soundexchange', 'distributor')", name=op.f('ck_registration_tasks_target')),
    sa.CheckConstraint("status IN ('not_started', 'in_progress', 'submitted', 'confirmed', 'not_applicable')", name=op.f('ck_registration_tasks_status')),
    sa.ForeignKeyConstraint(['export_file_id'], ['files.id'], name=op.f('fk_registration_tasks_export_file_id_files')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_registration_tasks_release_id_releases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_tasks')),
    sa.UniqueConstraint('release_id', 'target', name='uq_registration_tasks_release_target')
    )
    op.create_table('release_artists',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('artist_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'featured', name='artistrole', native_enum=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('primary', 'featured')", name=op.f('ck_release_artists_role')),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_release_artists_artist_id_artists')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_release_artists_release_id_releases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_release_artists')),
    sa.UniqueConstraint('release_id', 'artist_id', 'role', name='uq_release_artists_release_artist_role')
    )
    op.create_table('royalty_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('statement_id', sa.Uuid(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('isrc', sa.String(), nullable=True),
    sa.Column('iswc', sa.String(), nullable=True),
    sa.Column('upc', sa.String(), nullable=True),
    sa.Column('title_raw', sa.String(), nullable=True),
    sa.Column('artist_raw', sa.String(), nullable=True),
    sa.Column('territory', sa.String(), nullable=True),
    sa.Column('units', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=True),
    sa.Column('work_id', sa.Uuid(), nullable=True),
    sa.Column('match_method', sa.Enum('isrc', 'iswc', 'manual', 'unmatched', name='matchmethod', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_method IN ('isrc', 'iswc', 'manual', 'unmatched')", name=op.f('ck_royalty_lines_match_method')),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_royalty_lines_recording_id_recordings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['royalty_statements.id'], name=op.f('fk_royalty_lines_statement_id_royalty_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], name=op.f('fk_royalty_lines_work_id_works'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_royalty_lines'))
    )
    op.create_index('ix_royalty_lines_isrc', 'royalty_lines', ['isrc'], unique=False)
    op.create_index('ix_royalty_lines_recording_id', 'royalty_lines', ['recording_id'], unique=False)
    op.create_index('ix_royalty_lines_statement_id', 'royalty_lines', ['statement_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('recording_id', sa.Uuid(), nullable=False),
    sa.Column('disc_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title_override', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], name=op.f('fk_tracks_recording_id_recordings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_tracks_release_id_releases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracks')),
    sa.UniqueConstraint('release_id', 'disc_number', 'position', deferrable=True, initially='DEFERRED', name='uq_tracks_release_disc_position')
    )
    op.create_table('upc_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=13), nullable=False),
    sa.Column('status', sa.Enum('available', 'assigned', name='upcstatus', native_enum=False), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('available', 'assigned')", name=op.f('ck_upc_codes_status')),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('fk_upc_codes_release_id_releases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_upc_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_upc_codes_code'))
    )
    op.create_table('delivery_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('delivery_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'complete', 'failed', 'manual', name='deliverystatus', native_enum=False), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'in_progress', 'complete', 'failed', 'manual')", name=op.f('ck_delivery_items_status')),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_delivery_items_delivery_id_deliveries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_delivery_items_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_items')),
    sa.UniqueConstraint('delivery_id', 'track_id', name='uq_delivery_items_delivery_track')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_items')
    op.drop_table('upc_codes')
    op.drop_table('tracks')
    op.drop_index('ix_royalty_lines_statement_id', table_name='royalty_lines')
    op.drop_index('ix_royalty_lines_recording_id', table_name='royalty_lines')
    op.drop_index('ix_royalty_lines_isrc', table_name='royalty_lines')
    op.drop_table('royalty_lines')
    op.drop_table('release_artists')
    op.drop_table('registration_tasks')
    op.drop_table('recording_works')
    op.drop_table('master_splits')
    op.drop_table('deliveries')
    op.drop_table('credits')
    op.drop_table('work_writers')
    op.drop_table('royalty_statements')
    op.drop_table('releases')
    op.drop_table('recordings')
    op.drop_table('works')
    op.drop_table('jobs')
    op.drop_table('isrc_config')
    op.drop_table('files')
    op.drop_table('contributors')
    op.drop_table('artists')
    # ### end Alembic commands ###
