"""Operational Autopilot defaults. These are business policy, never law."""

from decimal import Decimal

POLICY_SLOT_MINUTES = 30
POLICY_MIN_SHIFT_MINUTES = 240
POLICY_MAX_SHIFT_MINUTES = 540
POLICY_SHIFT_MINUTES_BOUNDS = (120, 720)
POLICY_BREAK_THRESHOLD_MINUTES = 360
POLICY_DEFAULT_BREAK_MINUTES = 30
POLICY_MIN_HISTORY_WEEKS = 3
POLICY_MIN_SPLH_OBSERVATIONS = 3
POLICY_SALES_HISTORY_DAYS = 91
POLICY_WEEKDAY_MEDIAN_MIN_OBS = 4
POLICY_CONFIDENCE_MEDIUM_OBS = 4
POLICY_CONFIDENCE_HIGH_OBS = 8
POLICY_INDEX_MIN = Decimal("0.5")
POLICY_INDEX_MAX = Decimal("2.0")
POLICY_RAIN_HURTS = ((80, Decimal("0.85")), (60, Decimal("0.90")))
POLICY_RAIN_HELPS = ((80, Decimal("1.15")), (60, Decimal("1.10")))
POLICY_MAX_DEMAND_SHIFTS = 200
POLICY_MAX_WINDOW_MINUTES = 1440 + 480
