import MarketingNav from './MarketingNav'
import MarketingFooter from './MarketingFooter'

const INK = '#1F1D1A'
const BG = '#F5F2ED'
const MUTED = '#6B6760'
const LINE = '#E4DED2'
const DISPLAY = 'var(--font-display)'

const LAST_UPDATED = 'May 1, 2025'

export default function TermsPage() {
  return (
    <div style={{ backgroundColor: BG, color: INK, colorScheme: 'light' }} className="min-h-screen">
      <MarketingNav />
      <main className="max-w-[800px] mx-auto px-6 sm:px-10 pt-32 pb-24">
        <p className="text-[10px] font-mono uppercase tracking-[0.4em] mb-4" style={{ color: '#b48228' }}>
          Legal // Terms
        </p>
        <h1 className="text-4xl font-bold tracking-tight mb-3" style={{ fontFamily: DISPLAY, fontWeight: 500 }}>
          Terms of Service
        </h1>
        <p className="text-sm mb-12" style={{ color: MUTED }}>Last updated {LAST_UPDATED}</p>

        <div className="space-y-10 text-sm leading-relaxed" style={{ color: INK }}>
          <Section title="1. Acceptance of Terms">
            <p>By accessing or using Matcha's platform, consulting services, or any related products (collectively, the "Services"), you agree to be bound by these Terms of Service. If you are using the Services on behalf of an organization, you represent that you have authority to bind that organization to these terms.</p>
          </Section>

          <Section title="2. Description of Services">
            <p>Matcha provides HR consulting, governance, risk and compliance (GRC) consulting, employee relations support, and AI-assisted HR software tools. The specific services available to you depend on your subscription plan and any executed service agreements.</p>
          </Section>

          <Section title="3. Accounts and Access">
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must notify us immediately of any unauthorized use. We reserve the right to terminate accounts that violate these terms or remain inactive for an extended period.</p>
          </Section>

          <Section title="4. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2" style={{ color: MUTED }}>
              <li>Use the Services for any unlawful purpose or in violation of applicable law</li>
              <li>Attempt to gain unauthorized access to any part of the platform or its infrastructure</li>
              <li>Transmit malicious code, spam, or any content that violates third-party rights</li>
              <li>Reverse engineer, decompile, or otherwise attempt to extract source code</li>
              <li>Resell or sublicense access to the Services without written authorization</li>
            </ul>
          </Section>

          <Section title="5. Intellectual Property">
            <p>All content, software, and materials provided through the Services are the intellectual property of Matcha, Inc. or its licensors. You retain ownership of data you submit; you grant Matcha a limited license to process that data solely to deliver the Services.</p>
          </Section>

          <Section title="6. Confidentiality">
            <p>Both parties agree to maintain the confidentiality of non-public information shared in connection with the Services. This obligation survives termination of your subscription or service agreement.</p>
          </Section>

          <Section title="7. Payment and Billing">
            <p>Subscription fees are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law or as expressly stated in your service agreement. We reserve the right to modify pricing with thirty (30) days' notice.</p>
          </Section>

          <Section title="8. Disclaimers">
            <p>The Services are provided "as is." Matcha makes no warranty that the Services will be error-free or uninterrupted. Content generated by AI tools is provided for informational purposes and does not constitute legal advice. You should consult qualified counsel for legal matters.</p>
          </Section>

          <Section title="9. Limitation of Liability">
            <p>To the maximum extent permitted by law, Matcha's total liability for any claim arising from the Services shall not exceed the fees paid by you in the twelve (12) months preceding the claim. In no event shall Matcha be liable for indirect, incidental, or consequential damages.</p>
          </Section>

          <Section title="10. Governing Law">
            <p>These Terms are governed by the laws of the State of Delaware, without regard to conflict of law principles. Any disputes shall be resolved by binding arbitration in accordance with AAA Commercial Arbitration Rules.</p>
          </Section>

          <Section title="11. Changes to These Terms">
            <p>We may update these Terms from time to time. We will notify you of material changes via email or in-platform notice at least fourteen (14) days before they take effect. Continued use of the Services after that date constitutes acceptance of the updated Terms.</p>
          </Section>

          <Section title="12. Contact">
            <p>Questions about these Terms? Reach us at <a href="mailto:legal@matchahq.com" className="underline underline-offset-2" style={{ color: INK }}>legal@matchahq.com</a>.</p>
          </Section>
        </div>
      </main>
      <MarketingFooter />
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <div
        className="pb-4 mb-5"
        style={{ borderBottom: `1px solid ${LINE}` }}
      >
        <h2 className="text-base font-semibold tracking-tight" style={{ color: INK }}>{title}</h2>
      </div>
      <div style={{ color: MUTED }}>{children}</div>
    </div>
  )
}
