#!/usr/bin/env python3
"""Build an exact, tenant-scoped PROD -> LOCAL replacement SQL file.

This is the data engine for pull-tenant-from-prod.sh. It opens production in
read-only mode, walks the live foreign-key graph from one companies row, and
writes SQL that:

* deletes only the existing local rows descended from that company;
* preserves the local companies row until it can be upserted (avoids touching
  excluded/global rows that may still reference the company);
* inserts/updates every production tenant-owned row parent-first; and
* inserts referenced shared parents only when missing, never overwriting them.

The generated SQL has no transaction control. The shell wrapper rehearses it
with ROLLBACK and applies it to the hard-validated local DSN in one transaction.
Production is never a SQL target.
"""
from __future__ import annotations

import argparse
import asyncio
import importlib.util
import json
import os
import re
import sys
import time
from dataclasses import dataclass
from pathlib import Path

import asyncpg


REPO_ROOT = Path(__file__).resolve().parent.parent
_EXPORT_PATH = Path(__file__).resolve().parent / "export-dev-data.py"


def _load_export_dev_data():
    spec = importlib.util.spec_from_file_location("export_dev_data", _EXPORT_PATH)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["export_dev_data"] = mod
    spec.loader.exec_module(mod)
    return mod


@dataclass(frozen=True)
class RowSnap:
    row: dict
    descend: bool


def _format_elapsed(seconds: float) -> str:
    minutes, secs = divmod(max(0, int(seconds)), 60)
    return f"{minutes:02d}:{secs:02d}"


def _key_where(pk: list[str], key: tuple, lit) -> str:
    return " AND ".join(f'"{col}" = {lit(value)}' for col, value in zip(pk, key))


def emit_delete(table: str, pk: list[str], keys: list[tuple], lit) -> str:
    """Delete a table's tenant rows in one statement (self-FKs stay valid)."""
    if not keys:
        raise ValueError("emit_delete requires at least one key")
    predicates = [_key_where(pk, key, lit) for key in sorted(keys, key=repr)]
    return f'DELETE FROM "{table}" WHERE ' + " OR ".join(
        f"({predicate})" for predicate in predicates
    ) + ";"


def build_replacement_sql(source: dict, target: dict, cols: dict, pks: dict,
                          fks: list[dict], export_mod) -> tuple[list[str], dict]:
    """Return SQL lines and summary for a prod-authoritative local replacement."""
    tables = sorted(set(source) | set(target))
    order, cyclic = export_mod.topo_order(tables, fks)
    if cyclic:
        raise RuntimeError(
            "FK cycle prevents a safely ordered tenant replacement: "
            + ", ".join(sorted(set(cyclic)))
        )

    lines = [
        "-- Generated by scripts/pull_tenant_from_prod.py — do not hand-edit.",
        "-- Direction: production (read-only) -> local development only.",
        "-- Tenant-owned rows are replaced; shared parents are insert-if-missing.",
        "",
    ]
    deleted_rows = 0
    deleted_tables = 0

    # Children first. The companies root is deliberately retained and later
    # upserted so excluded/global rows which reference it are not disturbed.
    for table in reversed(order):
        if table == "companies":
            continue
        pk = pks.get(table)
        owned_keys = [key for key, snap in target.get(table, {}).items() if snap.descend]
        if owned_keys:
            lines.append(emit_delete(table, pk, owned_keys, export_mod.lit))
            deleted_rows += len(owned_keys)
            deleted_tables += 1

    if deleted_rows:
        lines.append("")

    self_refs: dict[str, list[str]] = {}
    for fk in fks:
        if fk["child"] == fk["parent"]:
            self_refs.setdefault(fk["child"], []).append(fk["child_col"])

    inserted_owned = 0
    inserted_dependencies = 0
    for table in order:
        table_rows = source.get(table, {})
        if not table_rows:
            continue
        table_fixups = []
        lines.append(f"-- {table} ({len(table_rows)} rows)")
        for key in sorted(table_rows, key=repr):
            snap = table_rows[key]
            statement, fixup = _emit_upsert(
                table, cols[table], pks[table], snap.row, snap.descend,
                export_mod.lit, self_refs.get(table, []),
            )
            lines.append(statement)
            if fixup:
                table_fixups.append(fixup)
            if snap.descend:
                inserted_owned += 1
            else:
                inserted_dependencies += 1
        if table_fixups:
            lines.append(f"-- {table}: self-references, applied after all rows exist")
            lines.extend(table_fixups)
        lines.append("")

    summary = {
        "deleted_local_rows": deleted_rows,
        "deleted_local_tables": deleted_tables,
        "source_tenant_rows": inserted_owned,
        "source_dependency_rows": inserted_dependencies,
        "source_tables": sum(bool(rows) for rows in source.values()),
    }
    return lines, summary


def _emit_upsert(table: str, columns: list[str], pk: list[str], row: dict,
                 descended: bool, lit, self_ref_cols: list[str]) -> tuple[str, str | None]:
    values = []
    for col in columns:
        value = None if col in self_ref_cols and row.get(col) is not None else row.get(col)
        values.append(lit(value))
    column_list = ", ".join(f'"{col}"' for col in columns)
    if descended:
        conflict = "(" + ", ".join(f'"{col}"' for col in pk) + ")"
        updates = ", ".join(
            f'"{col}" = EXCLUDED."{col}"' for col in columns if col not in pk
        )
        suffix = f"DO UPDATE SET {updates}" if updates else "DO NOTHING"
        statement = (
            f'INSERT INTO "{table}" ({column_list}) VALUES ({", ".join(values)}) '
            f"ON CONFLICT {conflict} {suffix};"
        )
    else:
        # Shared users/catalogs can collide on a secondary unique key under a
        # different PK. Untargeted DO NOTHING preserves the local shared row.
        statement = (
            f'INSERT INTO "{table}" ({column_list}) VALUES ({", ".join(values)}) '
            "ON CONFLICT DO NOTHING;"
        )

    fixup = None
    updates = [
        f'"{col}" = {lit(row[col])}'
        for col in self_ref_cols if row.get(col) is not None
    ]
    if updates:
        key = tuple(row[col] for col in pk)
        fixup = (
            f'UPDATE "{table}" SET {", ".join(updates)} '
            f"WHERE {_key_where(pk, key, lit)};"
        )
    return statement, fixup


async def snapshot_tenant(conn, export_mod, cols, pks, fks, tenant_id: str,
                          *, include_global_dependencies: bool, side: str,
                          progress: bool) -> tuple[dict, object]:
    collector = export_mod.Collector(
        conn, cols, pks, fks, export_mod.DEFAULT_EXCLUDE,
        include_global_dependencies=include_global_dependencies,
    )
    started = time.monotonic()

    async def heartbeat():
        while True:
            await asyncio.sleep(10)
            row_count = sum(len(rows) for rows in collector.rows.values())
            print(
                f"   [{_format_elapsed(time.monotonic() - started)}] {side}: "
                f"{row_count:,} rows / {sum(bool(r) for r in collector.rows.values())} "
                f"tables; current {collector.last_table or 'starting'}",
                file=sys.stderr,
            )

    task = asyncio.create_task(heartbeat()) if progress else None
    try:
        company = await conn.fetchrow("SELECT * FROM companies WHERE id = $1", tenant_id)
        if company is None:
            return {}, collector
        await collector.collect("companies", dict(company), descend=True)

        snapshot = {}
        for table, rows in collector.rows.items():
            if not rows:
                continue
            pk = pks.get(table)
            owned_count = sum(descend for _, descend in rows.values())
            if not pk:
                if owned_count:
                    raise RuntimeError(
                        f'{side} table "{table}" has {owned_count} tenant row(s) but no primary key'
                    )
                continue
            text_rows = await export_mod.fetch_as_text(
                conn, table, cols[table], pk, list(rows.keys())
            )
            by_key = {tuple(str(row[col]) for col in pk): row for row in text_rows}
            table_snap = {}
            for key, (_, descend) in rows.items():
                text_key = tuple(str(value) for value in key)
                if text_key not in by_key:
                    raise RuntimeError(
                        f'{side} table "{table}" dropped a row during PK text conversion: {key!r}'
                    )
                table_snap[text_key] = RowSnap(by_key[text_key], descend)
            snapshot[table] = table_snap
        return snapshot, collector
    finally:
        if task:
            task.cancel()
            try:
                await task
            except asyncio.CancelledError:
                pass


async def load_unique_keys(conn) -> dict[str, list[list[str]]]:
    """Load usable non-partial, non-expression unique indexes (excluding PKs)."""
    rows = await conn.fetch(
        """
        SELECT tbl.relname AS table_name,
               idx.relname AS index_name,
               array_agg(att.attname ORDER BY ord.n) AS columns
        FROM pg_index i
        JOIN pg_class tbl ON tbl.oid = i.indrelid
        JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
        JOIN pg_class idx ON idx.oid = i.indexrelid
        JOIN LATERAL unnest(i.indkey) WITH ORDINALITY ord(attnum, n) ON true
        JOIN pg_attribute att ON att.attrelid = tbl.oid AND att.attnum = ord.attnum
        WHERE ns.nspname = 'public'
          AND i.indisunique
          AND NOT i.indisprimary
          AND i.indpred IS NULL
          AND i.indexprs IS NULL
        GROUP BY tbl.relname, idx.relname
        ORDER BY tbl.relname, idx.relname
        """
    )
    result: dict[str, list[list[str]]] = {}
    for row in rows:
        columns = list(row["columns"])
        if columns not in result.setdefault(row["table_name"], []):
            result[row["table_name"]].append(columns)
    return result


async def _fetch_local_match(conn, table: str, columns: list[str], pk: list[str],
                             unique_keys: list[list[str]], row: dict) -> dict | None:
    select = ", ".join(f'"{col}"::text AS "{col}"' for col in columns)

    async def lookup(key_columns: list[str]):
        if not key_columns or any(row.get(col) is None for col in key_columns):
            return None
        where = " AND ".join(
            f'"{col}"::text = ${index}' for index, col in enumerate(key_columns, 1)
        )
        return await conn.fetchrow(
            f'SELECT {select} FROM "{table}" WHERE {where} LIMIT 2',
            *(row[col] for col in key_columns),
        )

    exact = await lookup(pk)
    if exact:
        return dict(exact)

    matches = []
    for key_columns in unique_keys:
        match = await lookup(key_columns)
        if match:
            candidate = dict(match)
            candidate_pk = tuple(candidate[col] for col in pk)
            if all(tuple(existing[col] for col in pk) != candidate_pk for existing in matches):
                matches.append(candidate)
    if len(matches) > 1:
        identities = [tuple(match[col] for col in pk) for match in matches]
        raise RuntimeError(
            f'{table}: source dependency matches multiple local rows via unique keys: {identities}'
        )
    return matches[0] if matches else None


def rewrite_foreign_keys(row: dict, table: str, fks: list[dict],
                         mappings: dict[tuple[str, str, str], str]) -> dict:
    rewritten = dict(row)
    for fk in fks:
        if fk["child"] != table:
            continue
        value = rewritten.get(fk["child_col"])
        if value is None:
            continue
        replacement = mappings.get((fk["parent"], fk["parent_col"], value))
        if replacement is not None:
            rewritten[fk["child_col"]] = replacement
    return rewritten


async def reconcile_shared_dependencies(source: dict, dev_conn, cols: dict,
                                        pks: dict, fks: list[dict],
                                        unique_keys: dict[str, list[list[str]]]) -> tuple[dict, int]:
    """Map prod shared UUIDs onto equivalent local natural-key rows.

    Shared parents are never overwritten. If the same logical row already
    exists locally under another primary key (common for seeded catalogs),
    tenant/source FKs are rewritten to the local key and the prod dependency
    row is omitted from the generated INSERT set.
    """
    order, cyclic = _load_export_dev_data().topo_order(sorted(source), fks)
    if cyclic:
        raise RuntimeError(
            "FK cycle prevents shared dependency reconciliation: "
            + ", ".join(sorted(set(cyclic)))
        )

    mappings: dict[tuple[str, str, str], str] = {}
    mapped_rows: set[tuple[str, tuple]] = set()
    parent_ref_columns: dict[str, set[str]] = {}
    for fk in fks:
        parent_ref_columns.setdefault(fk["parent"], set()).add(fk["parent_col"])

    for table in order:
        for key in sorted(source.get(table, {}), key=repr):
            snap = source[table][key]
            candidate = rewrite_foreign_keys(snap.row, table, fks, mappings)
            source[table][key] = RowSnap(candidate, snap.descend)
            if snap.descend:
                continue
            local_row = await _fetch_local_match(
                dev_conn, table, cols[table], pks[table], unique_keys.get(table, []),
                candidate,
            )
            if not local_row:
                continue
            mapped_rows.add((table, key))
            for parent_col in parent_ref_columns.get(table, set()):
                source_value = candidate.get(parent_col)
                local_value = local_row.get(parent_col)
                if source_value is not None and local_value is not None:
                    mappings[(table, parent_col, source_value)] = local_value

    # Apply mappings discovered later in the same table (self-FKs) and rebuild
    # dictionary keys if a mapped FK is itself part of a composite PK.
    reconciled: dict = {}
    for table, rows in source.items():
        rebuilt = {}
        for key, snap in rows.items():
            if (table, key) in mapped_rows:
                continue
            row = rewrite_foreign_keys(snap.row, table, fks, mappings)
            new_key = tuple(row[col] for col in pks[table])
            if new_key in rebuilt:
                raise RuntimeError(
                    f"{table}: dependency remapping collapsed two source rows onto {new_key!r}"
                )
            rebuilt[new_key] = RowSnap(row, snap.descend)
        if rebuilt:
            reconciled[table] = rebuilt
    return reconciled, len(mapped_rows)


async def resolve_tenant(prod_conn, dev_conn, selector: str):
    if re.fullmatch(r"[0-9a-fA-F-]{36}", selector):
        prod_rows = await prod_conn.fetch(
            "SELECT id::text, name, is_test FROM companies WHERE id = $1", selector
        )
    else:
        prod_rows = await prod_conn.fetch(
            "SELECT id::text, name, is_test FROM companies WHERE lower(name) = lower($1)",
            selector,
        )
    if not prod_rows:
        raise RuntimeError(f"no production company matched {selector!r}")
    if len(prod_rows) > 1:
        choices = ", ".join(f"{row['name']} ({row['id']})" for row in prod_rows)
        raise RuntimeError(f"multiple production companies matched {selector!r}: {choices}")

    tenant = prod_rows[0]
    local_name_collision = await dev_conn.fetchrow(
        "SELECT id::text, name FROM companies WHERE lower(name) = lower($1) AND id <> $2::uuid",
        tenant["name"], tenant["id"],
    )
    if local_name_collision:
        raise RuntimeError(
            f"local company name collision: {local_name_collision['name']} "
            f"({local_name_collision['id']}) has the production tenant's name"
        )
    return tenant


def _relevant_schema_drift(source: dict, target: dict, prod_cols: dict,
                           dev_cols: dict, prod_pks: dict, dev_pks: dict) -> list[str]:
    problems = []
    for table in sorted(set(source) | set(target)):
        if table not in prod_cols:
            problems.append(f'{table}: missing on production')
            continue
        if table not in dev_cols:
            problems.append(f'{table}: missing locally')
            continue
        prod_only = sorted(set(prod_cols[table]) - set(dev_cols[table]))
        dev_only = sorted(set(dev_cols[table]) - set(prod_cols[table]))
        if prod_only or dev_only:
            problems.append(f"{table}: prod-only columns {prod_only}; local-only columns {dev_only}")
        if prod_pks.get(table) != dev_pks.get(table):
            problems.append(
                f"{table}: primary key differs (prod {prod_pks.get(table)}, local {dev_pks.get(table)})"
            )
    return problems


async def run(args) -> int:
    export_mod = _load_export_dev_data()
    print("Connecting to production (read-only) and local development...", file=sys.stderr)
    prod_conn = await asyncpg.connect(args.prod_dsn)
    dev_conn = await asyncpg.connect(args.dev_dsn)
    try:
        # Defense in depth: even an accidental future mutation added to this
        # engine cannot write through the production connection.
        await prod_conn.execute("SET default_transaction_read_only = on")
        prod_cols, prod_pks, prod_fks, prod_composite = await export_mod.load_schema(prod_conn)
        dev_cols, dev_pks, dev_fks, dev_composite = await export_mod.load_schema(dev_conn)
        dev_unique_keys = await load_unique_keys(dev_conn)
        tenant = await resolve_tenant(prod_conn, dev_conn, args.tenant)
        tenant_id = tenant["id"]
        print(
            f"Resolved: {tenant['name']} ({tenant_id}), is_test={tenant['is_test']}",
            file=sys.stderr,
        )

        print("Walking production tenant graph and required shared parents...", file=sys.stderr)
        source, source_collector = await snapshot_tenant(
            prod_conn, export_mod, prod_cols, prod_pks, prod_fks, tenant_id,
            include_global_dependencies=True, side="production", progress=args.progress,
        )
        print("Walking existing local tenant graph...", file=sys.stderr)
        target, target_collector = await snapshot_tenant(
            dev_conn, export_mod, dev_cols, dev_pks, dev_fks, tenant_id,
            include_global_dependencies=False, side="local", progress=args.progress,
        )

        problems = _relevant_schema_drift(
            source, target, prod_cols, dev_cols, prod_pks, dev_pks
        )
        relevant = set(source) | set(target)
        composite = {
            (child, parent, name)
            for child, parent, name in prod_composite + dev_composite
            if parent in relevant or child in relevant
        }
        if composite:
            problems.extend(
                f"{child} -> {parent}: composite FK {name} is not safely walkable"
                for child, parent, name in sorted(composite)
            )
        if problems:
            raise RuntimeError("relevant schema is not safe to transfer:\n  " + "\n  ".join(problems))

        source, remapped_dependencies = await reconcile_shared_dependencies(
            source, dev_conn, dev_cols, dev_pks, dev_fks, dev_unique_keys
        )

        lines, summary = build_replacement_sql(
            source, target, prod_cols, prod_pks, prod_fks, export_mod
        )
        output = Path(args.out)
        output.write_text("\n".join(lines).rstrip() + "\n")
        os.chmod(output, 0o600)

        summary.update({
            "tenant_id": tenant_id,
            "tenant_name": tenant["name"],
            "is_test": tenant["is_test"],
            "output": str(output),
            "excluded_tables": sorted(export_mod.DEFAULT_EXCLUDE),
            "skipped_local_global_rows": sum(
                len(ids) for ids in target_collector.skipped_global.values()
            ),
            "remapped_shared_dependencies": remapped_dependencies,
            "production_shared_dependencies": sum(
                1 for rows in source.values()
                for snap in rows.values() if not snap.descend
            ),
        })
        if args.summary_out:
            summary_path = Path(args.summary_out)
            summary_path.write_text(json.dumps(summary, indent=2) + "\n")
            os.chmod(summary_path, 0o600)
        print(
            f"Built {summary['source_tenant_rows']:,} tenant rows across "
            f"{summary['source_tables']} tables plus "
            f"{summary['source_dependency_rows']:,} new shared dependencies "
            f"({remapped_dependencies:,} mapped to existing local rows); "
            f"will replace {summary['deleted_local_rows']:,} existing local tenant rows.",
            file=sys.stderr,
        )
        return 0
    finally:
        await dev_conn.close()
        await prod_conn.close()


async def _main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tenant", required=True, help="exact company name or UUID")
    parser.add_argument("--prod-dsn", default=os.getenv("PROD_DATABASE_URL"))
    parser.add_argument(
        "--dev-dsn",
        default=os.getenv(
            "DEV_DATABASE_URL",
            "postgresql://matcha:matcha_dev@127.0.0.1:5432/matcha",
        ),
    )
    parser.add_argument("--out", required=True)
    parser.add_argument("--summary-out")
    parser.add_argument("--progress", action="store_true")
    args = parser.parse_args()
    if not args.prod_dsn:
        parser.error("--prod-dsn or PROD_DATABASE_URL is required")
    try:
        return await run(args)
    except (asyncpg.PostgresError, OSError, RuntimeError, ValueError) as exc:
        print(f"FAILED: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(asyncio.run(_main()))
