"""Setup-concierge action registry (migration zzzzcappe27).

The dashboard Merlin panel is confirm-first: unlike the page editor's ops
(which fold onto client state and never touch the DB until Save), everything
here is a real server-row write — a new page, a product, a promo banner. The
model never writes directly; it PROPOSES via `stage_action`, the entry lands
in the setup conversation's `staged_actions` JSONB column with
`status='proposed'`, and only an explicit later confirmation (chat or a REST
click) runs `execute_setup_action`. This is the same plan-then-approve shape
as matcha Huume's `evaluate_huume_action`, reimplemented from scratch here —
cappe is a parallel stack and must not import matcha code.

Each `SetupActionSpec` mirrors the `MerlinOp` registry-as-data pattern in
`.ops` (validate + a human summary + prompt text all live on one entry, so
the prompt can't drift from what's actually enforced), with one addition:
`gate` takes the NORMALIZED PAYLOAD too, not just plan/entitlements — a
`create_product` proposal's entitlement check depends on the fulfillment kind
the model is actually asking for, not just the account's plan.

Two-phase evaluation, both pure/DB-free (`evaluate_setup_stage`,
`evaluate_setup_execute`) so they're unit-testable without a database and so
the SAME entitlement message a user sees at stage time ("your plan can only
sell X") is generated by the same code path that authoritatively re-checks it
at execute time — one function, not two copies that can drift.

Cache invalidation and conversation persistence are deliberately NOT done
here: `execute_setup_action` only writes the row this action is about.
Callers (routes/merlin_setup.py, setup_agent.py) own `invalidate_render_cache`
(a routes/-layer function — services/ must never import routes/) and
`store.mutate_staged_actions` (the row-locked queue write).
"""
from __future__ import annotations

import json
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Literal, Optional
from uuid import UUID, uuid4

from ..common import loads, slugify
from ..design_gate import is_premium_plan
from ..directory import refresh_site_search
from ..entitlements import Entitlements, resolve_entitlements
from .catalog import BLOCK_FIELDS, BLOCK_TYPES
from .ops import _field_value_error

# ---------------------------------------------------------------------------
# Shared block-content validation (the add_block content-filter rules from
# .ops._v_add_block, minus the same-turn-id/ctx machinery that op needs and
# this doesn't — a staged action always stands alone).
# ---------------------------------------------------------------------------

_MAX_BLOCKS_PER_ACTION = 12


def _validate_block(raw: Any) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(raw, dict):
        return None, "each block must be an object"
    btype = raw.get("type")
    # canvas is structural (grid/elements), not field-based — the concierge
    # doesn't build them (same reasoning as the v1 scope cut on canvas ops).
    if not isinstance(btype, str) or btype not in BLOCK_TYPES or btype == "canvas":
        return None, f"unsupported block type '{raw.get('type')}'"
    allowed = BLOCK_FIELDS.get(btype, {})
    content = {
        k: v for k, v in raw.items()
        if k != "type" and k in allowed and _field_value_error(v, allowed[k], btype, k) is None
    }
    return {"type": btype, **content}, None


def _validate_blocks(raw: Any) -> tuple[Optional[list[dict[str, Any]]], Optional[str]]:
    if raw is None:
        return [], None
    if not isinstance(raw, list) or not raw:
        return None, "'blocks' must be a non-empty list"
    if len(raw) > _MAX_BLOCKS_PER_ACTION:
        return None, f"at most {_MAX_BLOCKS_PER_ACTION} blocks per action"
    out: list[dict[str, Any]] = []
    for item in raw:
        block, err = _validate_block(item)
        if err:
            return None, err
        out.append(block)
    return out, None


def _gate_none(payload: dict[str, Any], entitlements: Entitlements, plan: str) -> Optional[str]:
    return None


# ---------------------------------------------------------------------------
# create_page — server-side mirror of client/src/cappe/data/cappePagePresets.ts.
# The client presets never reach the concierge (it has no open editor to hand
# them to); this is its own copy so the two libraries can diverge in wording
# without either needing the other to change.
# ---------------------------------------------------------------------------

SETUP_PAGE_PRESETS: dict[str, dict[str, Any]] = {
    "shop": {
        "title": "Shop",
        "blocks": [
            {"type": "hero", "heading": "Shop the collection", "subheading": "Browse our latest products — secure checkout, fast fulfilment.", "style": "centered", "cta": "Browse products", "ctaHref": "#shop"},
            {"type": "store", "heading": "Featured products", "subheading": "Hand-picked favourites from our catalogue."},
            {"type": "features", "heading": "Why shop with us", "items": [
                {"icon": "🚚", "title": "Fast shipping", "body": "Orders ship within 1–2 business days."},
                {"icon": "↩️", "title": "Easy returns", "body": "30-day, no-questions-asked returns."},
                {"icon": "🔒", "title": "Secure checkout", "body": "Encrypted payments you can trust."},
            ]},
            {"type": "newsletter", "heading": "Get 10% off your first order", "subheading": "Join the list for early drops and members-only deals."},
        ],
    },
    "about": {
        "title": "About",
        "blocks": [
            {"type": "hero", "heading": "About us", "subheading": "The people, the mission, and why we do what we do.", "style": "split"},
            {"type": "split", "eyebrow": "Our story", "heading": "How it started", "body": "Share the origin story — what sparked this, the problem you set out to solve, and where you are today.", "bullets": ["Founded with a clear purpose", "Built on craft and care", "Growing with our community"]},
            {"type": "features", "heading": "What we stand for", "items": [
                {"icon": "✦", "title": "Quality first", "body": "We sweat the details so you don't have to."},
                {"icon": "◆", "title": "Honest & open", "body": "Transparent pricing and straight talk."},
                {"icon": "▲", "title": "Customer-obsessed", "body": "Your experience drives every decision."},
            ]},
            {"type": "gallery", "heading": "Behind the scenes", "images": []},
            {"type": "cta", "heading": "Want to work with us?", "subheading": "We'd love to hear from you.", "cta": "Get in touch", "ctaHref": "/p/contact"},
        ],
    },
    "contact": {
        "title": "Contact",
        "blocks": [
            {"type": "hero", "heading": "Get in touch", "subheading": "Questions, quotes, or just to say hi — we reply fast.", "style": "minimal"},
            {"type": "contact", "heading": "Send a message", "subheading": "Fill in the form and we'll get back to you.", "fields": ["name", "email", "message"], "formSlug": "contact"},
            {"type": "map", "heading": "Find us"},
        ],
    },
    "services": {
        "title": "Services",
        "blocks": [
            {"type": "hero", "heading": "Services", "subheading": "Everything we offer, and how we can help.", "style": "centered", "cta": "Book a session", "ctaHref": "#book"},
            {"type": "features", "heading": "What we offer", "items": [
                {"icon": "✦", "title": "Service one", "body": "Describe the outcome a client gets."},
                {"icon": "◆", "title": "Service two", "body": "Describe the outcome a client gets."},
                {"icon": "▲", "title": "Service three", "body": "Describe the outcome a client gets."},
            ]},
            {"type": "pricing", "heading": "Pricing", "plans": [
                {"name": "Starter", "price": "$0", "period": "/mo", "features": ["Feature one", "Feature two"], "cta": "Choose"},
                {"name": "Pro", "price": "$24", "period": "/mo", "features": ["Everything in Starter", "Feature three", "Feature four"], "cta": "Choose", "highlighted": True},
            ]},
            {"type": "cta", "heading": "Ready to start?", "cta": "Book now", "ctaHref": "#book"},
        ],
    },
}


def _validate_create_page(payload: dict[str, Any]) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(payload, dict):
        return None, "invalid payload"
    title = payload.get("title")
    if not isinstance(title, str) or not (1 <= len(title.strip()) <= 255):
        return None, "'title' must be 1-255 characters"
    preset = payload.get("preset")
    if preset is not None and preset not in SETUP_PAGE_PRESETS:
        return None, f"unknown preset '{preset}' — expected one of: {', '.join(sorted(SETUP_PAGE_PRESETS))}"
    blocks: Optional[list[dict[str, Any]]] = None
    if preset is None:
        blocks, err = _validate_blocks(payload.get("blocks"))
        if err:
            return None, err
    return {"title": title.strip(), "preset": preset, "blocks": blocks}, None


def _summary_create_page(payload: dict[str, Any]) -> str:
    if payload.get("preset"):
        return f'Create a "{payload["title"]}" page using the {payload["preset"]} layout'
    n = len(payload.get("blocks") or [])
    return f'Create a "{payload["title"]}" page with {n} section{"s" if n != 1 else ""}'


async def _execute_create_page(conn, site: dict[str, Any], account: Any, payload: dict[str, Any]) -> dict[str, Any]:
    site_id = site["id"]
    base = slugify(payload["title"])
    slug = base
    n = 1
    while await conn.fetchval(
        "SELECT 1 FROM cappe_pages WHERE site_id = $1 AND slug = $2", site_id, slug
    ):
        n += 1
        slug = f"{base}-{n}"

    preset_key = payload.get("preset")
    if preset_key:
        blocks = deepcopy(SETUP_PAGE_PRESETS[preset_key]["blocks"])
    else:
        blocks = payload.get("blocks") or []

    sort_order = await conn.fetchval(
        "SELECT COALESCE(MAX(sort_order), -1) + 1 FROM cappe_pages WHERE site_id = $1", site_id
    )
    row = await conn.fetchrow(
        """INSERT INTO cappe_pages (site_id, title, slug, content, sort_order, status)
           VALUES ($1, $2, $3, $4, $5, 'draft')
           RETURNING id, title, slug""",
        site_id, payload["title"], slug, json.dumps({"blocks": blocks}), sort_order,
    )
    return {"page_id": str(row["id"]), "title": row["title"], "slug": row["slug"]}


class SetupActionError(Exception):
    """Raised by an action's `execute` for a referential failure discovered
    only at execute time (e.g. the target page was deleted after staging).
    Caught by `execute_setup_action` and turned into a `blocked` outcome —
    never a raw 500 to the panel."""


# ---------------------------------------------------------------------------
# add_blocks — append pre-built sections to an EXISTING page. The sanctioned
# exception to client-state-is-truth: the dashboard has no open editor for
# these ops to fold onto, so this writes `cappe_pages.content` directly, the
# same table the page editor's own PUT persists to.
# ---------------------------------------------------------------------------

def _validate_add_blocks(payload: dict[str, Any]) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(payload, dict):
        return None, "invalid payload"
    page_id = payload.get("page_id")
    if not isinstance(page_id, str):
        return None, "'page_id' is required"
    try:
        UUID(page_id)
    except (ValueError, AttributeError, TypeError):
        return None, "'page_id' must be a valid id"
    blocks, err = _validate_blocks(payload.get("blocks"))
    if err or not blocks:
        return None, err or "'blocks' must be a non-empty list"
    at = payload.get("at")
    if at is not None and (not isinstance(at, int) or isinstance(at, bool) or at < 0):
        return None, "'at' must be a non-negative index"
    return {"page_id": page_id, "blocks": blocks, "at": at}, None


def _summary_add_blocks(payload: dict[str, Any]) -> str:
    types = ", ".join(b["type"] for b in payload["blocks"])
    n = len(payload["blocks"])
    return f"Add {n} section{'s' if n != 1 else ''} to the page ({types})"


async def _execute_add_blocks(conn, site: dict[str, Any], account: Any, payload: dict[str, Any]) -> dict[str, Any]:
    page_id = UUID(payload["page_id"])
    row = await conn.fetchrow(
        "SELECT content FROM cappe_pages WHERE id = $1 AND site_id = $2 FOR UPDATE",
        page_id, site["id"],
    )
    if row is None:
        raise SetupActionError("That page doesn't exist anymore.")
    content = loads(row["content"])
    existing = content.get("blocks") if isinstance(content.get("blocks"), list) else []
    at = payload.get("at")
    insert_at = len(existing) if at is None else min(max(at, 0), len(existing))
    content["blocks"] = existing[:insert_at] + payload["blocks"] + existing[insert_at:]
    await conn.execute(
        "UPDATE cappe_pages SET content = $2, updated_at = NOW() WHERE id = $1",
        page_id, json.dumps(content),
    )
    return {"page_id": str(page_id), "added": len(payload["blocks"])}


# ---------------------------------------------------------------------------
# create_product
# ---------------------------------------------------------------------------

_FULFILLMENTS = frozenset({"physical", "digital", "service", "booking"})


def _validate_create_product(payload: dict[str, Any]) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(payload, dict):
        return None, "invalid payload"
    name = payload.get("name")
    if not isinstance(name, str) or not (1 <= len(name.strip()) <= 255):
        return None, "'name' must be 1-255 characters"
    fulfillment = payload.get("fulfillment", "physical")
    if fulfillment not in _FULFILLMENTS:
        return None, "'fulfillment' must be one of: physical, digital, service, booking"
    price_cents = payload.get("price_cents", 0)
    if not isinstance(price_cents, int) or isinstance(price_cents, bool) or price_cents < 0:
        return None, "'price_cents' must be a non-negative integer (cents)"
    description = payload.get("description")
    if description is not None and not isinstance(description, str):
        return None, "'description' must be text"
    digital_file_url = payload.get("digital_file_url")
    if digital_file_url is not None and not isinstance(digital_file_url, str):
        return None, "'digital_file_url' must be text"
    category = payload.get("category")
    if category is not None and (not isinstance(category, str) or len(category) > 120):
        return None, "'category' must be at most 120 characters"
    return {
        "name": name.strip(), "fulfillment": fulfillment, "price_cents": price_cents,
        "description": description, "digital_file_url": digital_file_url, "category": category,
    }, None


def _gate_create_product(payload: dict[str, Any], entitlements: Entitlements, plan: str) -> Optional[str]:
    fulfillment = payload.get("fulfillment", "physical")
    if fulfillment in entitlements.allowed_fulfillment:
        return None
    allowed = ", ".join(sorted(entitlements.allowed_fulfillment)) or "nothing yet"
    return (
        f"Your {entitlements.plan_name} plan can only sell: {allowed}. "
        "Want to set this up as one of those instead, or upgrade first?"
    )


def _summary_create_product(payload: dict[str, Any]) -> str:
    price = f"${payload['price_cents'] / 100:.2f}" if payload["price_cents"] else "free"
    return f'Sell "{payload["name"]}" ({payload["fulfillment"]}, {price})'


async def _execute_create_product(conn, site: dict[str, Any], account: Any, payload: dict[str, Any]) -> dict[str, Any]:
    # A digital good with no file yet would be a sale with nothing to deliver
    # — created as a draft so it can't be bought until the seller finishes it
    # in Shop. Everything else is safe to activate straight from chat.
    status_ = "draft" if payload["fulfillment"] == "digital" and not payload.get("digital_file_url") else "active"
    row = await conn.fetchrow(
        """INSERT INTO cappe_products
               (site_id, name, description, price_cents, status, fulfillment, digital_file_url, category)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
           RETURNING id, name, status, fulfillment""",
        site["id"], payload["name"], payload.get("description"), payload["price_cents"],
        status_, payload["fulfillment"], payload.get("digital_file_url"), payload.get("category"),
    )
    await refresh_site_search(conn, site["id"])
    return {"product_id": str(row["id"]), "name": row["name"], "status": row["status"]}


# ---------------------------------------------------------------------------
# create_booking_type — not fulfillment-gated: every plan may take bookings
# (see entitlements.py's seeded catalog — service/booking is the one
# fulfillment kind every plan, including creator, allows).
# ---------------------------------------------------------------------------

def _validate_create_booking_type(payload: dict[str, Any]) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(payload, dict):
        return None, "invalid payload"
    name = payload.get("name")
    if not isinstance(name, str) or not (1 <= len(name.strip()) <= 255):
        return None, "'name' must be 1-255 characters"
    duration = payload.get("duration_minutes", 30)
    if not isinstance(duration, int) or isinstance(duration, bool) or not (5 <= duration <= 1440):
        return None, "'duration_minutes' must be between 5 and 1440"
    price_cents = payload.get("price_cents")
    if price_cents is not None and (not isinstance(price_cents, int) or isinstance(price_cents, bool) or price_cents < 0):
        return None, "'price_cents' must be a non-negative integer (cents)"
    description = payload.get("description")
    if description is not None and not isinstance(description, str):
        return None, "'description' must be text"
    category = payload.get("category")
    if category is not None and (not isinstance(category, str) or len(category) > 120):
        return None, "'category' must be at most 120 characters"
    return {
        "name": name.strip(), "duration_minutes": duration, "price_cents": price_cents,
        "description": description, "category": category,
    }, None


def _summary_create_booking_type(payload: dict[str, Any]) -> str:
    price = f"${payload['price_cents'] / 100:.2f}" if payload.get("price_cents") else "free"
    return f'Add a "{payload["name"]}" booking type ({payload["duration_minutes"]} min, {price})'


async def _execute_create_booking_type(conn, site: dict[str, Any], account: Any, payload: dict[str, Any]) -> dict[str, Any]:
    row = await conn.fetchrow(
        """INSERT INTO cappe_booking_types (site_id, name, description, duration_minutes, price_cents, category)
           VALUES ($1, $2, $3, $4, $5, $6)
           RETURNING id, name""",
        site["id"], payload["name"], payload.get("description"), payload["duration_minutes"],
        payload.get("price_cents"), payload.get("category"),
    )
    return {"booking_type_id": str(row["id"]), "name": row["name"]}


# ---------------------------------------------------------------------------
# set_promo — the FIRST server-side write gate on meta_config.promos. Today
# it's only ever hidden client-side (PromosPanel.tsx's `premium` prop); this
# is what makes the gate real.
# ---------------------------------------------------------------------------

_PROMO_TARGETS = frozenset({"bar", "popup"})
_PROMO_POSITIONS = frozenset({"top", "bottom"})
_PROMO_MODES = frozenset({"newsletter", "cta", "code"})


def _validate_set_promo(payload: dict[str, Any]) -> tuple[Optional[dict[str, Any]], Optional[str]]:
    if not isinstance(payload, dict):
        return None, "invalid payload"
    target = payload.get("target")
    if target not in _PROMO_TARGETS:
        return None, "'target' must be 'bar' or 'popup'"
    enabled = payload.get("enabled", True)
    if not isinstance(enabled, bool):
        return None, "'enabled' must be true or false"
    out: dict[str, Any] = {"target": target, "enabled": enabled}

    if target == "bar":
        text = payload.get("text")
        if enabled:
            if not isinstance(text, str) or not (1 <= len(text.strip()) <= 200):
                return None, "'text' must be 1-200 characters"
            text = text.strip()
        elif text is not None and not isinstance(text, str):
            return None, "'text' must be text"
        cta_label = payload.get("cta_label")
        if cta_label is not None and (not isinstance(cta_label, str) or len(cta_label) > 60):
            return None, "'cta_label' must be at most 60 characters"
        cta_href = payload.get("cta_href")
        if cta_href is not None and (not isinstance(cta_href, str) or len(cta_href) > 300):
            return None, "'cta_href' must be at most 300 characters"
        position = payload.get("position", "top")
        if position not in _PROMO_POSITIONS:
            return None, "'position' must be 'top' or 'bottom'"
        dismissible = payload.get("dismissible", True)
        if not isinstance(dismissible, bool):
            return None, "'dismissible' must be true or false"
        out.update(text=text, cta_label=cta_label, cta_href=cta_href, position=position, dismissible=dismissible)
    else:
        heading = payload.get("heading")
        if enabled:
            if not isinstance(heading, str) or not (1 <= len(heading.strip()) <= 120):
                return None, "'heading' must be 1-120 characters"
            heading = heading.strip()
        elif heading is not None and not isinstance(heading, str):
            return None, "'heading' must be text"
        body = payload.get("body")
        if body is not None and (not isinstance(body, str) or len(body) > 400):
            return None, "'body' must be at most 400 characters"
        mode = payload.get("mode", "newsletter")
        if mode not in _PROMO_MODES:
            return None, "'mode' must be 'newsletter', 'cta', or 'code'"
        cta_label = payload.get("cta_label")
        if cta_label is not None and (not isinstance(cta_label, str) or len(cta_label) > 60):
            return None, "'cta_label' must be at most 60 characters"
        out.update(heading=heading, body=body, mode=mode, cta_label=cta_label)

    return out, None


def _gate_set_promo(payload: dict[str, Any], entitlements: Entitlements, plan: str) -> Optional[str]:
    if is_premium_plan(plan):
        return None
    return (
        "Promo banners are a Pro/Business/Creator feature — your plan can't turn one on. "
        "Upgrade first, then ask me again and I'll set it up."
    )


def _summary_set_promo(payload: dict[str, Any]) -> str:
    label = "announcement bar" if payload["target"] == "bar" else "pop-up"
    action = "Enable" if payload["enabled"] else "Turn off"
    return f"{action} the {label} promo"


async def _execute_set_promo(conn, site: dict[str, Any], account: Any, payload: dict[str, Any]) -> dict[str, Any]:
    row = await conn.fetchrow(
        "SELECT meta_config FROM cappe_sites WHERE id = $1 FOR UPDATE", site["id"]
    )
    meta = loads(row["meta_config"]) if row else {}
    promos = meta.get("promos") if isinstance(meta.get("promos"), dict) else {}
    target = payload["target"]
    current = promos.get(target) if isinstance(promos.get(target), dict) else {}
    updated = dict(current)
    for key, value in payload.items():
        if key in ("target", "enabled") or value is None:
            continue
        updated[key] = value
    updated["enabled"] = payload["enabled"]
    meta = {**meta, "promos": {**promos, target: updated}}
    await conn.execute(
        "UPDATE cappe_sites SET meta_config = $2, updated_at = NOW() WHERE id = $1",
        site["id"], json.dumps(meta),
    )
    return {"target": target, "enabled": payload["enabled"]}


# ---------------------------------------------------------------------------
# The registry
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SetupActionSpec:
    name: str
    validate: Callable[[dict[str, Any]], tuple[Optional[dict[str, Any]], Optional[str]]]
    # Takes the NORMALIZED payload (not just plan/entitlements) — see module
    # docstring. Returns a human-readable block reason, or None to allow.
    gate: Callable[[dict[str, Any], Entitlements, str], Optional[str]]
    execute: Callable[..., Any]  # async (conn, site, account, payload) -> dict
    summary: Callable[[dict[str, Any]], str]
    prompt_shape: str = ""
    prompt_rules: tuple[str, ...] = field(default_factory=tuple)


SETUP_ACTIONS: tuple[SetupActionSpec, ...] = (
    SetupActionSpec(
        name="create_page",
        validate=_validate_create_page,
        gate=_gate_none,
        execute=_execute_create_page,
        summary=_summary_create_page,
        prompt_shape='{"title":"<page title>","preset":"about"|"contact"|"services"|"shop"|null,"blocks":[{...}]|null}',
        prompt_rules=(
            "Prefer a preset over hand-building blocks — presets are professionally composed and cover "
            "the common asks (\"make an about page\", \"add a contact page\", \"add a services page\", "
            "\"add a shop page\"). Only pass 'blocks' when the user describes something a preset doesn't fit.",
        ),
    ),
    SetupActionSpec(
        name="add_blocks",
        validate=_validate_add_blocks,
        gate=_gate_none,
        execute=_execute_add_blocks,
        summary=_summary_add_blocks,
        prompt_shape='{"page_id":"<id from context>","blocks":[{"type":"<blockType>",...fields...}],"at":<index>|null}',
        prompt_rules=(
            "Use this to add a single section to an EXISTING page — most commonly a newsletter signup "
            "block (type 'newsletter') or a store/booking widget block (type 'store'|'booking') onto the "
            "home page. 'at' omitted appends at the end.",
        ),
    ),
    SetupActionSpec(
        name="create_product",
        validate=_validate_create_product,
        gate=_gate_create_product,
        execute=_execute_create_product,
        summary=_summary_create_product,
        prompt_shape='{"name":"<product name>","fulfillment":"physical"|"digital"|"service"|"booking","price_cents":<int>,"description":"<optional>","digital_file_url":"<optional, digital only>","category":"<optional>"}',
        prompt_rules=(
            "'service'/'booking' fulfillment is for selling a session or appointment WITHOUT a booking "
            "calendar — prefer create_booking_type instead when the user wants real availability/scheduling.",
            "A digital product with no digital_file_url is created as a draft (nothing to deliver yet) — "
            "say so, and point them to Shop to attach the file.",
        ),
    ),
    SetupActionSpec(
        name="create_booking_type",
        validate=_validate_create_booking_type,
        gate=_gate_none,
        execute=_execute_create_booking_type,
        summary=_summary_create_booking_type,
        prompt_shape='{"name":"<e.g. 1:1 coaching call>","duration_minutes":<int>,"price_cents":<int>|null,"description":"<optional>","category":"<optional>"}',
        prompt_rules=(
            "This is a real bookable session with a calendar — the right choice for \"sell a booking "
            "session\"/\"sell 1:1 time\", not create_product with fulfillment='booking'.",
        ),
    ),
    SetupActionSpec(
        name="set_promo",
        validate=_validate_set_promo,
        gate=_gate_set_promo,
        execute=_execute_set_promo,
        summary=_summary_set_promo,
        prompt_shape='{"target":"bar"|"popup","enabled":true,"text":"<bar only>","heading":"<popup only>","body":"<popup only>","cta_label":"<optional>","cta_href":"<bar only, optional>","position":"top"|"bottom","mode":"newsletter"|"cta"|"code","dismissible":true}',
        prompt_rules=(
            "'bar' is the site-wide announcement strip; 'popup' is a modal. Only send the fields that "
            "target uses. This is Pro/Business/Creator only — say so plainly if the plan doesn't allow it "
            "rather than staging something that will just get blocked.",
        ),
    ),
)

SETUP_ACTIONS_BY_NAME: dict[str, SetupActionSpec] = {a.name: a for a in SETUP_ACTIONS}


# ---------------------------------------------------------------------------
# Evaluation — pure, DB-free. See module docstring for why stage/execute
# share one gate function per action instead of two hand-written copies.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Verdict:
    kind: Literal["stage", "blocked", "invalid", "proceed", "refuse"]
    message: str = ""
    # Populated only for kind == "stage": the validated/normalized payload to
    # actually persist (never the model's raw, unfiltered one).
    payload: Optional[dict[str, Any]] = None


def evaluate_setup_stage(
    action_type: str, payload: Any, *, entitlements: Entitlements, plan: str
) -> Verdict:
    """Should a newly-proposed action be staged, or refused outright?"""
    spec = SETUP_ACTIONS_BY_NAME.get(action_type)
    if spec is None:
        return Verdict("invalid", f"unknown action type '{action_type}' — expected one of: {', '.join(sorted(SETUP_ACTIONS_BY_NAME))}")
    normalized, error = spec.validate(payload if isinstance(payload, dict) else {})
    if error:
        return Verdict("invalid", error)
    blocked = spec.gate(normalized, entitlements, plan)
    if blocked:
        return Verdict("blocked", blocked)
    return Verdict("stage", spec.summary(normalized), payload=normalized)


def evaluate_setup_execute(
    entry: dict[str, Any], *, entitlements: Entitlements, plan: str, this_turn_staged_ids
) -> Verdict:
    """May this already-staged entry run now?

    Confirm-first, structurally: `this_turn_staged_ids` is the set of entry
    ids the CURRENT turn itself just staged (tracked by the caller's tool
    loop, empty for the REST approve button) — an id in it is refused, so the
    model can't stage-then-immediately-confirm inside one turn no matter what
    it's told to do. Idempotent: any status other than 'proposed' refuses.
    """
    entry_id = entry.get("id")
    if entry_id in this_turn_staged_ids:
        return Verdict("refuse", "That was just proposed — confirm it on a later message, not the same turn it was staged in.")
    status_ = entry.get("status")
    if status_ != "proposed":
        return Verdict("refuse", f"That action is already {status_} and can't be run again.")
    spec = SETUP_ACTIONS_BY_NAME.get(entry.get("type"))
    if spec is None:
        return Verdict("refuse", "Unknown action type.")
    blocked = spec.gate(entry.get("payload") or {}, entitlements, plan)
    if blocked:
        return Verdict("blocked", blocked)
    return Verdict("proceed")


async def execute_setup_action(conn, site: dict[str, Any], account: Any, entry: dict[str, Any]) -> dict[str, Any]:
    """Authoritative execute: re-resolves entitlements (never trusts the
    stage-time gate result — the plan may have changed since), re-runs the
    same gate, then runs the DB write. Caller must have already confirmed via
    `evaluate_setup_execute` returning 'proceed' — this does not repeat the
    same-turn/idempotency check, only the entitlement one, since that's the
    one thing that can legitimately change between stage and execute.

    Returns `{"ok", "status", "message", "result"?}` — never raises for an
    expected failure (gate block, `SetupActionError`); an unexpected
    exception from `spec.execute` propagates, matching the rest of the
    codebase's "don't swallow real bugs" convention.
    """
    spec = SETUP_ACTIONS_BY_NAME.get(entry["type"])
    if spec is None:
        return {"ok": False, "status": "blocked", "message": "Unknown action type."}
    ent = await resolve_entitlements(account.plan, conn=conn)
    blocked = spec.gate(entry["payload"], ent, account.plan)
    if blocked:
        return {"ok": False, "status": "blocked", "message": blocked}
    try:
        result = await spec.execute(conn, site, account, entry["payload"])
    except SetupActionError as exc:
        return {"ok": False, "status": "blocked", "message": str(exc)}
    return {
        "ok": True, "status": "executed", "result": result,
        "message": f"Done — {spec.summary(entry['payload'])}.",
    }


# ---------------------------------------------------------------------------
# Staged-entry helpers — pure closures for `store.mutate_staged_actions`.
# ---------------------------------------------------------------------------

def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def new_staged_entry(action_type: str, payload: dict[str, Any], summary: str) -> dict[str, Any]:
    return {
        "id": str(uuid4()), "type": action_type, "summary": summary, "payload": payload,
        "status": "proposed", "result": None, "message": None,
        "created_at": _now_iso(), "executed_at": None,
    }


def append_entry(entry: dict[str, Any]) -> Callable[[list[dict[str, Any]]], list[dict[str, Any]]]:
    def _fn(current: list[dict[str, Any]]) -> list[dict[str, Any]]:
        return [*current, entry]
    return _fn


def apply_outcome(entry_id: str, outcome: dict[str, Any]) -> Callable[[list[dict[str, Any]]], list[dict[str, Any]]]:
    """`outcome` is `execute_setup_action`'s return value.

    Only applies while the entry is still 'proposed' — same guard
    `dismiss_entry` uses. The real race guard is upstream of this function:
    both confirm callers (`routes/merlin_setup.py:_apply_action_outcome`,
    `services/merlin/setup_agent.py:do_execute_staged_action`) now hold a
    `merlin_store.lock_conversation_actions` row lock for the ENTIRE
    check-write-flip sequence, inside one transaction — so a second
    concurrent confirmation blocks on the lock and, once it acquires it,
    re-reads a status that is no longer 'proposed' and refuses before this
    closure ever runs twice for the same entry. This `status == 'proposed'`
    check is a defense-in-depth idempotency guard, not the sole race guard."""
    def _fn(current: list[dict[str, Any]]) -> list[dict[str, Any]]:
        out = []
        for e in current:
            if e.get("id") != entry_id or e.get("status") != "proposed":
                out.append(e)
                continue
            updated = dict(e)
            updated["status"] = outcome["status"]
            updated["message"] = outcome.get("message")
            if outcome["status"] == "executed":
                updated["result"] = outcome.get("result")
                updated["executed_at"] = _now_iso()
            out.append(updated)
        return out
    return _fn


def dismiss_entry(entry_id: str) -> Callable[[list[dict[str, Any]]], list[dict[str, Any]]]:
    def _fn(current: list[dict[str, Any]]) -> list[dict[str, Any]]:
        out = []
        for e in current:
            if e.get("id") == entry_id and e.get("status") == "proposed":
                e = {**e, "status": "dismissed"}
            out.append(e)
        return out
    return _fn


def find_entry(entries: Optional[list[dict[str, Any]]], entry_id: str) -> Optional[dict[str, Any]]:
    for e in entries or []:
        if e.get("id") == entry_id:
            return e
    return None
